### ISSUE TITLE
missing npm packages - ws and request for your examples

### ISSUE THREAD

**Issue by developerwok** [jaggedsoft/node-binance-api#1]

**Comment by jaggedsoft** [comment]
I can not reproduce this problem, When installing via npm, it should automatically install `ws` and `request` .. I did this on another machine and it installed them for me.
![image](https://user-images.githubusercontent.com/4283360/31806177-02481672-b51b-11e7-997e-d26ba2583be9.png)

However, you should be able to solve by this command:
`npm install ws request -g`

**Comment by jaggedsoft** [comment]
If that does not fix it then navigate to your project directory and type:
`npm install ws request`
