### ISSUE TITLE
Err 404 when buy,sell, etc.. 

### ISSUE THREAD

**Issue by DoTradesWell** [jaggedsoft/node-binance-api#103]
I'm using local server on a Chrome browser to run the following code:

`
const binance = require('./node-binance-api.js');

binance.options({
  APIKEY: '****MY-API-KEY****',
  APISECRET: '****MY-SECRET-API***',
  useServerTime: false, // If you get timestamp errors, synchronize to server time at startup
  test: true // If you want to use sandbox mode where orders are simulated
});

binance.prices('ETHBTC', (error, ticker) => {
  console.log("Price of ETHBTC: ", ticker.ETHBTC);
});

var quantity = 0.05 ;
binance.marketBuy("ETHBTC", quantity);
`

I've gotten the binance.prices to work using this wrapper, however, whenever there is a more secure network is needed, which involve my API-key or Secret-Key, i cannot seem to retrieve information. 

My assumptions for this possibility:
1. Chrome browser is not supported by binance api server 
2. My API-Key/Secret-Key are banned from binance api 
3. Code is not primed for more secure options

Let me know what you think. Thanks in advance!

**Comment by jaggedsoft** [comment]
Hi there, unfortunately running any API on any exchange is not possible as far as I know.
The reason for this is CORS
You can test it by yourself with a simple request in your javascript console (Press Ctrl+Shift+J)

```js
fetch('https://api.binance.com');
```

Returns this
![image](https://user-images.githubusercontent.com/4283360/35783742-21a8b288-09c1-11e8-822a-1231b125e8ef.png)

You will get the same result if you try `api.poloniex.com` or `bittrex.com` therefore I am convinced that this is not possible without some sort of workaround. Others have mentioned putting an entry in your hosts file to get around this. Personally, I do everything server side.

https://github.com/jaggedsoft/node-binance-api/issues/52
https://github.com/jaggedsoft/node-binance-api/issues/38
https://github.com/jaggedsoft/node-binance-api/issues/27
https://github.com/binance-exchange/node-binance-api/issues/64
https://github.com/binance-exchange/node-binance-api/issues/55
https://github.com/binance-exchange/node-binance-api/issues/27
https://github.com/binance-exchange/node-binance-api/issues/12

**Comment by DoTradesWell** [comment]
I've tried CORS browser extension to bypass some preflights with allow orgin headers, however, this only worked for "GET" functions. As soon as I attempted "POST", I've tried adding headers that shown in  public api but this only resulted in errors of 400, 401, 404. 

I am convinced you're right, and I'm going to attempt trying server-side rather than client-side.

Thank you for your answer. I might be back with an update on my situation.

**Comment by jaggedsoft** [comment]
I think people have had some success with electron, turning it into a desktop app https://electronjs.org
But I haven't tested it for that

**Comment by DoTradesWell** [comment]
Thank you, I'll give that a try.

**Comment by DoTradesWell** [comment]
Awesome, I gave Electron a preliminary order test. 

It worked! Thanks a bunch for the help!
