### ISSUE TITLE
Wont ever buy? API Buy not working

### ISSUE THREAD

**Issue by springjben** [jaggedsoft/node-binance-api#105]
Using this API will not allow me to make trades?

        let price = parseFloat(data.pricePerUnit)
        let btcBalance = parseFloat(data.btcbalance) * 0.98 //to cover fees
        let qty = parseFloat(btcBalance / price).toFixed(8)

        binance.buy(data.coin + "BTC", qty, price, {type:'LIMIT'}, (error, response) => {
          console.log("Limit Buy response", response);
          console.log("order id: " + response.orderId);
        });

**Comment by springjben** [comment]
I get this in the response:

Limit Buy response {}
order id: undefined

Doesn#t work with binance.marketBuy("BNBBTC", qty); either.

My API keys are correct and working. It can get my balances but doesn't make trades. 

Oh and my API keys have it ticked to allow trading.

**Comment by jaggedsoft** [comment]
`if ( error ) return console.error(error);`

Add that to the top of your function
only other reason this should happen is if `test: true` is set in options

**Comment by jaggedsoft** [comment]
You can report back with the error it says and I will help

**Comment by springjben** [comment]
body: '{"code":-1013,"msg":"Filter failure: LOT_SIZE"}' }

Thats the error I am getting. What is Filter Failure

**Comment by jaggedsoft** [comment]
So that means you are not buying enough of something

You can call exchangeInfo() to see the minimums on every coin

#### exchangeInfo(): Pull minimum order size, quantity, etc.
```js
//minQty = minimum order quantity
//minNotional = minimum order value (price * quantity)
binance.exchangeInfo(function(error, data) {
	let minimums = {};
	for ( let obj of data.symbols ) {
		let filters = {minNotional:0.001,minQty:1,maxQty:10000000,stepSize:1,minPrice:0.00000001,maxPrice:100000};
		for ( let filter of obj.filters ) {
			if ( filter.filterType == "MIN_NOTIONAL" ) {
				filters.minNotional = filter.minNotional;
			} else if ( filter.filterType == "PRICE_FILTER" ) {
				filters.minPrice = filter.minPrice;
				filters.maxPrice = filter.maxPrice;
			} else if ( filter.filterType == "LOT_SIZE" ) {
				filters.minQty = filter.minQty;
				filters.maxQty = filter.maxQty;
				filters.stepSize = filter.stepSize;
			}
		}
		minimums[obj.symbol] = filters;
	}
	console.log(minimums);
	fs.writeFile("minimums.json", JSON.stringify(minimums, null, 4), function(err){});
});
```
![example](https://image.ibb.co/bz5KAG/notationals.png)

**Comment by jaggedsoft** [comment]
if minNotional is .001 that means you have to buy at minimum .001 btc worth
if the amount is smaller than minQty then you need to increase the amount to minQty as well
You also have to round to stepSize

```js
if ( amount < minQty ) amount = minQty;
if ( price * amount < minNotional ) {
	amount = minNotional / price;
}
amount = binance.roundStep(amount, global.minimums[symbol].stepSize); // I save the minimums above to a global object
```

**Comment by springjben** [comment]
Thank you for your answer, what is the stepSize? I am a little confused. Sorry

**Comment by jaggedsoft** [comment]
Some coins let you only order in quantities of 1, for example
XRP:
minNotional is .002 meaning you have to buy at minimum .002 btc worth
stepSize is 1 meaning you can only order in increments of 1, you can't order 1.5 for example
minQty means that the minimum amount you can order must be 1 or more (plus the other rules too)

**Comment by springjben** [comment]
Also, how will I test this? If I enable the test feature on your API, what will that do? Does it just fake the payments?

**Comment by jaggedsoft** [comment]
Test feature of the api is kind of boring, it just returns a blank response instead of posting the order
I tested mine live but with small amounts
When i first got my bot going i always did slightly over the abosolute minimum purchases

**Comment by jaggedsoft** [comment]
I'm considering adding a paper trading module we can plug in later, but right now the priority is getting the library to be easier to use, faster, and more stable

**Comment by springjben** [comment]
I am really really really sorry for asking another cheeky question. Last one I promise.

How will I know if an order has successfully been completed? If the order doesn't get completed right there and then, do I just run a loop testing if its been fulfilled? How did you approach this?

Also, do you have a donation address?

**Comment by jaggedsoft** [comment]
The best way to know if an order went through, is by checking the order id. If you have an order id and `error` is not set then your order has been successful. Market orders are my favorite but unfortunately binance's api won't return the price you paid
```js
var quantity = 1;
binance.marketBuy("BNBBTC", quantity, (error, response) => {
  console.log("Market Buy response", response);
  console.log("order id: " + response.orderId);
  // Now you can limit sell with a stop loss, etc.
});
```

Donations are absolutely not necessary. If you insist, ETH address is `0x0D1c87a87eD9503D5139D6ed29530865B8a938bA`

**Comment by springjben** [comment]
Hey,
So I am using your exchangeInfo function, in an external file. However its returning undefined because its returning too quickly. I am trying to use .then but it doesn't work. I was going to use Promise() but it halts the server. Seems like its would be an easy fix. Oh and, do you have a BTC address? Can't purchase ETH atm. Thank you, I know its not really a binance problem.

My main file:
    await func.getCoinFigs().then(v => {
      console.log("Test:" + v)
    })

Func.js:

async function getCoinFigs() {
  binance.exchangeInfo(function(error, data) {
    let minimums = {};
    for ( let obj of data.symbols ) {
      let filters = {minNotional:0.001,minQty:1,maxQty:10000000,stepSize:1,minPrice:0.00000001,maxPrice:100000};
      for ( let filter of obj.filters ) {
        if ( filter.filterType == "MIN_NOTIONAL" ) {
          filters.minNotional = filter.minNotional;
        } else if ( filter.filterType == "PRICE_FILTER" ) {
          filters.minPrice = filter.minPrice;
          filters.maxPrice = filter.maxPrice;
        } else if ( filter.filterType == "LOT_SIZE" ) {
          filters.minQty = filter.minQty;
          filters.maxQty = filter.maxQty;
          filters.stepSize = filter.stepSize;
        }
      }
      minimums[obj.symbol] = filters;
      return minimums;
    }
    //return minimums
    //fs.writeFile("minimums.json", JSON.stringify(minimums, null, 4), function(err){});
  });
}

**Comment by jaggedsoft** [comment]
Unfortunately I have not switched to promises yet. I'm an old school programmer so still not confident in switching everything over yet. It's on the list though

My BTC address is `1C5gqLRs96Xq4V2ZZAR1347yUCpHie7sa` - donations are not required, but appreciated. Have a great day :)

**Comment by jaggedsoft** [comment]
This library has had support for promises since day one
https://github.com/binance-exchange/binance-api-node

**Comment by nicolas-martin** [comment]
@jaggedsoft so if `test` is set to true, it won't even return anything? Trying to tests stuff without actually making any trades.

**Comment by jaggedsoft** [comment]
correct, won't return anything. I was expecting more

**Comment by springjben** [comment]
Hey sorry, is there a good way of checking if an order has been complete?

Currently I am just creating a setInterval (looping) every second that calls getOpenOrders, if the order has been fulfilled it will tell the user. It loops for 50 seconds, if nothing happens it just cancels the order.

There MUST be a better way of doing this!

**Comment by jaggedsoft** [comment]
Yeah the websocket should tell you whenever your orders get filled
https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#user-data-account-balance-updates-trade-updates-new-orders-filled-orders-cancelled-orders-via-websocket

I haven't figured out the best way of doing it myself, so I just use market orders with newOrderRespType set to FULL
Thanks for the suggestion. We'll need to figure something out in v0.5.0 to make this process much easier, it'll be a nice addition

```js
// Market buy with amount (Thanks matthewwoop!)
// This function showcases the use of newOrderRespType
let quantity = 1;
const flags = {type: 'MARKET', newOrderRespType: 'FULL'};
binance.marketBuy("BNBBTC", quantity, flags, function(error, response) {
	if ( error ) return console.error(error);
	console.log("Market Buy response", response);
	console.log("order id: " + response.orderId);
	console.log("First price: "+response.fills[0].price);
});
```

![image](https://user-images.githubusercontent.com/4283360/36094574-acb15ae6-0fa3-11e8-9209-e6f528e09e84.png)
First price: 0.00106140

**Comment by springjben** [comment]
With your example above, I assume without using websockets its just showing the initial purchases (it bought straight away). 

And thank you.

**Comment by jaggedsoft** [comment]
Yep and likewise thanks for the good ideas
The market buy example is how I'm currently doing it, just posted it here to remind myself to add it to the examples, but I'd love to make managing limit orders much easier

**Comment by springjben** [comment]
If you ever need any basic help (testing, writing documentation) or whatever, hit me up. Would love to help out. 

And thanks once again.

**Comment by springjben** [comment]
I think there is a big with the advanced execution update function. It executes twice. Its either that or my trade it so small it does it in one, outputs it bought it and then outputs the final transaction? I dunno.

![capture](https://user-images.githubusercontent.com/32540273/36280114-2ed92c02-1291-11e8-9264-d102e31c97e9.PNG)

**Comment by jaggedsoft** [comment]
I will look in to this, thanks

**Comment by springjben** [comment]
Sometimes it happens 3 times. Maybe its my set up. Let me know if you find the problem :)

![capture](https://user-images.githubusercontent.com/32540273/36280500-5c14ba3c-1292-11e8-9827-e23d97c19712.PNG)

**Comment by springjben** [comment]
I think I have figured it out after some vigorous testing. It shows when the order is first made. The other one is when the order is complete (or is partially filled). Annoying but oh well.

**Comment by springjben** [comment]
Actually, no thats not the problem. Its something else. So weird.

**Comment by amirws** [comment]
Hi, Did you resolved the problem? I have the same problem: I'm getting : Limit sell response {}
order id: undefined when try to do a sell:               

binance.sell("BTCUSDT", quantity, price, {type:'LIMIT'}, (error, response) => {
                console.log("Limit sell response", response);
                console.log("order id: " + response.orderId);
              });

**Comment by jaggedsoft** [comment]
@amirws for situation it would benefit to have some error handling. for example:

```js
binance.sell("BTCUSDT", quantity, price, {type:'LIMIT'}, (error, response) => {
if ( error ) return console.error("SELL error: ", error);
console.log("Limit sell response", response);
console.log("order id: " + response.orderId);
});
```

**Comment by amirws** [comment]
I'm getting : body: '{"code":-2010,"msg":"Account has insufficient balance for requested action."}' }
It's my operation:   '/api/v3/order?symbol=BTCUSDT&side=SELL&type=LIMIT&quantity=0.002149&price=6750 .  

The minimun is 0.002 right?

**Comment by jaggedsoft** [comment]
Yes you can view how to pull the minimums here: [Advanced examples](https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#exchangeinfo-pull-minimum-order-size-quantity-etc)

```js
{ status: 'TRADING',
  minPrice: '0.01000000',
  maxPrice: '10000000.00000000',
  tickSize: '0.01000000',
  stepSize: '0.00000100',
  minQty: '0.00000100',
  maxQty: '10000000.00000000',
  minNotional: '10.00000000',
  orderTypes:
   [ 'LIMIT',
     'LIMIT_MAKER',
     'MARKET',
     'STOP_LOSS_LIMIT',
     'TAKE_PROFIT_LIMIT' ],
  icebergAllowed: true }
```

minNotional is $10 USDT
You can double check your numbers by punching in the same values on the binance webpage
![image](https://user-images.githubusercontent.com/4283360/38176615-f424fcec-35a6-11e8-8ac2-e854266fbcb3.png)

So here it shows that would be $14.50 USDT which looks like it would be fine. Maybe you should check your open orders and close any open orders you have
