### ISSUE TITLE
Trade updates (websocket) are in fact Aggregate Trade streams

### ISSUE THREAD

**Issue by aviggiano** [jaggedsoft/node-binance-api#107]
Currently the `binance.websockets.trades` function subscribes to the [@aggTrade](https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L906) stream, while there is a separate [@trade](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#trade-streams) stream on the Binance API documentation.

It would be better if the current method was renamed `binance.websockets.aggTrades` and a new `binance.websockets.trades` was created, but I guess this would break the compatibility of this module. 

I propose then implementing a `binance.websockets.recentTrades` method (to maintain [this convention](https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L752)) on the current version and maybe reevaluating if it is worth breaking the compatibility on the next major version of this module.

What do you think about it? I can submit a PR.

**Comment by jaggedsoft** [comment]
Yeah good call I can see how this would be confusing. @trades was an afterthought since it only came out recently
Will think about this some more

**Comment by jaggedsoft** [comment]
More importantly, we need to support the `(symbol)@trade` websocket functionality
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#trade-streams

**Comment by soshhowell** [comment]
Also, great work guys! Don't want to start out negative.

**Comment by jaggedsoft** [comment]
That was binance being down for a few hours, I think it's back now :)

**Comment by jaggedsoft** [comment]
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension

**Comment by soshhowell** [comment]
Thanks for the link! I think your right about it being because of the upgrade/extension, though the pricing part is still down for me. I'll just keep an eye on that link.
