### ISSUE TITLE
Testing Trades

### ISSUE THREAD

**Issue by alteredorange** [jaggedsoft/node-binance-api#108]
Thanks for the awesome wrapper! I'm been doing some basic playing around, and I'm wondering,

1. When I'm in test mode, it looks like it just gets an order ready but doesn't submit anything, is that correct?

2. Because of this I'm assuming you can't tweak variables like your portfolio starting amount, and then track buys and sells and see what kind of profit you'd make off of a trade, right?

Thanks again!

**Comment by alteredorange** [comment]
Just read through another issue that mentioned test doesn't really do anything :) OH well!

**Comment by jaggedsoft** [comment]
Correct. That's just how they made it, kind of silly
But I would like to develop a paper testing module you could just plug in and easily adjust yourself
