### ISSUE TITLE
Adding Rate Limits

### ISSUE THREAD

**Issue by nickreese** [jaggedsoft/node-binance-api#110]
Fantastic work on this codebase. Since I've never done a pull request, I wanted to drop this potential improvement here as there is a lesser chance I'll bork something.

Background: So my bot does a ton of requests in the background to get historical data and I was having issues getting banned, so I had created a temporary hack that I had to merge each time you updated. 

Today, I figured it would be worth just cleaning up the code so others can benefit. 

### Refactored Request function to include rate limiting.

I've refactored the body of each of the request functions into one core function and added rate limiting.

```
	let callWeight, requestCount = 0, requestInitTime = Date.now();

	const makeRequest = function(opt, done){
		// If our last requestInitTime was more than a minute ago. Reset our count.
		if(Date.now() - requestInitTime > 60*1000){
			requestCount = 0;
			requestInitTime = Date.now();
		}

		if(opt.url.indexOf('depth') > -1){
			callWeight = 10;
		} else if(opt.url.indexOf('historicalTrades') > -1){
			callWeight = 5;
		} else {
			callWeight = 1;
		}

		options.log(opt.caller, requestCount, opt.url);

		if(requestCount < 1000 || opt.caller === 'signedRequest'){
			requestCount += callWeight;	
			request(opt, function(error, response, body) {
				if ( !done ) return;
				if ( error ) {
					options.log(Error(error));
					return done( error, {} );
				}

				if ( response && response.statusCode !== 200 ) {
					return done( response, {} );
				}
				
				return done( null, JSON.parse(body) );
			});
		} else {
			console.log('delaying:', opt.url)
			setTimeout(() => {
				makeRequest(opt, done);
			}, Date.now() - requestInitTime + 60*1000 );
		}
	}

```

### Refactored requests:

Then I've refactored each of the "requests" to be as follows: 

```
	const publicRequest = function(url, data, callback, method = 'GET') {
		if ( !data ) data = {};
		let opt = {
			caller: 'publicRequest',
			url: url,
			qs: data,
			method: method,
			timeout: options.recvWindow,
			agent: false,
			headers: {
				'User-Agent': userAgent,
				'Content-type': contentType
			}
		};
		makeRequest(opt, callback)
	};

```
The only thing that I added to each request was a "caller" to the opts so I could debug better. 

### Assumptions

I've set the rate limit to 1000 and then defer all requests that aren't signed ones. The logic here is a bit weak as others may issue 200+ signed requests in a minute though I know mine won't ever encounter that edge case.

### Tested

I've tested this quiet thoroughly and can download data on a huge amount of markets without getting banned.

**Comment by jaggedsoft** [comment]
Thank you for your contribution!
Excellent. I was wanting to add this at some point.
I was originally wanting to do this under a flag that would default to true.
But with your implementation, I don't see any reason this shouldn't just be merged in to the main codebase. Looks like it will just work

**Comment by keith1024** [comment]
Thanks for sharing this @nickreese. I also handle rate limiting in a similar way in my wrapper of this library, and had it on my "if I had more time" list, to eventually add into the library itself.

I'm not 100% when @jaggedsoft will implement and merge this, but I'm sure if you opened a PR it would be much sooner, as it would require a lot less of his time. 👍 

A couple of suggestions from my side though.

1. The library should get its limit from a call to `exchangeInfo`.
2. The `depth` endpoint should take into account its `limit` argument and set the weight as _1, 5, 10_ appropriately.
3. _signedRequest_ calls should not be segregated from the limiting.
4. the delaying `setTimeout` should be clamped to its _interval window_ defined by `requestInitTime `. ie. if I've reached my limit at _55_ seconds, the next request should be delayed _5_ seconds, and not _65_ seconds.

```javascript
// Results in a (60000 + <the difference>)ms delay.
setTimeout(() => {}, Date.now() - requestInitTime + 60*1000 );

// Results in a <the difference>ms delay or it'll be scheduled
// immediately in the next event loop if <= 0.
setTimeout(() => {}, (60 * 1000) - (Date.now() - requestInitTime));
```

**Comment by nickreese** [comment]
@keith1024 Thanks for the feedback. Never done a pull request and in fact until I started this side project, I would have considered myself more of a 'let me find a solution on stack exchange' than someone who would wield JS with any skill outside the browser. I'll take a look at prettying it up as long as you guys are good tearing it apart if it is junk. :) I guess everyone has to start somewhere. 

The main thing I can't figure out is how to manage the counter limits with multiple instances running. 

---

Notes:

1. Agreed.
2. Do you know of a API endpoint where Binance lists the weights? I can only find them in the docs.
3. Signed Requests are inherently timely requests, hence why I tried a simple solution to make sure they should always get through.
4. You're right. Thank you.

**Comment by keith1024** [comment]
@nickreese No problem. I know how it feels to do your first PR, but it really is chilled, just fork the project to your github, clone it to your local machine, do your changes, committing and pushing to your heart's content on your fork, and then when you're ready open that PR, you can still make changes and push commits that may come up in discussion once the PR is open and it'll update on the existing PR. You're spot on, everyone has to start somewhere. :)

This may help... If you move your `let requestCount = 0` and `let requestInitTime = Date.now()`  before the `module.exports = `, all instances of the library will access the same version of those variables, and they won't be polluting the global scope either.
#
Notes:

2. Nah, I believe the per request weights are only available in the docs.
3. I understand where you're coming from, but if I'm sitting on `1200` requests at 58 seconds, and execute a `signedRequest`, Binance won't care and will response with a `429` _rate limit violation_.

**Comment by jaggedsoft** [comment]
Apologies for not merging the changes sooner. Have had way too much on my plate the past couple weeks
If I see PR's, I try to push them through no questions asked
Keep up the great work you guys
