### ISSUE TITLE
Websocket Trade Updates With Buy/Sell Info?

### ISSUE THREAD

**Issue by alteredorange** [jaggedsoft/node-binance-api#111]
I'm using the trade updates websocket:
```
binance.websockets.trades(['LTCBNB'], (trades) => {
  let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
  console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
```
Works great, but is there any way to see if it's buying or selling, and the spread?  As far as I can tell from the docs, Maker is just telling you if it's a market order or limit order.  

Thanks!

**Comment by jaggedsoft** [comment]
Unfortunately that information is not provided
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#aggregate-trade-streams

Maker orders are whichever was placed first, so if you place a limit order and it gets filled, then you were a market maker
if you're just buying from someone else's order, you're a taker

When the price is going up but so is the number of taker orders, then people are market buying more often than normal and this can be taken as a sign of demand

Wish i could help more but I don't see a way to do what you're asking

**Comment by alteredorange** [comment]
Thanks, that helps I think!  Appreciate it!

**Comment by s-a** [comment]
@jaggedsoft but how does walebot alerts work?
