### ISSUE TITLE
Add Withdraw Endpoint

### ISSUE THREAD

**Issue by otisscott** [jaggedsoft/node-binance-api#112]
I was just hoping that you could add a withdraw endpoint. I read on their website that it exists within their API but I cannot find further documentation on it.

**Comment by jaggedsoft** [comment]
Is it not working for you?
Seems to be working

```js
binance.withdraw("ETH", "0x0D1c87a87eD9503D5139D6ed29530865B8a938bA", 0.2);
```

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#signed-endpoint-examples-for-post-wapiv3withdrawhtml
