### ISSUE TITLE
`websockets.terminate()` calls should override `options.reconnect`

### ISSUE THREAD

**Issue by keith1024** [jaggedsoft/node-binance-api#113]
I'm just creating a separate issue for this based on our discussion below, in #102.

![image](https://user-images.githubusercontent.com/4868093/35962447-183ace06-0cba-11e8-8294-848115d526f3.png)

**Comment by jaggedsoft** [comment]
Also open to completely changing how it's currently done. I'm sure there's a better solution

**Comment by keith1024** [comment]
I've just pushed up a branch (https://github.com/jaggedsoft/node-binance-api/commit/8fd11d91ef8aa5f3537f89a146052f8a365f8dbb) that you can have a look at, and see what you think, that I think addresses all the issues without introducing any breaking changes in the way things are done. I must still test it properly though, so I've held off on opening a PR for now.
