### ISSUE TITLE
prevDay reconnect error

### ISSUE THREAD

**Issue by webworker01** [jaggedsoft/node-binance-api#114]
Binance API I believe was down, and my server was dying  [on reconnect](https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L1006)

```
let reconnect = function() {
    if ( options.reconnect ) prevDay(symbol, callback);
};
```

Should this be

```
let reconnect = function() {
    if ( options.reconnect ) prevDay(symbols, callback);
};
```

**Comment by keith1024** [comment]
Whoops. Thanks for spotting that.
