### ISSUE TITLE
Error 5381

### ISSUE THREAD

**Issue by vaielab** [jaggedsoft/node-binance-api#116]
Hello, Since yestersday I keep receiving "WebSocket Unexpected response: 5381"
Anybody know what this error means? I look at the official binance api but there was no mention of it.

**Comment by keith1024** [comment]
Woah, not a clue, but with the insane upgrade Binance seems to be doing to their systems, who knows how much their API is going to have changed, or have added to it. Guess we'll see what updates 14h00 UTC brings us to their docs etc.

**Comment by vaielab** [comment]
Alright, thanks
I was hoping the error was on everybody... I will try it on a other server (different ip) and let you know

**Comment by keith1024** [comment]
I'd consider any communication with the Binance servers as _undefined_ until they announce that their upgrades are complete. Since they suspended trading for the upgrades, there seems have been a lot of "strange" errors popping up.

**Comment by keith1024** [comment]
FYI. [Binance API Telegram - System Upgrade Update](https://user-images.githubusercontent.com/4868093/35976171-f44330aa-0ce7-11e8-8843-a852442e730a.jpg)

Systems back up for trading @ **09/02/2018 04h00 UTC**

**Comment by vaielab** [comment]
This morning I restart my app, and got no error, as you said, it was because of their upgrades.
Thank you
