### ISSUE TITLE
Convenient way to terminate combined websocket streams?

### ISSUE THREAD

**Issue by dakovi** [jaggedsoft/node-binance-api#117]
Question: What is the most convenient way to terminate combined websocket streams? While working with them a few days ago I realized that the advanced examples don't work for combined streams:

binance.websockets.terminate('ethbtc@ticker'); // for prevday
binance.websockets.terminate('ethbtc@kline_1m'); // for candlestick charts

Even if you have only one websocket kline stream running (but still as a combined form) you can't terminate it with the classical trade pair id. At least I wasn't able to do it...I always had to use the numeric endpoint as variable.

So right now I am iterating through the existing websockets with my coin pair as search value (which gets a hit on the url parameter) so I can return the relevant endpoint number and then terminate the connection...not very native.

Maybe it's possible to implement an optional more general handling of terminating combined websockets by their kind (eg binance.websockets.terminate('ticker');) without stressing other websocket connections?

But perhaps I am also totally missing a more obvious and right way to do all this?

**Comment by jaggedsoft** [comment]
If you _need_ to be able to terminate a socket, you'll have to open it by itself for now
Otherwise, the only solution with combined sockets, would be to ignore the data from that stream
