### ISSUE TITLE
async hook stack has become corrupted

### ISSUE THREAD

**Issue by DoTradesWell** [jaggedsoft/node-binance-api#119]
I've have been getting this error: "async hook stack has become corrupted" almost immediately after i connect with Binance server. This has been going on a little before, and now worse after the whole binance update episode. 

Anyone know the generic cause for this? 

I can't seem to pin point the problem. I'm using node-binance-api wrapper v4.12.

**Comment by jaggedsoft** [comment]
Have never heard of this error.  I will look in to it.
Anything unusual going on with your setup? Electron? Other packages?

**Comment by DoTradesWell** [comment]
Not that I see. I may have fixed the problem by increasing the recvwindow.

 I'll return later tonight to verify, I'm off to work.

**Comment by DoTradesWell** [comment]
After increasing the recvWindow, the async corruption error was no longer an issue.
