### ISSUE TITLE
publicRequest error: Error: connect ETIMEDOUT 54.238.203.159:443

### ISSUE THREAD

**Issue by includeleec** [jaggedsoft/node-binance-api#12]
![image](https://user-images.githubusercontent.com/3683190/33214459-fe8571a2-d166-11e7-87de-d024cd559252.png)
if ( !response || !body ) throw "publicRequest error: "+error;
                                                  ^
publicRequest error: Error: connect ETIMEDOUT 54.238.203.159:443

**Comment by jaggedsoft** [comment]
Hi, thank you for the report! I am publishing a new release and will have a fix for you soon.

**Comment by jaggedsoft** [comment]
In this release the `recvWindow` will also set the timeout for all API calls.
Please update to `v0.2.7` by navigating to your project folder and issuing an `npm update`
Then in your project you can adjust your own timeout values like this:

```js
binance.options({
	'APIKEY': 'xxx',
	'APISECRET': 'xxx',
	'recvWindow': 60000
});
```

**Comment by includeleec** [comment]
thank you very much!
