### ISSUE TITLE
Full response from sell order

### ISSUE THREAD

**Issue by cryptonic203** [jaggedsoft/node-binance-api#122]
How can I get full response from sell market order?

$quantity=20
$order = $api->sell("XRPETH", $quantity, 0, "MARKET");

Response:
Array (
[symbol] => XRPETH
[orderId] => 14343614
[clientOrderId] => j2NHdrtyIx5q8uSYI5yr
[transactTime] => 1518382731482
[price] => 0.00000000
[origQty] => 20.00000000
[executedQty] => 20.00000000
[status] => FILLED
[timeInForce] =>GTC
[type] => MARKET
[side] => SELL
) 

Needed:
{
  "symbol": "XRPETH",
  "orderId": 28,
  "clientOrderId": "6gCrw2kRUAF9CvJDGP16IP",
  "transactTime": 1507725176595,
  "price": "0.00000000",
  "origQty": "10.00000000",
  "executedQty": "10.00000000",
  "status": "FILLED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "fills": [
    {
      "price": "0.00122355",
      "qty": "10.00000000",
      "commission": "0.0056000000",
      "commissionAsset": "USDT"
    },
    {
      "price": "0.00122353",
      "qty": "5.00000000",
      "commission": "0.005400000",
      "commissionAsset": "USDT"
    },
    {
      "price": "0.00122345",
      "qty": "5.00000000",
      "commission": "0.0600000",
      "commissionAsset": "USDT"
    }
  ]
}

Nessesary: Prices and quantities of filled order

**Comment by jaggedsoft** [comment]
```js
// Market buy with amount (Thanks matthewwoop!)
// This function showcases the use of newOrderRespType
let quantity = 1;
const flags = {type: 'MARKET', newOrderRespType: 'FULL'};
binance.marketBuy("BNBBTC", quantity, flags, function(error, response) {
	if ( error ) return console.error(error);
	console.log("Market Buy response", response);
	console.log("order id: " + response.orderId);
	console.log("First price: "+response.fills[0].price);
});
```

![image](https://user-images.githubusercontent.com/4283360/36094574-acb15ae6-0fa3-11e8-9209-e6f528e09e84.png)
First price: 0.00106140

I just learned about this and am open to suggestions to make this better, such as adding volume weighted average calculation to return a more accurate price.

**Comment by cryptonic203** [comment]
Suggestion:
$order = $api->sell("XRPETH", $quantity, 0, "MARKET"**,"FULL"**);

Response:
Array (
[symbol] => XRPETH
[orderId] => 14343614
[clientOrderId] => j2NHdrtyIx5q8uSYI5yr
[transactTime] => 1518382731482
[price] => 0.00000000
[origQty] => 20.00000000
[executedQty] => 20.00000000
[status] => FILLED
[timeInForce] =>GTC
[type] => MARKET
[side] => SELL
**[average_price] =>0.0013125**    //--Add
**[full_commission] => 0.01**         //--Add
**[commissionAsset] => 0.01**       //--Add
)

//---------------------------------------------------
$average_price=0;
$full_commision=0;
for ($i=0;$i<count($order['fills']);$i++){
$average_price=$average_price+$order['fills']['qty']*$order['fills']['price'];
$full_commision=$full_commission+$order['fills']['commission']; //--A complex algorithm with different currencies
}
$average_price=$average_price/$order['executedQty'] //-or $average_price/$order['origQty'] 
//---------------------------------------------------
The code is approximate
