### ISSUE TITLE
24hr Price Change Stats Window?

### ISSUE THREAD

**Issue by alteredorange** [jaggedsoft/node-binance-api#127]
Using this snippet, but it looks like it's getting yesterday's data (i.e. if I call today on Tuesday, it get's the 24 hours of Monday.  Is there a way to get the previous 24 Hours of stats (really just need High/low of a symbol) so if I call right now, it will account for right now and back 24 hours?
Thanks!

Get 24hr ticker price change statistics for a symbol
```
binance.prevDay("BNBBTC", (error, prevDay, symbol) => {
  console.log(symbol+" previous day:", prevDay);
  console.log("BNB change since yesterday: "+prevDay.priceChangePercent+"%")
});
```

**Comment by alteredorange** [comment]
I might have spoken too soon, it might be grabbing the rolling 24 hours, not the previous day....

**Comment by jaggedsoft** [comment]
Correct, it compares it from exactly 24 hours prior .. let me know any way I can help
