### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Soljia** [jaggedsoft/node-binance-api#128]
Just a suggestion. Maybe put the error callback as the last parameter, as to not break code for backwards compatability.

Example: 
Old
` if ( callback ) return callback.call(this, error, data, symbol);`
New
` if ( callback ) return callback.call(this, data, symbol, error);`

**Comment by jaggedsoft** [comment]
Thanks for the suggestion. Unfortunately, not every function follows these rules, so it would be counter intuitive

"error first" is the standard way. But with promises we won't have to worry about this anymore, it will be much cleaner than callbacks
