### ISSUE TITLE
depthCache out of sync

### ISSUE THREAD

**Issue by keith1024** [jaggedsoft/node-binance-api#129]
Myself and a few others have noticed an issue where the depth cache _sometimes_ goes out of sync, leaving garbage in the order book and chaos in the world.

I'm not sure if any other issues make direction mention of it, but it has been brought up in #125. I'm just creating this issue to have one that is specific to this problem.

**Comment by keith1024** [comment]
I believe I've solved this! I just need to tidy it up, and then I'll open a PR. It's late here now though, and I must go to bed, but I'll get around to it as soon as possible tomorrow.

**Comment by jaggedsoft** [comment]
Thanks for all your hard work!! I appreciate you very much
There are a lot of improvements I want to make but time is very limited for me this week
Everything you have done so far has been very high quality and well thought out. You're very good at what you do. Thanks again

**Comment by keith1024** [comment]
No problem man. It's been a pleasure to help out with a library that's made my life so much easier. And no worries, I know all about limited time and how that goes. Speak of improvements, feel free to shout if there's anything I can help with in the quest for `v0.5.0`.
