### ISSUE TITLE
Watch order updates

### ISSUE THREAD

**Issue by dubrovsky-kiril** [jaggedsoft/node-binance-api#133]
Hi. Could you please help me to understand how to track order updates and status? Or at least what to use or where to look at?

I tried to use BNC_WS.orderStatus, but it returns order status only once I request it. But what should I use if I need to track all updates continuously? I tried to find something in docs, but didn't succeed. Please help :)

**Comment by jaggedsoft** [comment]
Right now it's a pain, you'd have to keep track of all orderids and periodically check them
For this reason I just place market orders

I am working on a solution to allow you to subscribe to any order updates when you place an order
seems that would make things much easier

**Comment by dubrovsky-kiril** [comment]
Thank you for your fast response! Would be reaally nice and convenient to have this functionality built-in! :)

I am also using only market orders. So you keep track of your placed order status by checking if its **id** exist in active orders ids? What method do you use for fetching all orders ids then?

Another way to solve this might be to call of BNC_WS.orderStatus with some interval. Or it would be overkill? How do you think?

**Comment by andresbelt** [comment]
hi,

right now im working on this, what i'm doing is get the all orders with openOrders() and create a array of this and after verify status by each with orderStatus() this i do each 1m, but i not know which is the best form for build this, i'm trying with ws

How did you do it?

**Comment by jaggedsoft** [comment]
I'm not doing this presently, but still thinking of the best way to accomplish it for the next iteration of the software

I think the library itself can be made to manage a list of all recent orders, and if you subscribe to order updates when placing an order, it could trigger updates as it sees them

**Comment by andresilvasantos** [comment]
Isn't the example in the [advanced examples](https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#connect-to-all-websockets-at-once-thanks-keith1024) what you're looking for? I track just fine all order updates that way.

```
// The only time the user data (account balances) and order execution websockets will fire, is if you create or cancel an order, or an order gets filled or partially filled
function balance_update(data) {
	...
}
function execution_update(data) {
	let { x:executionType, s:symbol, p:price, q:quantity, S:side, o:orderType, i:orderId, X:orderStatus } = data;
	if ( executionType == "NEW" ) {
		if ( orderStatus == "REJECTED" ) {
			console.log("Order Failed! Reason: "+data.r);
		}
		console.log(symbol+" "+side+" "+orderType+" ORDER #"+orderId+" ("+orderStatus+")");
		console.log("..price: "+price+", quantity: "+quantity);
		return;
	}
	//NEW, CANCELED, REPLACED, REJECTED, TRADE, EXPIRED
	console.log(symbol+"\t"+side+" "+executionType+" "+orderType+" ORDER #"+orderId);
}
binance.websockets.userData(balance_update, execution_update);
```

**Comment by fngrz** [comment]
@andresilvasantos I've only been able to get wallet updates from this, not trade updates. Have you been able to get the execution update to give you trade data?

**Comment by andresilvasantos** [comment]
@fngrz Yes, I don't know what you might be doing wrong to give you one but not the other. Check out my project [BitProphet](https://github.com/andresilvasantos/bitprophet) - I use userData for that purpose and it works very well.
