### ISSUE TITLE
Market order buy 100%

### ISSUE THREAD

**Issue by gibo** [jaggedsoft/node-binance-api#139]
This is an absolutely great API.

Is it possible to do a Market order, to buy as much as you have available to spend?

**Comment by jaggedsoft** [comment]
To get the quantity
divide the amount of btc you have, by the btc price of the item you're buying

for example if you have .3 btc
and you want to buy eth

the price of ETH_BTC is 0.089250
.3 / 0.089250 = 3.361344537815126

This means you can afford to buy 3.36 eth at a cost of .2999 btc

You can punch in the numbers on the website to verify how it works
![unnamed](https://user-images.githubusercontent.com/4283360/36356918-455ed8be-14ad-11e8-9f0d-f5aa8a354e42.png)

It's not a bad idea to make an option to do this for you automatically, though. Will consider it in the future. Thanks!

**Comment by dalaverd** [comment]
I would like that too. Because it's hard to know what's the max available order with leverage.
