### ISSUE TITLE
Better way to get the current price / volume for each coin?

### ISSUE THREAD

**Issue by napindc** [jaggedsoft/node-binance-api#14]
I want to be able to get the current price & volume for each coin, once per minute. I'm using the `binance.prices(function(ticker) {` to get back the current prices. I can then feed that into something like `binance.websockets.candlesticks(['IOTABTC'], "1d", function(candlesticks) {`, and I'll get back all of the information I need (note that I pass all of the BTC/ETH pairs into that websocket). I then `terminate` the websocket once I have the information.

It would be better if there was a non-websocket API to get the price/volume, but I don't see it. Because right now, it takes forever to wait for the websocket to get back all the information for each coin , when you pass in 100+ coins into it.

**Comment by jaggedsoft** [comment]
Yes. Great suggestion. I have already passed this along to the CTO of Binance.
We would like 24 hour price statistics for all symbols, so we can easily get daily volume, etc.

**Comment by jaggedsoft** [comment]
I also responded here: https://github.com/binance-exchange/node-binance-api/issues/7

**Comment by jaggedsoft** [comment]
Now available on latest version

#### Get 24h Price Change Statistics via WebSocket
```js
// For all symbols:
binance.websockets.prevDay(false, function(response) {
  console.log(response);
});

// For a specific symbol:
binance.websockets.prevDay('BNBBTC', function(response) {
  console.log(response);
});
```

<details>
 <summary>View Response</summary>

```
{ eventType: '24hrTicker',
  eventTime: 1512629577435,
  symbol: 'BNBBTC',
  priceChange: '-0.00002671',
  percentChange: '-12.844',
  averagePrice: '0.00019282',
  prevClose: '0.00020796',
  close: '0.00018125',
  closeQty: '55.00000000',
  bestBid: '0.00018038',
  bestBidQty: '580.00000000',
  bestAsk: '0.00018125',
  bestAskQty: '144.00000000',
  open: '0.00020796',
  high: '0.00021300',
  low: '0.00017555',
  volume: '3731915.00000000',
  quoteVolume: '719.59011818',
  openTime: 1512543177433,
  closeTime: 1512629577433,
  firstTradeId: 2248079,
  lastTradeId: 2284725,
  numTrades: 36647 }
```
</details>

**Comment by jaggedsoft** [comment]
https://api.binance.com/api/v1/ticker/24hr
Now returning all symbols

```js
binance.prevDay(false, function(response) {
	console.log(response);
});```
