### ISSUE TITLE
cannot print error message

### ISSUE THREAD

**Issue by denigada** [jaggedsoft/node-binance-api#142]
`binance.buy(pair, order.amount, order.bidAsk, { type: 'LIMIT' }, (error, response) => {
if (error) {
              console.log('ERROR PLACING ORDER: ' + error.msg);`

It is printing undefined. I also tried error.body.msg but it doesn't work. Does anyone know how to fix this?

**Comment by keith1024** [comment]
What do you see if you just print `console.log(error)`?

**Comment by denigada** [comment]
A pretty big json file with body : {code:__,msg:__} at the end

**Comment by keith1024** [comment]
Is there a `statusCode`?

**Comment by denigada** [comment]
this is the output:
`IncomingMessage {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { end: [ [Function: responseOnEnd], [Function] ],
     close: [ [Function], [Function] ],
     data: [Function],
     error: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  socket: 
   TLSSocket {
     _tlsOptions: 
      { pipe: false,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: <Buffer 30 82 06 95 02 01 01 02 02 03 03 04 02 c0 2f 04 20 d5 1c a7 13 00 29 0f bd 39 0f 9a a5 ce e2 e3 6d 21 5c b9 96 e4 01 7d 6f 77 d8 79 5c 25 b3 b5 09 04 ... >,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Array],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        timeout: [Object] },
     _eventsCount: 10,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.binance.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _bytesDispatched: 448,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96 HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\nContent-type: application/x-www-form-urlencoded\r\nX-MBX-APIKEY: fa99e46ddd1e4365ac16d48459db80fa\r\nhost: api.binance.com\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     _consuming: true,
     _idleTimeout: -1,
     _idleNext: null,
     _idlePrev: null,
     _idleStart: 22004,
     _destroyed: false,
     [Symbol(asyncId)]: 2021,
     [Symbol(bytesRead)]: 310,
     [Symbol(asyncId)]: 2067,
     [Symbol(triggerAsyncId)]: 2029 },
  connection: 
   TLSSocket {
     _tlsOptions: 
      { pipe: false,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: <Buffer 30 82 06 95 02 01 01 02 02 03 03 04 02 c0 2f 04 20 d5 1c a7 13 00 29 0f bd 39 0f 9a a5 ce e2 e3 6d 21 5c b9 96 e4 01 7d 6f 77 d8 79 5c 25 b3 b5 09 04 ... >,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Array],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        timeout: [Object] },
     _eventsCount: 10,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.binance.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _bytesDispatched: 448,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96 HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\nContent-type: application/x-www-form-urlencoded\r\nX-MBX-APIKEY: fa99e46ddd1e4365ac16d48459db80fa\r\nhost: api.binance.com\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     _consuming: true,
     _idleTimeout: -1,
     _idleNext: null,
     _idlePrev: null,
     _idleStart: 22004,
     _destroyed: false,
     [Symbol(asyncId)]: 2021,
     [Symbol(bytesRead)]: 310,
     [Symbol(asyncId)]: 2067,
     [Symbol(triggerAsyncId)]: 2029 },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: true,
  headers: 
   { date: 'Mon, 19 Feb 2018 22:40:58 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     connection: 'close',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     'x-frame-options': 'SAMEORIGIN' },
  rawHeaders: 
   [ 'Date',
     'Mon, 19 Feb 2018 22:40:58 GMT',
     'Content-Type',
     'application/json',
     'Transfer-Encoding',
     'chunked',
     'Connection',
     'close',
     'Server',
     'nginx',
     'Strict-Transport-Security',
     'max-age=31536000; includeSubdomains',
     'X-Frame-Options',
     'SAMEORIGIN' ],
  trailers: {},
  rawTrailers: [],
  upgrade: false,
  url: '',
  method: null,
  statusCode: 401,
  statusMessage: 'Unauthorized',
  client: 
   TLSSocket {
     _tlsOptions: 
      { pipe: false,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: <Buffer 30 82 06 95 02 01 01 02 02 03 03 04 02 c0 2f 04 20 d5 1c a7 13 00 29 0f bd 39 0f 9a a5 ce e2 e3 6d 21 5c b9 96 e4 01 7d 6f 77 d8 79 5c 25 b3 b5 09 04 ... >,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Array],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        timeout: [Object] },
     _eventsCount: 10,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.binance.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _bytesDispatched: 448,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96 HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\nContent-type: application/x-www-form-urlencoded\r\nX-MBX-APIKEY: fa99e46ddd1e4365ac16d48459db80fa\r\nhost: api.binance.com\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     _consuming: true,
     _idleTimeout: -1,
     _idleNext: null,
     _idlePrev: null,
     _idleStart: 22004,
     _destroyed: false,
     [Symbol(asyncId)]: 2021,
     [Symbol(bytesRead)]: 310,
     [Symbol(asyncId)]: 2067,
     [Symbol(triggerAsyncId)]: 2029 },
  _consuming: true,
  _dumped: false,
  req: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Function],
        response: [Function: bound ],
        error: [Array],
        drain: [Function],
        timeout: [Object],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.binance.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 448,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 22004,
        _destroyed: false,
        [Symbol(asyncId)]: 2021,
        [Symbol(bytesRead)]: 310,
        [Symbol(asyncId)]: 2067,
        [Symbol(triggerAsyncId)]: 2029 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.binance.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 448,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 22004,
        _destroyed: false,
        [Symbol(asyncId)]: 2021,
        [Symbol(bytesRead)]: 310,
        [Symbol(asyncId)]: 2067,
        [Symbol(triggerAsyncId)]: 2029 },
     _header: 'POST /api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96 HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\nContent-type: application/x-www-form-urlencoded\r\nX-MBX-APIKEY: fa99e46ddd1e4365ac16d48459db80fa\r\nhost: api.binance.com\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
     _ended: true,
     res: [Circular],
     aborted: undefined,
     timeoutCb: [Function: emitTimeout],
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     [Symbol(outHeadersKey)]: 
      { 'user-agent': [Array],
        'content-type': [Array],
        'x-mbx-apikey': [Array],
        host: [Array],
        'content-length': [Array] } },
  request: 
   Request {
     domain: null,
     _events: 
      { error: [Function: bound ],
        complete: [Function: bound ],
        pipe: [Function],
        data: [Function],
        end: [Function] },
     _eventsCount: 5,
     _maxListeners: undefined,
     method: 'POST',
     timeout: 60000,
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     headers: 
      { 'User-Agent': 'Mozilla/4.0 (compatible; Node Binance API)',
        'Content-type': 'application/x-www-form-urlencoded',
        'X-MBX-APIKEY': 'fa99e46ddd1e4365ac16d48459db80fa',
        'content-length': 0 },
     callback: [Function],
     readable: true,
     writable: true,
     explicitMethod: true,
     _qs: 
      Querystring {
        request: [Circular],
        lib: [Object],
        useQuerystring: undefined,
        parseOptions: {},
        stringifyOptions: {} },
     _auth: 
      Auth {
        request: [Circular],
        hasAuth: false,
        sentAuth: false,
        bearerToken: null,
        user: null,
        pass: null },
     _oauth: OAuth { request: [Circular], params: null },
     _multipart: 
      Multipart {
        request: [Circular],
        boundary: '39579478-8f72-42f0-835b-58f3595b75f0',
        chunked: false,
        body: null },
     _redirect: 
      Redirect {
        request: [Circular],
        followRedirect: true,
        followRedirects: true,
        followAllRedirects: false,
        followOriginalHttpMethod: false,
        allowRedirect: [Function],
        maxRedirects: 10,
        redirects: [],
        redirectsFollowed: 0,
        removeRefererHeader: false },
     _tunnel: 
      Tunnel {
        request: [Circular],
        proxyHeaderWhiteList: [Array],
        proxyHeaderExclusiveList: [] },
     setHeader: [Function],
     hasHeader: [Function],
     getHeader: [Function],
     removeHeader: [Function],
     localAddress: undefined,
     pool: {},
     dests: [],
     __isRequestRequest: true,
     _callback: [Function],
     uri: 
      Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'api.binance.com',
        port: 443,
        hostname: 'api.binance.com',
        hash: null,
        search: '?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        query: 'symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        pathname: '/api/v3/order',
        path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        href: 'https://api.binance.com/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96' },
     proxy: null,
     tunnel: true,
     setHost: true,
     originalCookieHeader: undefined,
     _disableCookies: true,
     _jar: undefined,
     port: 443,
     host: 'api.binance.com',
     path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
     httpModule: 
      { Server: [Object],
        createServer: [Function: createServer],
        globalAgent: [Object],
        Agent: [Object],
        request: [Function: request],
        get: [Function: get] },
     agentClass: { [Function: Agent] super_: [Object] },
     _started: true,
     href: 'https://api.binance.com/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96 HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\nContent-type: application/x-www-form-urlencoded\r\nX-MBX-APIKEY: fa99e46ddd1e4365ac16d48459db80fa\r\nhost: api.binance.com\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v3/order?symbol=NEOBTC&side=BUY&type=LIMIT&quantity=0.17779604&price=0.01222800&timeInForce=GTC&timestamp=1519080057769&recvWindow=60000&signature=87034a240a163a3c35c2d41075a1bab726a37c362fc9628fb7df8a26d31a3d96',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     ntick: true,
     timeoutTimer: null,
     response: [Circular],
     originalHost: 'api.binance.com',
     originalHostHeaderName: 'host',
     responseContent: [Circular],
     _destdata: true,
     _ended: true,
     _callbackCalled: true },
  toJSON: [Function: responseToJSON],
  caseless: 
   Caseless {
     dict: 
      { date: 'Mon, 19 Feb 2018 22:40:58 GMT',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        server: 'nginx',
        'strict-transport-security': 'max-age=31536000; includeSubdomains',
        'x-frame-options': 'SAMEORIGIN' } },
  read: [Function],
  body: '{"code":-2014,"msg":"API-key format invalid."}' } {}`
