### ISSUE TITLE
Missing depositHistory optional parameters

### ISSUE THREAD

**Issue by nicolas-martin** [jaggedsoft/node-binance-api#144]
Similar to #121 I believe some parameters are missing
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#deposit-history-user_data

https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L715-L718

**Comment by jaggedsoft** [comment]
Thanks for your report!
maybe something like this:

```js
        depositHistory: function(callback, params = {}) {
            if ( typeof asset == 'string' ) params = {asset:params}; // Support 'asset' (string) or optional parameters (object)
            signedRequest(wapi+'v3/depositHistory.html', params, callback);
        },
```
