### ISSUE TITLE
ExchangeInfo's issue

### ISSUE THREAD

**Issue by JowaDev** [jaggedsoft/node-binance-api#145]
Hello,

I'have an issue with this method : 

binance.exchangeInfo(function(response) {
	console.log(response);
});

It returns "null" ?

**Comment by keith1024** [comment]
That `null` is correct it means there wasn't an error. The signature of the callback is `(err, response)`. So your code should look like this rather.
```javascript
binance.exchangeInfo(function(err, response) {
    console.log(response);
});
```
