### ISSUE TITLE
Nested API calls

### ISSUE THREAD

**Issue by larkolab** [jaggedsoft/node-binance-api#146]
Hello,

I'm not very familiar with Node.Js, so I'm not sure how to handle the asynchronous API to perform nested calls to the binance API.

For example, I would like to get the bidPrice of a symbol inside a binance.candlesticks() function:

```
binance.candlesticks("BTCUSDT", "1h", (error, ticks, symbol) => {
	// do things
	...
	if (something) {
                let buy_price = 0;
		binance.bookTickers('BTCUSDT', (error, ticker) => {
                        buy_price = ticker.bidPrice;
                });
                console.log(buy_price);
        }
});
```

The problem with the code above is that it seems that it reaches the console.log(buy_price) before binance.bookTickers() has completed, so no value is set yet.

I guess it is a basic misunderstanding of me of node.js programming, but if you could show me how you generally solve this, it would help! :)
I've seen topics around async/await, but I guess there is another way to do that?

Thanks!

**Comment by keith1024** [comment]
Hi. Yeah, asynchronous programming can take a while to wrap your head around if you're not used it. Your code is close to getting what you wanted though.
```javascript
// Makes a web request, therefore any logic that needs its result
// must be in the callback (called when the request gets a response)
binance.candlesticks("BTCUSDT", "1h", (error, ticks, symbol) => {
    // In here we can deal with any results from `candlesticks`
    if (something) {
        let buy_price = 0;
        // This is going to make another we request, so any logic that
        // needs its result, must be in the callback.
        binance.bookTickers('BTCUSDT', (error, ticker) => {
            // Here we can use the results from `bookTickers`
            buy_price = ticker.bidPrice;
            // Your price price will be what you expect.
            console.log(buy_price);
        });
        // Code down here will run before the `bookTickers` response
        // is received. No synchronoous programming in Node.
        // You buy price is going to be 0 since this is called
        // immediately after `binance.bookTickers`.
        console.log(buy_price);
    }
});
```

**Comment by larkolab** [comment]
Hi @keith1024, yeah, I need to "unsynchronize" my head! ;)
I'm used to work with asynchronous programming with threads in C/C++, but I can still have synchronization point when I need it. With Node, I'm a little anxious not to know what happens when... :)

Thanks a lot for your answer, I'll see how far I can go !

Cheers
