### ISSUE TITLE
Cancellation of orders does not work

### ISSUE THREAD

**Issue by sashamorozov** [jaggedsoft/node-binance-api#147]
Hello, thank you for your work!

Faced a problem that when I try to cancel an order I get the following response from the API: `Invalid API-key, IP, or permissions for action.`

The API is set up for trading.
I just created new keys just in case.
I also added my IPs to Trusted IPs.
`test: true` is not set in options.
All this does not help, every time it returns the error.

The cancellation function is:
```
binance.cancel(symbol, orderId, (error, response, symb) => {
  if (error) {
    return console.error(`${symb} cancel error:`, error);
  }

  console.log(`${symb} cancel response:`, response);
});
```

`symbol` and `orderId` are correct, checked using another function to request order status.

I do not know what is not right, so I ask for help.

Thank you.

**Comment by jaggedsoft** [comment]
Hi there!
I have tested the cancel code recently and it worked. So I would assume that the problem is indeed related to API key or permissions. Perhaps the key is entered incorrectly, or something specific to your environment is causing this issue. I wish I could provide more clarity

**Comment by sashamorozov** [comment]
@jaggedsoft I checked additionally with a limit order, it also returns this error.
This is strange, because the keys are set up correctly. 
`Enable Trading` is activated in the settings.

Orders, balance and the rest works.
Only it is impossible to trade...

**Comment by jaggedsoft** [comment]
I wish I knew what was causing this, but I can't think of where to begin.
There is another library located here https://github.com/binance-exchange/binance-api-node perhaps you could see if it works?

**Comment by keith1024** [comment]
This is very strange. Try removing your restricted IP security, and testing it then? I use the cancel function extensively, and have never encountered this error.

**Comment by sashamorozov** [comment]
Okay, I deleted all API keys from binance.com and created a new one.
Now even orders are not loaded, only withdrawals and deposits.
It gives the same error `Invalid API-key, IP, or permissions for action.`.

Maybe Binance banned me? 😱

**Comment by jaggedsoft** [comment]
Not likely. The ban messages are specific, and most bans are only for a few minutes.

That's interesting that the error is only happening on things that require trading permissions

**Comment by sashamorozov** [comment]
I'm sorry, guys!!

I forgot about a function that I did not finish to store keys not in the code, but locally.
And it somehow activated old keys that were set to read-only mode.
