### ISSUE TITLE
WebSocket not terminated

### ISSUE THREAD

**Issue by amelenetwork** [jaggedsoft/node-binance-api#148]
Hello there,

Im trying to terminate connected socket 

EndPoint id is : 2131070991
**binance.websockets.terminate(list_connection[symbol][name_resolution+'_id']);**

But still pumping candlesticks ... Any body help me about it? How can I terminate socket with end point ID ? 

Thank you so much ....

Pump....
Before: 2
End Point list : 2131070991
Socket baglantisi kapatildi 2131070991
[ 'WebSocket terminated:', 2131070991 ]
[ 'WebSocket closed: 2131070991 (1006)' ]
Where was client: ETHBTC res was: h4
Do: 1
Before: undefined
Where was client: ETHBTC res was: undefined
Do: NaN
Pump....
Pump....
Pump...

Im getting End point and storing like that ...

var **endpoint_id** = binance.websockets.candlesticks([symbol], resolution, (candlesticks) => { 
        let { e:eventType, E:eventTime, s:symbol, k:ticks } = candlesticks;
        let { o:open, h:high, l:low, c:close, v:volume, n:trades, i:interval, t:startBar, q:quoteVolume, V:buyVolume, Q:quoteBuyVolume } = ticks;
        let answer = {
          s:'ok',
          c:[close,close],
          t:[Math.round(startBar/1000),Math.round(startBar/1000)],
          v:[volume,volume],
          h:[high, high],
          l:[low, low],
          o:[open, open]
        }

**Comment by jaggedsoft** [comment]
Websocket connections can now only be terminated if you opened the websocket by itself (instead of passing an array)
Probably should add some code to warn people about this if they're attempting it, might save them some time

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/36942072-594addb0-1f1f-11e8-8882-d5db90b234be.png)

1. Make sure `reconnect` is set to false
2. Make sure the ID of the endpoint is correct

To view the endpoints, use this code:
```js
setInterval(()=>{
	let endpoints = binance.websockets.subscriptions();
	for ( let endpoint in endpoints ) {
		console.log(endpoint);
	}
}, 1000);
```
The setTimeout is optional, you can run this code at any time, just providing it as-is out of my test file

**Comment by amelenetwork** [comment]
Hello there...
I set options ,
'reconnect':false 
'test':true  => this line important , when test:true , not terminated . I removed "test" option line, then terminated successfully .

Thank you so much your help.... Thank you mate !

**Comment by amelenetwork** [comment]
I said 'fixed' but no any change :( 

I conenct 2 different types . When connecting passing an array and just string symbol. 

When I trying to terminate Im getting these answers ..

**If array passing symbol, answer below :** 
[ 'WebSocket terminated:', 3205979174 ]
[ 'WebSocket closed: 3205979174 (1006)' ]

**if string passing answer below :** 

[ 'WebSocket terminated:', 'ethbtc@kline_1d' ]
[ 'WebSocket closed: ethbtc@kline_1d (1006)' ]

**What is this is code 1006 ? Is any some kind of error code ?** 

If you can do it please help me mate - really it's important for me , if I get all data , all time frame I think my system not will work healthy :( 

Thank you !

**Comment by amelenetwork** [comment]
If all 100 X 5 socket pumping 24 hours , what will happen "reconnect":true setting ? 

I tried many things - not terminating already opened socket :(  

Will can work this system, what is your opinion mate ?

**Comment by jaggedsoft** [comment]
My bot connects to every symbol with reconnect:true and works fine, something else is going wrong here

Close Code 1006 is a special code that means the connection was closed abnormally and we should check the output from an 'onerror' event. I will try to make better error messages

**Comment by amelenetwork** [comment]
mate, I have a local coin exchange project but I have no experience. I finished many things already, i have good designed screens I think and Binance data already working well (reconnect:true) on web-socket but I HAVE NO EXPERIENCE    , could you help me some special questions about coin exchange structures on skype or email ? @jaggedsoft
