### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by demipixel** [jaggedsoft/node-binance-api#15]
1) Is the default cb `console.log` because when calling binance.buy from the console without a callback it seems to log things (or is it sync which seems unlikely)

2) 
```
var quantity = 5, price = 0.00402030;
binance.buy("BNBETH", quantity, price, {}, function(response) {
	console.log("Limit Buy response", response);
	console.log("order id: " + response.orderId);
});
```

What is that {}? We jump straight from 3 to 5 parameters without specifying that.

3) 
```
// When the stop is reached, a stop order becomes a market order
let quantity = 1;
let price = 0.069;
let stopPrice = 0.068;
binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice});
```
Does it become a market order or does it sell at the price specified? If it does sell at the price specified, how can I make it a market order? Leave null for the price?

4)
Get market depth for a symbol
```
binance.depth("BNBBTC", function(depth, symbol) {
	console.log(symbol+" market depth", depth);
});
```

The response shown is actually `console.log("mark depth "+symbol, depth);`. I know, a bit picky, but consistency is important for someone who doesn't know the library.

**Comment by jaggedsoft** [comment]
Thank you for your suggestions! I will explain these better in the future.
