### ISSUE TITLE
candlesticks endpoint returning ECONNREFUSED

### ISSUE THREAD

**Issue by dseravalli** [jaggedsoft/node-binance-api#151]
My bot was running fine and all of a sudden I started getting errors from the candlesticks endpoint but it's not returning a standard Binance error that I'm used to (like when I hit a rate limit). It's returning a generic ECONNREFUSED.

I don't think this is rate limit related though. Immediately after running this test script I can hit the API with Postman and it works fine.  The rate limit is supposed to be 1200/minute and I'm nowhere near that. Also this code worked fine hours ago. Is it possible they've implemented a per second rate limit now?

Error received:
```console
{ Error: connect ECONNREFUSED 52.193.87.1:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.193.87.1',
  port: 443 }
```

Here's a test script. For me, any value of `i` over 6 will error every request over 6. So there's always six success and then all errors basically.

```javascript
const binanceApi = require('node-binance-api');

binanceApi.options({
  APIKEY: process.env.BINANCE_KEY,
  APISECRET: process.env.BINANCE_SECRET,
  useServerTime: true,
  test: true,
});

for(let i=0; i < 7; i++) {
  binanceApi.candlesticks('ETHBTC', '1m', (error, ticks) => {
    if (error) {
      console.log(error);
    } else {
      console.log('success');
    }
  });
}
```

**Comment by dseravalli** [comment]
I think this is due to concurrent requests. Binance must only allow 6 concurrent HTTP requests? Works fine If I write the code in a way that waits for previous request to finish first. Not sure why it was working before....

**Comment by jaggedsoft** [comment]
Recommend using websocket chart endpoint if possible

**Comment by dseravalli** [comment]
I am, this is just to grab all the symbol’s candlesticks once on app startup

**Comment by dseravalli** [comment]
Turns out it wasnt concurrent requests...getting it now with just one.

**Comment by jaggedsoft** [comment]
Best solution is to keep a daemon running that's listening to all the charts, and writing that data to json file so you always have it up to date.

**Comment by dseravalli** [comment]
Turns out this was a Docker networking glitch and nothing to do with this library or Binance.

**Comment by dajneem23** [comment]
> Author

i got same issue how u solve it ?
