### ISSUE TITLE
storing candlestick data?

### ISSUE THREAD

**Issue by t-westwood** [jaggedsoft/node-binance-api#153]
hi, is there a way possible that when you run the candlestick data for symbol, if you can store data on each of the last x candles?

Thanks! (sorry if this was the wrong area to post this)

**Comment by jaggedsoft** [comment]
Yeah just write it to file. Here is an example:

```js
const binance = require('node-binance-api')
binance.prevDay(false, (error, prevDay) => {
	let intervals = ['5m', '1h'];
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
		if ( symbol.substr(-3) !== 'BTC' ) continue; // BTC only
		markets.push(symbol);
	}
	console.info("Markets: ", markets);
	for ( let interval of intervals ) {
		binance.websockets.candlesticks(markets, interval, (candlestickData) => {
			let tick = binance.last(candlestickData);
			const symbol = candlestickData.s;
			const close = candlestickData[tick].c;
			console.log(symbol+" "+interval+": "+close);
			// here we are only displaying the 'close' value, but we have
			// access to every candlestick. Save to file
			fs.writeFile("charts/"+symbol+".json", JSON.stringify(candlestickData, null, 4), (err)=>{});
		});
	}
});
```

So this is performed on the 'candlestick' function but it's even easier with the 'chart' function which returns complete chart data in an easy format. I can provide an example for that if you'd like

**Comment by t-westwood** [comment]
You are awesome! thanks for such a quick reply! if you could show me an example that would be great!

**Comment by jaggedsoft** [comment]
You can pick any combination of symbols or a different timeframe:
```js
binance.websockets.chart(["BTCUSDT", "BNBBTC"], "1m", (symbol, interval, chart) => {
	let tick = binance.last(chart);
	const last = chart[tick].close;
	console.log(chart);
	// Optionally convert 'chart' object to array:
	// let ohlc = binance.ohlc(chart);
	// console.log(symbol, ohlc);
	console.log(symbol+" last price: "+last)
	// Save complete chart data to file:
	fs.writeFile("charts/"+symbol+".json", JSON.stringify(candlestickData, null, 4), (err)=>{});
});
```

**Comment by t-westwood** [comment]
thanks jaggedsoft, im well aware im being a pain! This is my last question i promise! using the code below. (im not quite ready for websockets yet haha) could i modify it to save me the last x amount of lows of a symbol to an array? If you could answer this i will be the happiest guy going (the last stage of my project haha) also if its to much trouble im happy to swing $20 your way! i so badly want to crack this last bit haha

Get Kline/candlestick data for a symbol:
You can use the optional API parameters for getting historical candlesticks, these are useful if you want to import data from earlier back in time. Optional parameters: limit (max/default 500), startTime, endTime. 

// Intervals: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M
binance.candlesticks("BNBBTC", "5m", (error, ticks, symbol) => {
  console.log("candlesticks()", ticks);
  let last_tick = ticks[ticks.length - 1];
  let [time, open, high, low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = last_tick;
  console.log(symbol+" last close: "+close);
}, {limit: 500, endTime: 1514764800000});

**Comment by jaggedsoft** [comment]
The websockets are much easier to use

What do you mean "x amount of lows"

**Comment by t-westwood** [comment]
So for example the last 10 high or low values for the symbol?

**Comment by jaggedsoft** [comment]
Ok I can provide the example in websocket too if you want

```js
const binance = require('node-binance-api')
// Intervals: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M
binance.candlesticks("BTCUSDT", "5m", (error, ticks, symbol) => {
    // Now you have the last 10 candles always
    //console.log(ticks);
    //fs.writeFile("json/candles/"+symbol+".json", JSON.stringify(ticks, null, 4), (err)=>{});
    // You can iterate through this data as well
    for ( let tick of ticks ) {
        let [time, open, high, low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = tick;
        let timestamp = new Date(time).toLocaleString();
        console.log(timestamp+" BTC: $"+close);
    }
}, {limit: 10});
```
![image](https://user-images.githubusercontent.com/4283360/37559281-7c801fea-29e0-11e8-95f0-49e4993b4ed3.png)

**Comment by t-westwood** [comment]
I cant thank you enough! Do you have paypal or a crypto account, il send you $20! Im really grateful bro.

**Comment by jaggedsoft** [comment]
Not necessary brother, keep your money. Thank you though

**Comment by t-westwood** [comment]
Thanks bro!

**Comment by t-westwood** [comment]
Hey Jaggedsoft, using the code you gave me above I've placed some additional code in there (saving the last 10 candles high, low etc) is there a way to iterate this code through all the symbols? thanks!

**Comment by jaggedsoft** [comment]
with websocket its much easier, you can run your program which will keep a realtime updated json file for every symbol (or just store it all in memory)

if you query every symbol without websocket you need to add a delay so you don't make too many requests in a short time

**Comment by t-westwood** [comment]
Ah ok,  i was planning on running the code for mybe 50 pairs and running it
every 5min. do you think that would be to many requests?

**Comment by t-westwood** [comment]
Would you be able to show me a web socket example? Can web socket be used
purely on node? Thanks

**Comment by t-westwood** [comment]
I just had a go at the web socket. When I first used it on orderbook
updates for all symbols it intimidated me a bit (So much data haha) but
it's definitely the way forward for what I need. If you could show me a way
of using a web socket that would be quality. Thanks!

**Comment by jaggedsoft** [comment]
we have the ability to process the last 10 candles every update
![image](https://user-images.githubusercontent.com/4283360/37571676-0f59d932-2abd-11e8-8dd4-ecf43330985b.png)

We can also save this data to file
This leaves us with the last 10 candles in json format like this
![image](https://user-images.githubusercontent.com/4283360/37571766-3d866a4a-2abe-11e8-8429-fcfd9b51071f.png)

### Complete Example, all symbols
```js
const fs = require('fs');
const binance = require('node-binance-api')
// get all markets, volume, daily change
binance.prevDay(false, (error, prevDay) => {
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		if ( obj.volume < 1 ) continue; // perform any filtering you want
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
		//if ( symbol.substr(-3) !== 'BTC' ) continue; // filter BTC only, etc
		markets.push(symbol);
	}
	console.info("Markets: ", markets);
	console.info("Total markets: ", markets.length);
	let interval = '5m';
	binance.websockets.chart(markets, interval, (symbol, interval, chart) => {
		//let tick = binance.last(chart); // Get last tick only
		//const last = chart[tick].close;
		//console.log(symbol+" "+interval+": "+close);
		let output = [], tick;
		// Get the last 10 candles:		
		const range = Object.keys(chart).slice(-10);
		for ( let time of range ) {
			tick = chart[time];
			tick.timestamp = Number(time);
			let timestamp = new Date(tick.timestamp).toLocaleString();
			console.log(timestamp+" "+symbol+": $"+tick.close+"\t high: $"+tick.high+"\t low: $"+tick.low);
			output.push(tick);
		}
		// Save just the last 10 entires to file:
		fs.writeFile("charts/"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{});
		// Optionally convert 'chart' object to array:
		// let ohlc = binance.ohlc(chart);
		// console.log(symbol, ohlc);

		// Save every candlestick to file (all 500 candles)
		//fs.writeFile("charts/"+symbol+".json", JSON.stringify(chart, null, 4), (err)=>{});
	});
});
```

### Simple Example, BTCUSDT Only
```js
const fs = require('fs');
const binance = require('node-binance-api')
binance.websockets.chart('BTCUSDT', '5m', (symbol, interval, chart) => {
    //let tick = binance.last(chart);
    //const last = chart[tick].close;
    //console.log(symbol+" "+interval+": "+close);
    // Get the last 10 candles:
    const range = Object.keys(chart).slice(-10);
    for ( let time of range ) {
        let tick = chart[time];
        let timestamp = new Date(Number(time)).toLocaleString();
        console.log(timestamp+" "+symbol+": $"+tick.close+"\t high: $"+tick.high+"\t low: $"+tick.low);
    }
    // Optionally convert 'chart' object to array:
    // let ohlc = binance.ohlc(chart);
    // console.log(symbol, ohlc);
    // here we are only displaying the 'close' value, but we have
    // access to every candlestick. Save to file
    fs.writeFile("charts/"+symbol+".json", JSON.stringify(chart, null, 4), (err)=>{});
});
```

**Comment by t-westwood** [comment]
Aweome! Cheers man!

**Comment by t-westwood** [comment]
fs.writeFile("charts/"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{}); 

I know im being stupid here, but I cant find the files? (I promise I will leave you alone after this haha)

**Comment by jaggedsoft** [comment]
they get written to whatever directory you're in when you run the program
what i do is i set a global path like this at the top of my program
`global.path = '/path/to/your/folder/';

then i do `fs.writeFile(global.path+"charts/"+symbol+".json"`

You might have to make the folder first before you can see the files in there
If its on linux then you might need to give it write permissions

**Comment by t-westwood** [comment]
ahh that makes sense, i just used  `fs.writeFile("test"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{});` and it popped up in my directory, thanks man

**Comment by berkinalex** [comment]
Hi, it may sound silly, but how can I use multiple time intervals? I have tried concatenating several binance.websockets.chart but it jumps error:
for (let obj of prevDay) {
