### ISSUE TITLE
Websocket reconnecting error

### ISSUE THREAD

**Issue by springjben** [jaggedsoft/node-binance-api#156]
Sometimes I get this error if I leave me server running over night:

![capture](https://user-images.githubusercontent.com/32540273/37565205-b039f63c-2a9c-11e8-8e44-fe453102d711.PNG)

Any ideas? Do I need a websockets on disconnected and then do something?

Thank you!

**Comment by jaggedsoft** [comment]
This error might be triggered when the first reconnection attempt failed. We will implement a more robust way to attempt to continue retrying in the future. For example, in 1 second, 3 seconds, 9 seconds, 60 seconds, etc

**Comment by springjben** [comment]
Is there anything I can do for the mean time? I am trying to keep my server up and running 24/7. Other than using PM2?
