### ISSUE TITLE
TypeError: data.symbol.replace is not a function

### ISSUE THREAD

**Issue by broburns** [jaggedsoft/node-binance-api#157]
I get this error when using the market orders with the symbol stored in a variable.

Here's the code:
//
  var quantity = getQuantity(current);
  binance.marketBuy(symbol, quantity);
  binance.allOrders(symbol, (error, orders, symbol) => {
      //console.log(symbol+" last order:", orders[0].price);
      boughtPrice = orders[0].price;
      boughtQty = orders[0].origQty;
      console.log('bought ' + symbol + " at: " + boughtPrice);
      binance.prices('BTCUSDT', (error, ticker) => {
          BTC = ticker.BTCUSDT;
        con.query('INSERT INTO trades_test (type, pair, pair_price, btc_price, ammount) VALUES (?,?,?,?,?)',['buy',symbol, boughtPrice, BTC, ammount]);
      });
    }, {limit:1});
//

Symbol is defined in the parent function, and passed in as an argument.

**Comment by broburns** [comment]
Update: i get the error with both the marketBuy() and allOrders(), however it works fine with candlesticks() and websockets.candlesticks().

**Comment by jaggedsoft** [comment]
Not sure what's going on here but I removed this line just in case
https://github.com/jaggedsoft/node-binance-api/commit/85b29effd184537a486e451000755ffefb1d965e

**Comment by broburns** [comment]
I deleted that line and am no longer getting the issue. Thanks for the quick reply!
