### ISSUE TITLE
LIMIT Order not working and does not display any error

### ISSUE THREAD

**Issue by bengrunfeld** [jaggedsoft/node-binance-api#158]
When I run the following code, no trade occurs. If I go into Binance and check the Trade History, it isn't there, so nothing has happened.

If I run a MARKET order instead, it works fine, so this issue is only with LIMIT orders.

Note that my success message `-->> Trade successful!` is also not displayed - neither is the error message, meaning the callback is never executed. Don't know what is displaying the output message.

```
binance.buy(symbol, quantity, price, (err, response) => {
  if (err)
    console.log('==>>> makeTrade error ', err.body)

  console.log('-->> Trade successful! ', response)
  if (response.orderId)
    resolve(response.orderId)

  resolve(false)
})
```

Console output:
```
[ 'BUY(WAVESETH,0.71,0.00873814) ', {} ]
```

**Comment by jaggedsoft** [comment]
Maybe `test` is set to true?

**Comment by bengrunfeld** [comment]
I found the error I was making. LIMIT orders that have a callback must have `{type: 'LIMIT'}`. Otherwise they don't work. 

```
binance.buy(symbol, quantity, price)
binance.buy(symbol, quantity, price, {type: 'LIMIT'}, (err, response) => {})
```

**Comment by sonthanhng** [comment]
Hello, I have the same problems. Can't place a limit order. 

The response is:
`
Limit Buy response {}
order id: undefined
`

And there is no errors.

Here is my test code. Can you guy help me? Thanks.

`binance.buy("BTCUSDT", 0.007, 6400, {type:'LIMIT'}, (error, response) => {
    if ( error ) return console.error("SELL error: ", error);
    console.log("Limit Buy response", response);
    console.log("order id: " + response.orderId);
  });`
