### ISSUE TITLE
@jaggedsoft

### ISSUE THREAD

**Issue by DarkAmber81** [jaggedsoft/node-binance-api#159]
would you be interested in a paid project? 
I'm new to Node.js, Json. 
I'm wanting to create data for external program (most likely Lumberyard, via Lua) - I am atempting to create my own trading Bot and I need access to the Apis for multiple Trading Servers (Binance, BitMex). 
In the end I want to create an interactive GUI that will Buy / Sell on triggered Events. 
I know you have the code, this project is personal, however it may be distributed in the future. 

In the end I want to Create an *.exe that will allow no techies to run and install the program for their own use. 
I'm not sure how to transfer the Information (Json) can be piped directly into another program, in any case, a looping Json files could be created to solve this problem (although not the best solution).

I also wanted to create Technical Indicators, RSI, MACD and others to plot lines and create users events.

Thank you DarkAmber

**Comment by jaggedsoft** [comment]
Hi DarkAmber, Unfortunately I am too busy to take on paid project at this time. But thank you for your consideration
