### ISSUE TITLE
Crypto Bot Community

### ISSUE THREAD

**Issue by kevflynn** [jaggedsoft/node-binance-api#160]
This will probably get deleted, as it should, but if you have interest in a private community centered around this module (and maybe a few other exchange node modules) with the goal of exchange bot development ideas, hit me up on telegram: flynner

@jaggedsoft - i've contributed some ideas to this repo in the past. Do you have interest in being a part of this community? I think it should remain small and private.

**Comment by jaggedsoft** [comment]
I'm jaggedsoft on telegram, but not on very often
This would probably be a good idea. I'm very active in discord

**Comment by kevflynn** [comment]
@jaggedsoft What's your discord tag? 
I'm 0650

**Comment by jaggedsoft** [comment]
1337 😎

**Comment by kevflynn** [comment]
i can't find you? 🤔
flynn#0650

**Comment by tiagosiebler** [comment]
Did you guys get together? Tried messaging you on telegram 😄
