### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Esisxnem** [jaggedsoft/node-binance-api#161]
Hi all,
I'm new to JS, and I'm having some troubles with the installation. I've installed NPM and I've tried to install the Binance package with the following error:

	C:\Users\Xxxx\source\repos_JS\Bin_Prices>npm install node-binance-api --save
	npm ERR! path C:\Users\Xxxx\source\repos_JS\Bin_Prices\node_modules\asn1
	npm ERR! code ENOENT
	npm ERR! errno -4058
	npm ERR! syscall rename
	npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Xxxx\source\
	repos_JS\Bin_Prices\node_modules\asn1' -> 'C:\Users\Xxxx\source\repos_JS\Bin_Pri
	ces\node_modules\.asn1.DELETE'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent

There is no asn1 file or folder inside node_modules...

Before this, I've modified the "package.json" file because seems that the file cannot have the same name of the field "name" and NPM gave a specific error (I don't remember which one)

"name": "node-binance-api"  <- Old line

"name": "node-binance-api-prova"  <- New line

I'm using Windows 7 64bit and 8.10.0 LTS

Any ideas?

**Comment by jaggedsoft** [comment]
Hmmm.. I have no idea here, sorry. This does not look related to my project at all.
The path I would take would probably be to delete the node_modules directory and reinstall what's necessary.

If you still can't get it working, I can tell you how to use the project without needing `npm`

**Comment by Esisxnem** [comment]
Thanks for replying,
I forgot to mention that I've already deleted node_modules directory and cleared the cache with no results.
Can you please tell me how to use the project without using npm?

**Comment by jaggedsoft** [comment]
Yes, go to your project directory and issue this command:
`npm install request string-hash ws`
Then copy download the node-binance-api.js file into your project directory

```js
const binance = require('./node-binance-api.js');
binance.options(global.path+"json/options.json"); // or use other options() example
```
