### ISSUE TITLE
RSI ?

### ISSUE THREAD

**Issue by t-westwood** [jaggedsoft/node-binance-api#163]
Hi dude, when using the websocket for previous candlestick data, is there a way to add the RSI for the candles aswel? 

thanks :)

**Comment by jaggedsoft** [comment]
This library is awesome: https://github.com/anandanand84/technicalindicators

**Comment by jaggedsoft** [comment]
Just pass an array of 'close' values from the candlesticks to the RSI function

**Comment by t-westwood** [comment]
Sorry mate forgot to thankyou! Great library for sure! Ive saved so much time than trying to do it all manually lol haha
