### ISSUE TITLE
Possible Binance Update messing with combined websocket streams

### ISSUE THREAD

**Issue by jaggedsoft** [jaggedsoft/node-binance-api#164]
I came across this earlier. Please let me know if you have any problems with websockets

https://github.com/binance-exchange/binance-official-api-docs/pull/27#issuecomment-376535717

**Comment by fjafferi** [comment]
just recently started getting apiRequest error: Error: ETIMEDOUT

**Comment by fabsalito** [comment]
I am getting the error "Could not connect: Timed out after 20 seconds" for calls to $api->ticker() and $api->userData() via websocket

**Comment by rdeelstra** [comment]
I got this error:
/node_modules/node-binance-api/node-binance-api.js:1739
                          if (err) throw err
                                   ^

Error: ETIMEDOUT
    at Timeout._onTimeout (/trader/node_modules/request/request.js:845:19)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
