### ISSUE TITLE
binance.buy no error or response is returned

### ISSUE THREAD

**Issue by rodrigooler** [jaggedsoft/node-binance-api#165]
I started an implementation to integrate an application with node-binance-api but I am not able to receive the response to know the orderId.

Follow the code below.

```javascript
const binance = require('node-binance-api');

binance.options({
    APIKEY: 'X',
    APISECRET: 'Y',
    useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
    test: true // If you want to use sandbox mode where orders are simulated
});

const quantity = 1, price = 0.069;
binance.buy("BNBBTC", quantity, price, { type: 'LIMIT' }, (error, response) => {
    if (error) return console.error(error);

    console.log("Limit Buy response", response);
    console.log("order id: " + response.orderId);
});
```

![image](https://user-images.githubusercontent.com/5496931/38041457-21cbfbc2-3288-11e8-9e91-db9077c18f96.png)

I would like to know the reasons for not returning the response.

**Comment by jaggedsoft** [comment]
'test' mode does not return responses, this is how binance designed it

**Comment by rodrigooler** [comment]
@jaggedsoft thanks for the reply, issue ended.
