### ISSUE TITLE
TypeError: ticks is not iterable

### ISSUE THREAD

**Issue by charlesdarkwind** [jaggedsoft/node-binance-api#166]
It looks like #162 but I'm using depthcache and all my scripts started crashing with this and I'm not sure what is I'm passing that's causing it yet, It happens after a while, can be a couple minutes or hours or running. I did not try useServerTime: true.

Thanks, I really appreciate the library!

```
.../node-binance-api/node-binance-api.js:391
        for ( let tick of ticks ) {
                          ^

TypeError: ticks is not iterable

```
Im not calling getPricesWS more than once.
```

const getPricesWS = () => {
    try {
        binance.websockets.depthCache(['ETHUSDT'], (symbol, depth) => {
            const bids = binance.sortBids(depth.bids);
            const asks = binance.sortAsks(depth.asks);
            bestAsk = parseFloat(binance.first(asks));
            bestBid = parseFloat(binance.first(bids));
        });
    } catch(err) {
        errorLogs.push(err);
    }
};

```

**Comment by keith1024** [comment]
Hi. Are you using `websockets.chart()` anywhere? If I look at the library code, I can see that `chart` is the only stream function that calls the code pointed at by your error.

**Comment by charlesdarkwind** [comment]
@keith1024  Yes! I thought it was related to depthCache

`const getChartsWS = () => binance.websockets.chart('ETHUSDT', "1m", (symbol, interval, chart) => marketData = binance.ohlc(chart));`

**Comment by charlesdarkwind** [comment]
Also I started testing 2 bots at the same time, both having this line, idk if that could be an issue.

**Comment by keith1024** [comment]
Cool. I'm guessing the `chart` request actually returned an error, so `ticks` was passed an empty `{}` object.

Just for some extra debug info. How many pairs are you getting streams for at any given time? Binance enforces a requests per minute limit. So if for example you are getting `chart` and `depthCache` for every pair Binance has available, chances are you are most likely going to exceed this limit, and requests will return with a _rate violation_ error instead. The limit is also enforced at IP address level, so multiple bots will count toward the same shared limit.

The next version of the API plans to handle errors and these rate limits a lot better internally, so you won't even have to think about it. I will add logic for handling the above mentioned `chart` request errors though.

**Comment by charlesdarkwind** [comment]
Thanks, I only have about 10 streams at all time plus this one:

`binance.websockets.userData(balance_update, execution_update);`

But im only placing like 2 orders per day in test mode.

**Comment by broburns** [comment]
I occasionally get a similar error from binance.charts(), i get "TypeError: last_tick is not iterable" and i've concluded that it stems from having an unstable internet connection. However, strangely enough i'll get the error even when the function is not running. Hope that helps.

**Comment by mathlet0x** [comment]
I also have the same error when i have an unstable internet connection. So i fixed it but i don't know if i'm doing it right so i won't make a PR before your agreement.

I implemented this method and simply check if ticks is iterable  : 

```
    const isIterable = function(obj) {
      // checks for null and undefined
      if (obj == null) {
        return false;
      }
      return typeof obj[Symbol.iterator] === 'function';
    }
```
and i added this condition line 999 : 

``` if(klineQueue[symbol][interval] !== undefined && kline !== null)```

**Comment by jaggedsoft** [comment]
@mathlet0x Thank you very much for sharing!

**Comment by charlesdarkwind** [comment]
I think this was caused by my VM having connection problems (caused by not having enough memory).
