### ISSUE TITLE
Stream to file

### ISSUE THREAD

**Issue by broburns** [jaggedsoft/node-binance-api#170]
I'm trying to save the candlestick data to a file for backtesting purposes. Basically, everytime the websocket stream sends an update, i want to stream it to a json file. Ive tried parsing the parsing the update object to JSON and then using stream.write() to send it to the file, however its just adding new objects to the file instead of adding to an array of objects. Its also saving it to one line. 

I'd like to be able to use a writeable stream to save all the candlestick data to a file, and then be able to use a readable stream to utilize the data the same way that the binance API sends it. Got any ideas?

**Comment by jaggedsoft** [comment]
Thank you for your kind words, glad to hear it. For charting there are also some built in functions that can be helpful:
ohlc, highstock, and array

this is the standard chart data as received from the websocket
![image](https://user-images.githubusercontent.com/4283360/37540459-3d28e72c-2914-11e8-8d5d-8c8807dfa5f8.png)

the ohlc function allows you to get an array of open, high, low, close values, and volume too
![image](https://user-images.githubusercontent.com/4283360/37540527-8511f2b8-2914-11e8-83b3-6d0f51d99f0b.png)

the highstock function returns data in the format for highstock charts
![image](https://user-images.githubusercontent.com/4283360/37540576-bc7db05c-2914-11e8-86f6-06028bbf1d13.png)
and the `array` function will convert a list of objects to an array. examples:
```js
const binance = require('node-binance-api')
// Get Complete Chart Data Updates via WebSocket
// Periods: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M
binance.websockets.chart("ETHBTC", "1m", function(symbol, interval, chart) {
	console.log(symbol+" "+interval+" chart update");
	// show just the last update
	let last = binance.last(chart);
	console.log(last, chart[last]);
	//console.log(chart);
	// get open, high, low, close, volume arrays for doing technical analysis
	//let highstock_data = binance.highstock(chart, true);
	//fs.writeFile("highstock/"+symbol+".json", JSON.stringify(highstock_data), function(err){});
	// Get data as OHLC
	//let ohlc = binance.ohlc(chart);
	fs.writeFile("charts/"+symbol+".json", JSON.stringify(chart, null, 4), function(err){});
	//fs.writeFile("ohlc/"+symbol+".json", JSON.stringify(ohlc, null, 1), function(err){});
});
```

I also know how to interface with the kline library that binance uses https://github.com/chxj1992/kline
![image](https://user-images.githubusercontent.com/4283360/37540611-dadb5158-2914-11e8-977e-dd82c4e978c7.png)

Another handy api endpoint I just found out about recently is the miniTicker
It streams you the last candlestick for every symbol

![image](https://user-images.githubusercontent.com/4283360/37541033-5e916ffe-2916-11e8-8335-5912613f9785.png)
```js
const binance = require('node-binance-api');
binance.websockets.miniTicker(markets => {
  console.log(markets);
});
```

**Comment by broburns** [comment]
I appreciate the response, but that's not quite what i was looking for. Rather than charting the data, i'm looking to save the data for testing my trading algorithm.  For example, fs.writeFile("charts/"+symbol+".json", JSON.stringify(chart, null, 4), function(err){}); only gives me the last 1000 candles, whereas i'm looking to store several thousands. To better explain, rather than writing the current and previous 1000 candles to a file, i want to save each new tick that the websocket sends for as long as the node program is running, so if it runs for 24 hours, then i want it to save 24hrs worth of the tick data.

This is what i currently have.
		var stream = fs.createWriteStream("charts/"+ticker+".json")

		binance.websockets.candlesticks(ticker, "1m", (candlesticks) => {
		  let { e:eventType, E:eventTime, s:symbol, k:ticks } = candlesticks;
		  let { o:open, h:high, l:low, c:close, v:volume, i:interval, x:isFinal} = ticks;
		 // console.log(symbol+" "+interval+" candlestick update");
		  var update = JSON.stringify({
		  	time: eventTime,
		  	open: open,
		  	close: close,
		  	high: high,
		  	low: low,
		  	volume: volume
			 });
		stream.write(update)
		});

and this is how it prints to the file:
{"time":1522474590988,"open":"0.05787600","close":"0.05789600","high":"0.05794200","low":"0.05782900","volume":"60.07400000"}{"time":1522474903047,"open":"0.05787700","close":"0.05786500","high":"0.05789800","low":"0.05779300","volume":"88.06400000"}
And i want it to be formatted like the example you provided, so that i can loop over it like a normal array. I hope that better explains my intentions

**Comment by broburns** [comment]
I think what i'm looking for is to access the stream object and use it like this:
BinanceStream.pipe(writeStream). I'm having trouble trying to finding the stream object.

**Comment by jaggedsoft** [comment]
1. Load existing json file into memory at program start
2. Every candlestick update add to the array
3. Write the complete file

```js
let candles = JSON.parse(file.readFileSync(global.path+"json/"+symbol+".json"));
candles.push([eventTime, open, high, low, close, volume]);
fs.writeFile("json/"+symbol+".json", JSON.stringify(candles, null, 4), function(err){});
```
