### ISSUE TITLE
Servertime issue

### ISSUE THREAD

**Issue by markvdberg0** [jaggedsoft/node-binance-api#173]
I keep getting "'Timestamp for this request was 1000ms ahead of the server\'s time.'". Script was working fine for a few days... 

When I use recvWindow with different values I keep getting the error. 

trying to check how much MS my server is off:

```
request("https://api.binance.com/api/v1/time", (error, response, body)=> { 
	var result = JSON.parse(body);
	console.log(Math.round((new Date()).getTime())-result.serverTime)
});

```
get a values of 1355, but still not working. Using the option useServertime = true, does not work either.

any ideas?

**Comment by jaggedsoft** [comment]
Maybe your request is running before useServerTime is getting executed
```js
binance.useServerTime(function() {
	binance.balance((error, balances) => {
		if ( error ) return console.error(error);
		console.log("balances()", balances);
		console.log("BNB balance: ", balances.BNB.available);
	});
});
```

This way accepts a callback to run after the sync is complete
