### ISSUE TITLE
Parameter on depth call should be limit and not depth

### ISSUE THREAD

**Issue by hunterbmartin** [jaggedsoft/node-binance-api#18]
https://github.com/jaggedsoft/node-binance-api/blob/dd83ac26d62730173f3ce9107b18164a64f3c114/node-binance-api.js#L432

Currently this produces an error
```
{
    code: -1104,
    msg: 'Not all sent parameters were read; read \'1\' parameter(s) but was sent \'2\'.' 
}
```

A change from `depth` to `limit` will fix this error

**Comment by jaggedsoft** [comment]
Thank you very much!
