### ISSUE TITLE
please add hook to project

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/node-binance-api#181]
```
https://api.codacy.com/events/github/d8b5b5af667d4f0ebe58b78a63178170
```

Please follow manual steps for github integration below

![image](https://user-images.githubusercontent.com/15192260/38562127-bd9a80c0-3cd1-11e8-80af-4424bebeb4a9.png)

**Comment by jaggedsoft** [comment]
# 👍 👍 👍
