### ISSUE TITLE
Test: websockets depth/prevday

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/node-binance-api#184]
I have an issue with web sockets, was wondering if you could have a peek?
ill dig into it later more, but thought you might be able to spot the problem quicker

Commented out both tests towards the end of the file
https://github.com/jaggedsoft/node-binance-api/blob/master/test.js

**Prevday test:**
particularity stubborn socket.. finding difficult to terminate

**depth test:**
complains that filter is not available on that messageQueue object
context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);

**Comment by jaggedsoft** [comment]
Yes I think I see the problem
`binance.websockets.prevDay( false, (a_error, a_response) => {`

Websockets do not pass an error parameter, if they do it was probably by mistake

Should be:
`binance.websockets.prevDay( false, (a_response) => {`

**Comment by dmzoneill** [comment]
cheers dude,  the callback for prevday seems to get called in very quick succession. must look into it.

Pretty sure there is a hard error in the depthCache.  will look into it tomorrow maybe

**Comment by jaggedsoft** [comment]
Thanks very much, let me know if you need help with anything related to the depth cache
I'm going to be busy for the next few weeks as I'm planning a move to Malta, after I will be much more available & can get more involved

**Comment by dmzoneill** [comment]
🤣 if there are any jobs in binance let me know 😎

Enjoy

**Comment by dmzoneill** [comment]
found issue,
eslint removed 4 lines of code..
