### ISSUE TITLE
how use proxy in request

### ISSUE THREAD

**Issue by ruanlp** [jaggedsoft/node-binance-api#188]
how use proxy in request

**Comment by dmzoneill** [comment]
Usage: https://github.com/jaggedsoft/node-binance-api/blob/master/README.md#proxy-support

Commit: https://github.com/jaggedsoft/node-binance-api/commit/f7c690d88e247bcdc82c7ba83d3fd98d6c885d95


![image](https://user-images.githubusercontent.com/15192260/38939512-f7fbee6c-431f-11e8-96b6-da85bc1955c6.png)

**Comment by K073** [comment]
can I use proxy with authentication via binance.options () instead of taking it from the env variable
