### ISSUE TITLE
Issue when getting restful depth (order book)

### ISSUE THREAD

**Issue by amlwwalker** [jaggedsoft/node-binance-api#19]
Hi, Running the example works fine for everything except:

```
binance.depth("SNMBTC", function(json) {
 console.log("market depth",json);
});
```
which throws:

```
/[PROJECT]/node_modules/node-binance-api/node-binance-api.js:265
		for ( obj of data.bids ) {
		                 ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

any idea why?

Thanks

**Comment by jaggedsoft** [comment]
I believe this issue was fixed in the latest update (you can update with `npm update` in the project directory)
I tested the above code you posted and it seems to be working
If you still have troubles please just comment here again and I will take care of it

**Comment by amlwwalker** [comment]
Yep, that fixed it, thanks!
