### ISSUE TITLE
Timestamp 1000ms error with useServerTime = true for long-running script

### ISSUE THREAD

**Issue by TomKrcmar** [jaggedsoft/node-binance-api#193]
**Title**
- bug: useServerTime not working as expected

**Short Description:**
- Timestamp 1000ms after server time with useServerTime = true after running script for 3 days.
  
**Platform:**
- windows

**node version:**
- 9.11

**Long descrption**
- Timestamp 1000ms after server time with useServerTime = true after running script for 3 days - is it possible running for a long time slowly desynchronizes over time?
- Error occurred on a signed order request to start a new order after one order had just filled - is it related to doing back-to-back requests, or because I did a request immediately after receiving the ws.executionUpdate packet?

**code**
```
binance.options({
	APIKEY: '...',
	APISECRET: '...',
	useServerTime: true,
	test: false
});
//... BinanceBroker.js class
	openOrder: function(order) {
		var that = this;
		//... Prepare and track order, do quantity and price filters
		var options = {
				type: 'LIMIT',
				newOrderRespType: 'ACK',
				newClientOrderId: order.clientId
			};
		//... func will equal binance.buy or binance.sell, or throw.
		return new Promise((resolve, reject) => {
			func(order.pair, amount, price, options, (error, response) => {
				if (error) {
					var body = JSON.parse(error.body);
					console.error('[Binance] ['+order.pair+'] ' + body.msg);
					throw error;
				}
				order.id = response.orderId;
				resolve(order);
			});
		});
	},
```

**result**
```
Timestamp 1000ms past server time error.
```

thank you
- No, thank YOU!

**Comment by jaggedsoft** [comment]
I think the real solution here is to sync your server time or set your system to auto-sync the time once or twice per day

Here is one easy solution I can think of
```js
binance.options({
	APIKEY: '...',
	APISECRET: '...',
	useServerTime: true
});

setInterval(function() {
	binance.useServerTime();
}, 8 * 60 * 60 * 1000); // Call this function every 8 hours
```

**Comment by TomKrcmar** [comment]
It's been 5 days now and I haven't gotten the error, so this does seem to be the best workaround to mitigate the issue.

Further protections on my side like gracefully handling this error and repeating my request, on the off-chance it still happens, also has me sleeping sounder at night.

Thanks to jaggedsoft and best of luck.

**Comment by jaggedsoft** [comment]
Glad to hear it. Let me know if you run in to anything else

**Comment by rogerioaguas** [comment]
Thanks @jaggedsoft u solve my problem too!
