### ISSUE TITLE
Question: cancelling a partial filled order

### ISSUE THREAD

**Issue by matteoantoci** [jaggedsoft/node-binance-api#194]
I don't know if this is the right place to ask, in case it's not just close the ticket.

What I'm trying to understand is what happens when I cancel a partially filled order. 
Let me explain: I know that a part of the order is bought and another part is cancelled but I'm wondering if the order status will still be `PARTIALLY_FILLED` or it becomes `CANCELED` and how to handle that case.

Thanks!

**Comment by jaggedsoft** [comment]
I'm not totally sure on the order status, I'm going to assume `PARTIALLY_FILLED` because Canceled should only be if nothing was filled.
Not sure what you mean on handling that case. Can always query the order afterwards to see the status. It'd be nice if we had a way to subscribe to updates on specific orders however, that's something I'm looking to integrate

**Comment by matteoantoci** [comment]
Thanks for the prompt reply. Let's say I open a ws stream on order update data, at time 0 I receive the information that order is partially filled, then after some amount of time I decide to cancel it. My question on how to handle the case it's about distinguishing orders that got filled in some way and than got cancelled and orders that got cancelled without filling at all. 
I suppose I have to compare original quantity and executed quantity.

Anyway, I think the easiest way to subscribe to specific order is to use observable objects (MobX, RxJS...), though the final application must know how to handle them.

**Comment by jaggedsoft** [comment]
Using RxJS is a great idea for this application

**Comment by matteoantoci** [comment]
To keep things even simpler you could achieve the same result using an event emitter, you just have to emit events based on the `newClientOrderId` found in the `executionReport` payload.
