### ISSUE TITLE
Possibly To Place Two (Or More) Stop-Losses That Cancel Each Other?

### ISSUE THREAD

**Issue by JimTheMan** [jaggedsoft/node-binance-api#195]
- feature: please add

**Short Description:**
I want to be able to run some code in a serverless lambda function that will buy a coin and then put in a stop-loss order if it moves either up 20% or down 20%. Is there any way for me to automatically have the one stop loss exit the position and cancel the other one? If the coin goes up 20% and then crashes back to what would be down 20%, would it "double sell" the coin? 
  
**Platform:**
- windows
- linux
- macos

**node version:**
- 6.10

**code**
```
const util = require('util');
const binance = require('node-binance-api');
binance.options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
  test: true // If you want to use sandbox mode where orders are simulated
});

var quantity = 1;
binance.marketBuy("BNBBTC", quantity, (error, response) => {
  console.log("Limit Buy response", response);
  console.log("order id: " + response.orderId);

  let type = "STOP_LOSS";
  let quantity = 1;
  let price = 0.03;
  let uppserStopPrice = 0.068;
  let lowerStopPrice = 0.018;
  binance.sell("ETHBTC", quantity, price, {stopPrice: upperStopPrice, type: type});
  binance.sell("ETHBTC", quantity, price, {stopPrice: lowerStopPrice, type: type});
});

util.inspect( binance );
```

thank you!

**Comment by jaggedsoft** [comment]
Instead of setting the stop losses server side, you can code this behavior in client side. Just remember your entry price and if it hits your target in either direction you can sell a percentage

**Comment by JimTheMan** [comment]
@jaggedsoft not sure what you mean. I'm trying to make a trading bit where there is no client side.

**Comment by fngrz** [comment]
@JimTheMan well, first confirm if a STOP-LOSS order reserves your coins "on order".

If it does, then you can't place two orders on the same amount of coin i.e. if you place a stop-loss order on 1BTC, you have that 1BTC put "on order" or reserved, and you shouldn't be able to place another order on the same 1 BTC without cancelling the first order.

This is how I remember it operating in the web interface, and in that case, your question is moot.

**Comment by fngrz** [comment]
Actually @JimTheMan, I'm pretty sure you can't do that - make two orders on the same coin.

**Comment by jaggedsoft** [comment]
Yeah I think you're right. Placing an order will lock it. This is simple math though if you just record your entry price then you can determine when to buy/sell with the bot
