### ISSUE TITLE
How to combine websockets requests

### ISSUE THREAD

**Issue by fngrz** [jaggedsoft/node-binance-api#196]
**Can we combine websockets requests?**
- question: how can we combine websockets requests?

**Short Description:**
- would like to combine two (or more) requests e.g. order book + ticker

**Comment by jaggedsoft** [comment]
```js
binance.websockets.subscribeCombined(['bnbbtc@ticker', 'bnbbtc@depth20'], (data) => {
    console.log(data);
});
```

Read the docs here:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by fngrz** [comment]
@jaggedsoft thanks Jon!

**Comment by jaggedsoft** [comment]
No problem, I realize this isn't as easy as it should be, i.e, it doesn't tell the callback what stream the data is from. So maybe we can improve it a bit, or turn it into a nice rxjs Observable event

**Comment by fngrz** [comment]
@jaggedsoft Not a terrible problem. Used an if statement to figure out which stream came from where but I'm sure there's a neater way to do this. Thanks again!

```
binance.websockets.subscribeCombined(['eoseth@ticker', 'eoseth@depth'], (data) => {
  if (data.e === '24hrTicker') {
    console.log(data.s + ',' + data.e + ',' + data.E + ',' + data.c)
  } else {
    console.log(data.s + ',' + data.E + ',bids,' + data.b)
    console.log(data.s + ',' + data.E + ',asks,' + data.a)
  }
})
```

**Comment by seyitaylor** [comment]
@jaggedsoft seems partial depths (e.g 'eoseth@depth20') lack information on symbol so if you combine multiple pairs in one request, you have no idea who's yielding what

**Comment by aryeharmon** [comment]
this does not work anymore
wss://stream.binance.com:9443/stream?streams=bnbbtc@ticker/bnbbtc@depth20

**Comment by jaggedsoft** [comment]
@aryeharmon correct the new format is
`/stream?streams=<streamName1>/<streamName2>/<streamName3>`
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

which should be how it's handled in any version within the last month or two
I'm moving next week, not gonna have much time for programming for the next two weeks or so
