### ISSUE TITLE
binance.sell embedded in binance.marketBuy does not work

### ISSUE THREAD

**Issue by diominandrew** [jaggedsoft/node-binance-api#197]
- bug: binance.sell embedded in binance.marketBuy does not work

**Short Description:**
- binance.sell embedded in binance.marketBuy does not work
  
**Platform:**
- windows 10

**node version:**
- 9.4.0

**Long descrption**
Sorry for my clumsy English. I would like to thank you for the incredible work and help. I encountered such a problem. I have performed this code many times and with different pairs, but it does not work. If I execute binance.sell separately, then everything works fine. I need to post a pending order immediately after a successful purchase. I am hope for your help.

**code**
```
let quantity = 1;

const flags = { type: 'MARKET', newOrderRespType: 'FULL' };
binance.marketBuy('BNBBTC', quantity, flags, function (error, response) {
    if (error) return console.error(error);

    console.log("Market Buy response", response);
    console.log("order id: " + response.orderId);
    console.log("First price: " + response.fills[0].price);

    let price = (parseFloat(response.fills[0].price) + (parseFloat(response.fills[0].price) * 0.2 / 100)).toFixed(8);

    binance.sell('BNBBTC', quantity, price, { type: 'LIMIT' }, (error, response) => {
        console.log("Limit Buy response", response);
        console.log("order id: " + response.orderId);
    });

})

```

**result**
```
Market Buy response { symbol: 'BNBBTC',
  orderId: 42382622,
  clientOrderId: 'p8h3lh5jDWqXkZQW1rHSXL',
  transactTime: 1524591748713,
  price: '0.00000000',
  origQty: '1.00000000',
  executedQty: '1.00000000',
  status: 'FILLED',
  timeInForce: 'GTC',
  type: 'MARKET',
  side: 'BUY',
  fills:
   [ { price: '0.00164190',
       qty: '1.00000000',
       commission: '0.00050000',
       commissionAsset: 'BNB',
       tradeId: 16322857 } ] }
order id: 42382622
First price: 0.00164190
[ 'SELL(BNBBTC,1,0.00164518) ', {} ]

```

thank you

**Comment by jaggedsoft** [comment]
The issue here is you are changing the price before selling
You must conform to whatever exchangeInfo() shows in terms of minQty, minNotional and stepSize
![image](https://user-images.githubusercontent.com/4283360/36249988-528054dc-11f1-11e8-90b8-c6002f2639f0.png)

See here for examples:
https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#clamp-order-quantities-to-required-amounts-via-minqty-minnotional-stepsize-when-placing-orders

**Comment by jaggedsoft** [comment]
^ Scroll up to the top of that page for the exchangeInfo example
