### ISSUE TITLE
Set variable BTCBalance to the return value of the function coinBalance('BTC')

### ISSUE THREAD

**Issue by elghoul93** [jaggedsoft/node-binance-api#198]
function coinBalance (coin) {

    binance.balance(function(error, balances) {
         if ( typeof balances[coin] !== "undefined" ) {

             //works fine
             console.log(Number(balances[coin].available));
             
             //returns undefined. How can I return the correct value???
             return Number(balances[coin].available);
         }
    });
}

**BTCBalance = coinBalance("BTC");**

**Comment by dmzoneill** [comment]
Hey, 

you need to rethink the way you are coding this. The nested function is an anonymous function called when the balances function completes.. your outer function will always return undefined...

If you really need to do it in this fashion look at the test class.. there is a way to wait for the callback to complete.. but really you should just call another function from with the callback function

**Comment by elghoul93** [comment]
Thanks for quick reply. 
could you give me a hint on how would you call another function with the callback function?

I appreciate your time to help.

**Comment by jaggedsoft** [comment]
Hi @elghoul93 
There's a few different ways to do this. here is what I would suggest:

- Load your balance when the program first starts
- Subscribe to websocket balance updates so you always have up to date information
- If you don't want to use websockets you can update your balance every 30 seconds or something like that

Whenever you update your balances you can store a global object

Here is something I'm doing at startup:
```js
global.balance = {};
function balance() {
	binance.balance((error, balances) => {
		if ( error ) console.error(error);
		let btc = 0.00;
		for ( let asset in balances ) {
			let obj = balances[asset];
			obj.available = parseFloat(obj.available);
			//if ( !obj.available ) continue;
			obj.onOrder = parseFloat(obj.onOrder);
			obj.btcValue = 0;
			obj.btcTotal = 0;
			if ( asset == 'BTC' ) obj.btcValue = obj.available;
			else if ( asset == 'USDT' ) obj.btcValue = obj.available / bot.ticker.BTCUSDT;
			else obj.btcValue = obj.available * bot.ticker[asset+'BTC'];
			if ( asset == 'BTC' ) obj.btcTotal = obj.available + obj.onOrder;
			else if ( asset == 'USDT' ) obj.btcTotal = (obj.available + obj.onOrder) / bot.ticker.BTCUSDT;
			else obj.btcTotal = (obj.available + obj.onOrder) * bot.ticker[asset+'BTC'];
			if ( isNaN(obj.btcValue) ) obj.btcValue = 0;
			if ( isNaN(obj.btcTotal) ) obj.btcTotal = 0;
			btc+= obj.btcTotal;
			global.balance[asset] = obj;
		}
		fs.writeFile("json/balance.json", JSON.stringify(global.balance, null, 4), (err)=>{});
	});
}
```

If you run this on a timer, you can access the variable `global.balance.BTC` and it will always be up to date
