### ISSUE TITLE
Bug: no context is passed to handleSocketHeartbeat

### ISSUE THREAD

**Issue by dmitriz** [jaggedsoft/node-binance-api#200]
**Short Description:**
`ws.on('pong', handleSocketHeartbeat)` missing the `this` context.

I propose: get rid of `this` whatsoever by using the functional style instead.

**Long descrption**
Replace 
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L457
with
```js
ws.on('pong', handleSocketHeartbeat(ws));
```
and then get rid of `this` in 
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L416
by replacing it with pure side-effect-free curried function:
```js
const handleSocketHeartbeat = ws => () => {
    ws.isAlive = true
}
```
Similar change can be made for other handlers.

This will make unnecessary the verbose form
```js
... handleSocketOpen.bind(ws, opened_callback)
```
and will preempt this bug from happening in the future.

**Comment by jaggedsoft** [comment]
Thank you for your report
