### ISSUE TITLE
Would you accept PR to reduce code duplication?

### ISSUE THREAD

**Issue by dmitriz** [jaggedsoft/node-binance-api#201]
**Title**
- enhancement: Make code more terse by avoiding duplication

**Short Description:**
Much of the same code seems to be repeated

**Long descrption**
For instance, these two methods are almost entirely identical:

https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L82
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L140

This make it very hard to read and understand how these are different and what are they used for.

**Comment by dmzoneill** [comment]
There are a number of chunks of identical code base.. any pull request most definately welcome 😊.

In the php binance api.. reduce it to 1 function also. Possibly at the expense of increased complexity

**Comment by dmzoneill** [comment]
@jaggedsoft 
@dmitriz 

Ultimately its jaggedsoft decision as the project owner.

While we are waiting on his +1 can you kick off the pull request.
Travis will automatically build your pull request and run the tests.
Will make jaggedsoft decision easier..

Thanks

**Comment by jaggedsoft** [comment]
Yes I am open to all changes, thank you for your contributions 👍

**Comment by jaggedsoft** [comment]
I wanted the new version of the library to be done by now, but I'm moving to malta so haven't had any time to finish this

https://github.com/jaggedsoft/node-binance-api/blob/master/async.js

it was only going to have one function for requests, and everything was to be async/await or promise based

**Comment by dmitriz** [comment]
@jaggedsoft 
You are welcome!

I have some concerns about `async/await` as these are essentially sugar for promises
and promises are neither as primitive nor powerful as callbacks,
e.g. not suitable for streams, whereas with callbacks you get your stream factory 
as simple as
```js
// general purpose websocket factory
const WebSocket = require('ws')
const createWS = path => cb => 
  new WebSocket(path).on('message', cb)
```

Another concern with promises is the lack of precise specification of how they detect and unwrap other promise implementations, making them both unsafe and less performant than callbacks.

In principle, it is easy to pass between the two styles, if needed, which can be separated away from the main library. Apart from the cases like streams, where promises are of little use.

**Comment by jaggedsoft** [comment]
Well that certainly looks a lot cleaner than what I had in mind, which was rxjs observable for streams

**Comment by dmitriz** [comment]
Thanks 😄 

This way also rests on years of research on functional programming in computer science and mathematics, as well as inspired by the [pull-streams ecosystem](https://github.com/pull-stream/pull-stream).

```js
cb => new WebSocket(path).on('message', cb)
```
is a suspended computation written in the continuation-passing-style wrapped around the streaming values, parametrized by `path`, that conforms to the monadic interface, and the `createWS` factory is a Kleisli arrow, that is composable with other computations.

At the same time, it is just a plain JS function ;) Which means a lot of power, such as functional composability, multiple callbacks, two-way-communication with client, etc. I don't think `rxjs` provides such power, despite of its 200+ operators.

**Comment by dmzoneill** [comment]
Thanks... moving the close 😊
