### ISSUE TITLE
please add instance constructor

### ISSUE THREAD

**Issue by adambud** [jaggedsoft/node-binance-api#206]
I saw similar requests before and  thought that maybe version 0.5 would have instance constuctor instead of singleton. Guys, it's 3 lines of code, what's the problem?

**Comment by jaggedsoft** [comment]
It would have been merged long ago, I asked the person if it was a breaking change and received no response. I'm currently moving to malta with no time to test for myself

**Comment by bmino** [comment]
The current version of the library (0.7.4) provides an instance constructor.
PR #235 allows for both an instance constructor AND a singleton constructor which was previously provided.
