### ISSUE TITLE
There hasn't a network error handler

### ISSUE THREAD

**Issue by Xaber20110202** [jaggedsoft/node-binance-api#21]
Hi,

https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L40

If throw error, we can not handle some network situations, and some program will be crashed out

**Comment by jaggedsoft** [comment]
Thank you for the suggestion
I am aware that this is an issue. However my development time is very limited at the moment
How do you propose we fix this?

**Comment by Xaber20110202** [comment]
A piece of my mind is that we can use node callback standard, like this
```
callback(err, result)
``` 

or Promise
```
return new Promise((resolve, reject) => {
    if (err) reject(err)
    resolve(result)
})
```

But if we did that, some api might to be update.

Thanks for your reply, this issue isn't important, and if I have time, I can do some help

**Comment by jaggedsoft** [comment]
Thanks for your input
Maybe we can pass an error handler function in the options
If there is a function to catch errors it will trigger that instead of `throw`

I will think about this some more and work on it in the future

**Comment by Xaber20110202** [comment]
Thanks
