### ISSUE TITLE
npm audit

### ISSUE THREAD

**Issue by jaggedsoft** [jaggedsoft/node-binance-api#211]
Trying to get 'npm audit' to work. Not having luck yet, though.

![image](https://user-images.githubusercontent.com/4283360/39893240-007c20cc-5458-11e8-981e-80b61e14bf9d.png)

**Comment by dmzoneill** [comment]
Ya saw this.. more info here

https://mandrillapp.com/track/click/30250289/www.bithound.io?p=eyJzIjoidzZ0UkNSeFdicEVTRF9fMDFUdVA5bkRqc2RnIiwidiI6MSwicCI6IntcInVcIjozMDI1MDI4OSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5iaXRob3VuZC5pb1xcXC9naXRodWJcXFwvamFnZ2Vkc29mdFxcXC9ub2RlLWJpbmFuY2UtYXBpXFxcL21hc3RlclwiLFwiaWRcIjpcImQ5ZjBlOTQ0ZTg1YzRiOTI5ZTEzYWY3MzBlYWI0ODI1XCIsXCJ1cmxfaWRzXCI6W1wiYzgzMzRkZWZhNWJiMWI4ZWYxMWRmNzA4YzM2YjAxMGIyYmJjNzE2ZlwiXX0ifQ

**Comment by bmino** [comment]
Found 5 more issues flagged by `npm audit` which are remedied by PR #238
