### ISSUE TITLE
websocket.userData subscription doesn't receive order execution updates

### ISSUE THREAD

**Issue by rotemx** [jaggedsoft/node-binance-api#213]
**websocket.userData subscription doesn't receive order execution updates**

- bug: websocket.userData subscription doesn't receive order execution updates

**Short Description:**
websocket.userData subscription doesn't receive order execution updates
  
**Platform:**
linux

**node version:**
- 8.11

**Long descrption**
I am writing a trading bot for Binance.
After a while of running the bot and making orders, the web sockets stops receiving any execution updates. 
I suspect this maybe has to do with the order being fulfilled immediately.
I've been running the bot for the past 2 months and this has never happened before, but in recent days it happened many times.

so I suspect it's either : 
1. a problem with Binance socket API ?
2. a problem in the node library 
3. a change of Binance API, making immediate execution not broadcasted over the socket. 

Any idea ??? would appreciate any help in how to solve this.

thank you

**Comment by Dobberoonski75** [comment]
User data streams are only valid for 60 minutes after its creation as described in the official Binance API Docs -> https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md | Are you making sure to reconnect/re-validate your websocket connections?

**Comment by jaggedsoft** [comment]
Hmm. This should be working, other people have reported the same issue in the past.
