### ISSUE TITLE
issue with wifi and depth websockets

### ISSUE THREAD

**Issue by stroumbo** [jaggedsoft/node-binance-api#215]
binance desktop and mobile apps seem to stop working whenever I start using a webosocket.  web sockets also work for a little while and then have to reconnect.  Any idea on what could be causing the issue?

**Comment by jaggedsoft** [comment]
My binance web app was doing some weird flashing yesterday. This is not normal for me, and I suspect you're not the only one having problems

**Comment by stroumbo** [comment]
I only really use 2 web sockets, the price and depth web socket.  This issue only happens when I use the depth web socket.  I have been using the price web socket without any problems but as soon as I activate a depth web socket my binance apps do not work on the same wifi network.

**Comment by bmino** [comment]
Keep in mind than upon opening each depth websocket, a standard REST request is made to initialize the depths. This request queries for a depth of 500 by default which has a request weight of 5.

So even though opening, closing, and listening for data through a websocket has no weight, those REST calls will add up and you might be getting a temporary IP ban which will affect all other binance apps on that wifi network.

**Comment by jaggedsoft** [comment]
Yes. I recommend a delay of at least 150ms between Websocket connections if possible. I would like to make this an automatic, user-adjustable option
