### ISSUE TITLE
Websocket for marketdepth

### ISSUE THREAD

**Issue by t-westwood** [jaggedsoft/node-binance-api#216]
Hi JaggedSoft,

I was wondering if there was a way to websocket all currencies for the market depth and save the results to file? 

Cheers bro

**Comment by t-westwood** [comment]
the files would be individual like writing to file for candlestick data etc

**Comment by t-westwood** [comment]
something like the code below, but to filter through all symbols? (and to save them to individual files)


binance.websockets.depthCache(["BTCUSDT"], function(symbol, depth) {
	let max = 10; // Only show the 10 best bids / asks (optional)
	let bids = binance.sortBids(depth.bids, max);
	let asks = binance.sortAsks(depth.asks, max);
	console.log(binance.reverse(asks)); // print asks
	console.log("ask: ", binance.first(asks));
	console.log("bid: ", binance.first(bids));
	console.log(bids); // print bids
});

**Comment by jaggedsoft** [comment]
Yes you could do something like this

```js
binance.prevDay(false, (error, prevDay) => {
	let markets = [];
	for ( let obj of prevDay ) {
		markets.push(obj.symbol);
		console.log(obj.symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
	}
	
	// if there are problems here then some delay needs to be added before opening too many of these at once
	binance.websockets.depthCache(markets, function(symbol, depth) {
		let maximum = Infinity;
		let baseValue = "cumulative"; // for charts
		let bids = binance.sortBids(depth.bids, maximum, baseValue);
		let asks = binance.sortAsks(depth.asks, maximum, baseValue);
		console.log(symbol+" bids", bids);
		console.log(symbol+" asks", asks);
		let output = {
			bids: binance.array(bids),
			asks: binance.array(asks).reverse()
		};
		fs.writeFile("json/depth/"+symbol+".json", JSON.stringify(output, null, 4), function(err){});
	});
});
```

**Comment by t-westwood** [comment]
Cheers bro!

**Comment by jaggedsoft** [comment]
No problem, just a note: "cumulative" is for drawing depth charts.
You can remove `baseValue` entirely if that's not what you want.

https://github.com/jaggedsoft/node-binance-api/wiki/Converting-Depth-Data-to-Array

**Comment by t-westwood** [comment]
When running the code above, you was right, there was DEPTH CACHE OUT OF SYNC !!' ] errors popping up, but i changed the maximum's to 15 and no problems ;) 

And to your above reply, i was only after the 15 bid/asks either side of the current price. I will have a play around with it. 

Thanks again!
