### ISSUE TITLE
Converting depth object to array gives garbled orders

### ISSUE THREAD

**Issue by tsujp** [jaggedsoft/node-binance-api#22]
I'm using the latest version of the library.

If I am tracking a symbol, doesn't matter which, sometimes the depth cache gives orders that look like this:

0.000001, 100000

Orders that couldn't possibly be the highest bid or lowest ask.

I am using this structure to convert the depth cache object into an array

```
let bids = Object.entries(binance.sortBids(depth.bids)).sort((a, b) => a - b)
let asks = Object.entries(binance.sortAsks(depth.asks)).sort((a, b) => b - a)
```

**Comment by jaggedsoft** [comment]
If you want it in array format try this

```js
binance.depth("BNBBTC", function(depth, symbol) {
	console.log(symbol+" bids", binance.array(depth.bids));
	console.log(symbol+" asks", binance.array(depth.asks));
});
```

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/wiki/Converting-Depth-Data-to-Array

**Comment by jaggedsoft** [comment]
Also it would be nice to know if you were using the websocket depth cache (ideal) or just depth

**Comment by tsujp** [comment]
I was using the websocket depth cache
