### ISSUE TITLE
Frequent websocket disconnection

### ISSUE THREAD

**Issue by panda2048** [jaggedsoft/node-binance-api#221]
- bug: Websocket connection drop frequently due to missing pong from server
- enhancement: add option for heartbeat interval and heartbeat retry count

**Short Description:**
I am seeing frequent disconnection from websocket after making about 375 websocket connections (Combined Stream)

After some debugging and discuss with binance api support, I identified that binance server is pinging the client every 3 mins and ws libs will pokg back automatically. And api library has a 30s heartbeat to ensure quick respond to server disconnection. 

However, the pong from server is sometimes lost or delayed, so the api lib actively disconnection the socket and reconnect. But this is not necessary a socket problem 

Suggest to make enhancement to solve this
Option 1) temp solution, disable client ping and rely on server ping to keep connection alive

Option 2) add heartbeat interval and heartbeat retry count to prevent false alarm of missing heartbeat

  
**Platform:**
- linux

**Comment by jaggedsoft** [comment]
I haven't run into any websocket disconnections personally, unless I spam too many connections so they get temporarily blocked

Even without ping/pong keepalive, a websocket should stay alive for 24 hours

**Comment by panda2048** [comment]
i think my AWS free tier is not powerful enough to handle such many connections
So the 30s heartbeat and no retry logic will casue delay in getting the pong from server

The enhancement i asked for would provide more flexibility to different users
I actually have make the change and testing 
But I am not familiar with the procedure in pull request
