### ISSUE TITLE
Limit Buy/Sell response empty{}

### ISSUE THREAD

**Issue by ManuCart** [jaggedsoft/node-binance-api#222]
**Limit Buy/Sell response empty{}**
- bug: response from binance.sell(PAIR, Q, PRICE, {type:'LIMIT'}, (error, response) => {
- feature: error and response are empty but sell/buy executed 

**Platform:**
- linux

**node version:**
- v8.9.4

**Comment by jaggedsoft** [comment]
This function should always return something as long as 'test' is not set to true.
In addition to {type:'LIMIT'} you may get more information with the newOrderRespType flag set as well

`{type:'LIMIT', newOrderRespType:'FULL'}`

**Comment by ManuCart** [comment]
'test' is not set to true
Working everytime execept sometimes.
Today for about 50 buy/sell this fonction return empty response {} 2 times

**Comment by jaggedsoft** [comment]
These types of connections are probably timing out but that would usually return an error instead.
The default timeout is set to 5 seconds. That can be increased

Otherwise I am confident to say this error is on Binance's end, not in this library.
You might have to use market orders
