### ISSUE TITLE
Listing My Trade History

### ISSUE THREAD

**Issue by mkhuman34** [jaggedsoft/node-binance-api#229]
Hello there my friends !!!

I tried 3 different methods to list my trade history . They are just showing general market history. 

I need to list just my trades any market if possible. 

How can I list just my trades history ? How can I list my open orders filled status ?

There is any method for this ? What is the best solution for this ? 

Thank you for your support !!! Thank you so much .

i tried them already....

 binance.aggTrades("TRXBTC", {limit:500}, (error, response)=>{
  console.log("aggTrades", response);
});
binance.recentTrades("TRXBTC", (error, response)=>{
  console.log("recentTrades", response);
});
binance.historicalTrades("TRXBTC", (error, response)=>{
  console.log("historicalTrades", response);
});

**Comment by jaggedsoft** [comment]
> I need to list just my trades any market if possible.

Unfortunately Binance has not made this possible yet. The only easy function I can think of is to grab the balance of all coins we own, and then check the trade history on each.

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#all-orders-user_data
![image](https://user-images.githubusercontent.com/4283360/41332114-58504398-6e91-11e8-95e0-ebe66b508a85.png)

```js
binance.allOrders("TRXBTC", (error, orders, symbol) => {
    console.log(symbol+" orders:", orders);
}, {limit: 500, orderId: 100000});
```
The max 'limit' is 500
You can filter by orderId to only get orders after a certain time

The easiest way, which is what I do, is to only trade using market orders, but that's just me.


This is how I get my current balances
```js
global.ticker = {};
binance.prices((error, ticker) => {
	if ( error ) console.error(error);
	//console.log("prices()", ticker);
	for ( let symbol in ticker ) {
		global.ticker[symbol] = parseFloat(ticker[symbol]);
	}
	binance.balance((error, balances) => {
		if ( error ) console.error(error);
		let balance = {};
		for ( let asset in balances ) {
			let obj = balances[asset];
			obj.available = parseFloat(obj.available);
			if ( !obj.available ) continue; // only show items with balances
			obj.onOrder = parseFloat(obj.onOrder);
			obj.btcValue = 0;
			obj.btcTotal = 0;
			if ( asset == 'BTC' ) obj.btcValue = obj.available;
			else if ( asset == 'USDT' ) obj.btcValue = obj.available / global.ticker.BTCUSDT;
			else obj.btcValue = obj.available * global.ticker[asset+'BTC'];
			if ( asset == 'BTC' ) obj.btcTotal = obj.available + obj.onOrder;
			else if ( asset == 'USDT' ) obj.btcTotal = (obj.available + obj.onOrder) / global.ticker.BTCUSDT;
			else obj.btcTotal = (obj.available + obj.onOrder) * global.ticker[asset+'BTC'];
			if ( isNaN(obj.btcValue) ) obj.btcValue = 0;
			if ( isNaN(obj.btcTotal) ) obj.btcTotal = 0;
			balance[asset] = obj;
		}
		//fs.writeFile("balance.json", JSON.stringify(balance, null, 4), (err)=>{});
		console.log(balance);
	});
});
```
inside this loop somewhere you can check order history, up to you
