### ISSUE TITLE
marketSell and marketBuy should give better feedback

### ISSUE THREAD

**Issue by F1nnF41ler** [jaggedsoft/node-binance-api#232]
Just like the title says, marketSell and marketBuy should give a better response.

**Code**
```
const binance = require('node-binance-api');
binance.options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
  test: false // If you want to use sandbox mode where orders are simulated
});

binance.marketSell("BTCUSDT", 0.05);
```
**Result**
```
[ "SELL(BTCUSDT,0.05,0) ",{}]
```

That doesn't really tell anything about what went wrong.
It would be really useful if the response would tell you what went wrong.

At first glance you'd think that there's something wrong with the binance.options's test setting, since when that is set to "true" the result is exactly like that.
But the cause of the problem is actually the fact that I have 0.049 BTC.

Anyways, I think that it would be _very_ useful if the users would get some response that would tell about what went wrong.

**Platform:**
- windows

**node version:**
- 9.11.1

ps.
Sorry for the really bad quality of this Issue, this is the first one that I'm writing and I'm very tired...

**Comment by dmzoneill** [comment]
Welcome

If you take a look at the marketXXX signiture, it supports an optional callbavk function in the form of function (error, result).


```
marketBuy: function(symbol, quantity, flags = {type:'MARKET'}, callback = false) {

```

Hope this helps,
Enjoy

**Comment by jaggedsoft** [comment]
Hi there, using `newOrderRespType` with market orders will return much more detailed information.

[newOrderRespType example](https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#neworderresptype-example-when-placing-orders)
