### ISSUE TITLE
IP ban?

### ISSUE THREAD

**Issue by broburns** [jaggedsoft/node-binance-api#233]
Is there any way of finding out if you've been IP banned? Out of the blue last night, my bots stopped working. All sync functions such as binance.balance() and binance.candlesticks() return undefined and the websockets return a 403 error. This only happens on Ubuntu VPN, the same program works just fine on my local machine so i'm assuming my VPN has been IP banned for some reason, is there any way of finding out for certain?

**Comment by jaggedsoft** [comment]
```js
const Binance = require('node-binance-api');
const binance = new Binance().options("options.json");
// Account Status: Shows if you are banned
binance.accountStatus((error, response) => {
	console.log(response);
});

// Account returns all details for your account, including all balances.
binance.account((error, response) => {
	console.log(response);
});
```

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md
code 429 is issued when you are going over the rate limit
code 418 indicates you've been ip banned
403 means forbidden, which may happen if you've made way too many requests in too short of a time

most of the heavy lifting can be done  by websockets, which are free to use

**Comment by broburns** [comment]
Thanks, turns out i was banned, presumably from my bot going haywire and spam API requests.
