### ISSUE TITLE
bug: Error function binance.buy

### ISSUE THREAD

**Issue by marccasco** [jaggedsoft/node-binance-api#236]
**Short Description:**
- I have a problem when doing the purchase function, none of the purchasing functions work for me, and I do not understand why.
  
**Platform:**
- windows

**node version:**
- v10.5.0

**code**
--------------
var quantity = 10, price = 0.00000450;
binance.buy("DNTBTC", quantity, price, {type:'LIMIT'}, (error, response) => {
console.log("Limit Buy response", response);
console.log("order id: " + response.orderId);
 });
--------------
**result**
--------------
Limit Buy response {}
order id: undefined
--------------

Please help me, thanks!

**Comment by jaggedsoft** [comment]
To see the response add this line
`if ( error ) return console.error(error);`

```js
var quantity = 10, price = 0.00000450;
binance.buy("DNTBTC", quantity, price, {type:'LIMIT'}, (error, response) => {
if ( error ) return console.error(error);
console.log("Limit Buy response", response);
console.log("order id: " + response.orderId);
});
```

**Comment by marccasco** [comment]
Okay, this is what returns me.

Could you give me your telegram for consultations?

Thank you very much!
[IncomingMessage.txt](https://github.com/jaggedsoft/node-binance-api/files/2149902/IncomingMessage.txt)

**Comment by dmzoneill** [comment]
'{"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}' }

If you check the exchangeinfo, theres.  And array of coins. For each coin it lists the limitations on orders.  

You are trying to buy less than the fractionally allowed amount for that coin

**Comment by dmzoneill** [comment]
Its right at the very endof the message.. 
Can you please delete the file off of here,  there may be parts of your exchnage key visible in the file..

I would recommend you create a new key

**Comment by marccasco** [comment]
Okay, thank you, now I will look for it.
I deleted all the keys of the txt before uploading it, but just in case I also remove it from the comment. Thanks for the warning.

About the other mistake, does it give you any idea?
I have the balance query in an interval of 5 seconds, I get 6 times well, and the seventh gives me error.
Why could this happen?

Thank you very much for the help and sorry for the inconvenience, I am new to nodejs.

**Comment by dmzoneill** [comment]
Binance uses a third party for load balancing and DDOS prevention. It give irregular 500s on requests.   I would not program my application to be certain of a guaranteed response every time.. if you get a black response. Check for it and then. Try again... 

Beyond that we would need to see your code to determine if there is something wrong there.
