### ISSUE TITLE
Non Deterministic Unit Tests

### ISSUE THREAD

**Issue by bmino** [jaggedsoft/node-binance-api#240]
**Non Deterministic Tests**
- Bug: Unit tests will not always produce the same outcome

**Short Description:**
- Somebody can use the provided API key and secret from the test module to break all future test runs.
  
**Platform:**
- linux

**node version:**
- 9.11.2

**Long description**
The current unit tests rely on an api key which is linked to a binance account. This key/secret is public information in the source code and can be used by anyone. The following test case asserts that no trades have been made for a given symbol, but if somebody trades SYMBTC using those API credentials, all future tests will now fail.

```javascript
describe( 'trades', function() {
  it( 'Attempt get all trade history for given symbol', function( done ) {
    binance.trades( 'SNMBTC', ( error, trades, symbol ) => {
      debug( error );
      debug( trades );
      debug( symbol );
      assert( typeof ( error ) === 'object', WARN_SHOULD_BE_OBJ );
      assert( typeof ( trades ) === 'object', WARN_SHOULD_BE_OBJ );
      assert( typeof ( symbol ) === 'string', WARN_SHOULD_BE_TYPE + 'string' );
      assert( symbol === 'SNMBTC' );
      assert( error === null, WARN_SHOULD_BE_NULL );
      assert( trades !== null, WARN_SHOULD_BE_NOT_NULL );
      assert( Object.keys( trades ).length === 0 );
      done();
    } );
  } ).timeout( TIMEOUT );
} );
```

Situations like this exist in a few other unit tests as well.

**Comment by bmino** [comment]
I don't see any value in asserting against the trade history unless the purpose is to check for another test run previously that traded that commodity. Even then, I would be a lil scared that tests are dependent on each other AND on a Binance account that persists between test runs. Right? You can't clean out the trading history of that account before each test run to ensure it starts at the same point.

**Comment by jaggedsoft** [comment]
I suppose it would be impossible to make a trade if the account balance is 0

**Comment by bmino** [comment]
True and this is why it never failed previously, but couldn't a troll use those credentials to add funds and make a trade breaking all future test runs?

**Comment by dmzoneill** [comment]
hey

thanks for the feedback, the test cases are best effort, and in most cases are extremely simplistic to the point of just making sure we get back valid json from a request.

In terms of maturity, i spent maybe a few days getting the tests cases setup, they are by no means mature.   We don't have many options available to us on a zero balance account and such we can only do what we can.

If you can provide a pull request, we will be most grateful also,  moving to close as swamped with issues.

thanks again

@jaggedsoft 
@bmino
