### ISSUE TITLE
Retrurn question

### ISSUE THREAD

**Issue by guygberg** [jaggedsoft/node-binance-api#242]
**Title**
Why most of the functions return undefined? 

**Short Description:**
This may be a dumb question, but I was curious why does most of the functions do not return a meaningful value (like exchangeInfo returning the JSON of the response) ?
The solution to work with this is either by using await or nested API functions and save the callback's relevant data to global variables.
  
thank you

**Comment by jaggedsoft** [comment]
Because that is how the `request` library was designed, it's callback only

With the use of async/await we can get a complete response each time, it's a bit cleaner that way. Requires using `axios` library instead of request.js

**Comment by guygberg** [comment]
Many thanks for your quick replay.

What do you think is the best practice to abstract the data from the the callbacks using this package (prefer not to nest functions).

I assume that your previous  answer regarding the request library explains why the code below print: "{}" and then the JSON of the exchangeInfo, right?

"async function getExchangeData()
  {
    await binance.exchangeInfo( (error,data)=>{ global.exchangeInfo =  data; });
    console.log(global.exchangeInfo);
    setTimeout(() =>{ console.log(global.exchangeInfo); },4440);
  }
  
getExchangeData();"

**Comment by jaggedsoft** [comment]
Yeah this project doesn't work with async/await yet, but you can check out these experiments i started
you can include them separately for now: https://github.com/jaggedsoft/node-binance-api/blob/master/async.js
