### ISSUE TITLE
Usage Instantiating Multiple Instances as Sync

### ISSUE THREAD

**Issue by erayidil** [jaggedsoft/node-binance-api#244]
### I have a script like the one below roughly. It's working good for a few minutes. After, some variables, arrays have wrong data, is it possible to run this codes sync, if it is, how?
thank you

setInterval(function() {

binance.candlesticks("BNBBTC", "1m", function(error, ticks) {
 //some stuff
}, {limit: 50});

binance.websockets.trades(['BTCUSDT'], (trades) => {
//some stuff
// sell();
//some stuff
//buy();
});

function buy() {
	const flags = {type: 'MARKET', newOrderRespType: 'FULL'};
	binance.marketBuy("BNBBTC", buy_quantity, flags, function(error, response) {
        ........
	});
}
function sell() {
	const flags = {type: 'MARKET', newOrderRespType: 'FULL'};
	binance.marketSell("BNBBTC", sell_quantity, flags, function(error, response) {
        ........
	});
}

}, 60000);

**Comment by jaggedsoft** [comment]
Can you give an example of the wrong data? I can not reproduce

**Comment by erayidil** [comment]
binance.candlesticks makes an array for price, binance.websockets changes last index data of that array for every new price. I can see usually true new array but once in a 5 or 10 second, i see array of 1 or 2 minutes before.  thank you...

**Comment by erayidil** [comment]
I'm sorry, problem was in my code.
Thank you very much.
