### ISSUE TITLE
How can I use library without API keys? I need only public methods

### ISSUE THREAD

**Issue by dormadekhin-denis** [jaggedsoft/node-binance-api#246]
**Title**
- question

**Short Description:**
-I want to use only the public REST API and Websocket methods
  
**Platform:**
- ubuntu 16.04

**node version:**
- 10.6.1

thank you

**Comment by jaggedsoft** [comment]
I think you can just pass blank fields to the constructor

```js
const Binance = require('node-binance-api');
const binance = new Binance().options({
  APIKEY: '',
  APISECRET: '',
  useServerTime: true
});
```

**Comment by bmino** [comment]
If you are only performing non-api requests (such as the public REST api) you can omit the `APIKEY` and `APISECRET` parameters from the `options()` method.

Keep in mind that the `useServerTime` parameter requires an api request to be made so you will have to remove that. Something like the following will work:

```javascript
const Binance = require('node-binance-api');
const binance = new Binance().options({
    // options here
});
```

or without using the options method at all

```javascript
const Binance = require('node-binance-api');
const binance = new Binance();
```
