### ISSUE TITLE
Terminate websocket doesn't work.

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [jaggedsoft/node-binance-api#247]
Terminate websocket (trades) doesn't work.
  
**Platform:**
- macos 10.13.5

**node version:**
- v8.9.2

**code**
```
binance.options({
    'APIKEY': options.binance_public_key,
    'APISECRET': options.binance_private_key,
    'reconnect': false
});

binance.websockets.trades(['BCDBTC'], (trades) => {
            let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
            console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
            console.log('eventTime ' + moment(eventTime).format());
            console.log('price ' + price);
            console.log('quantity ' + quantity);
            console.log('maker ' + maker);
            console.log('----- ------ -----');
        });

binance.websockets.terminate('bcdbtc@trade') // bcdbtc@trades - also doesn't work
```

**result**
Websocket not terminated. I'm still getting info from open socket connection.

thank you

**Comment by jaggedsoft** [comment]
`binance.websockets.trades(['BCDBTC']`
Change this to
`binance.websockets.trades('BCDBTC'`
and try again

If you pass an array, it will use a Combined websocket stream, which can not be terminated. However if you connect individually it should be possible to terminate the connection

**Comment by georgeMuraveiAlkh** [comment]
@jaggedsoft ok thank you. It's works that way.
