### ISSUE TITLE
Shouldn't binance.depth return data as array?

### ISSUE THREAD

**Issue by bengrunfeld** [jaggedsoft/node-binance-api#249]
**Title**
- enhancement: `binance.depth` should return data as array

**Short Description:**
- Currently, `binance.depth` returns an object, but it seems more like array data. Not to be finicky or anything. Just asking.

Rather, depth data should be returned as an array. E.g.

```
{
  bids: [
    [0.00022997, 49.00000000],
    [0.00022867, 11.00000000],
    [0.00022865, 1149.00000000],
    [0.00022810, 20.00000000]
], asks: [
]
```
  
**Platform:**
- MacOS

**node version:**
- v10.0.0

**code**
```
binance.depth("BNBBTC", (error, depth, symbol) => {
  console.log(symbol+" market depth", depth);
});
```

Thank you, supercoder!! ;)

**Comment by jaggedsoft** [comment]
I had found that managing the depth cache as an object was way more efficient in terms of speed. However if you prefer the array format you can still request it as such:

```js
binance.websockets.depthCache(['BTCUSDT'], (symbol, depth) => {
	const limit = 3;
	let bids = binance.sortBids(depth.bids, limit);
	let asks = binance.sortAsks(depth.asks, limit);

	//console.log("best bid: "+binance.first(bids));
	//console.log("best ask: "+binance.first(asks));
	let output = {bids:binance.array(bids), asks:binance.array(asks)};
	console.log(symbol, output);

	// save information to json file
	//file.writeFile("json/depth/"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{});
});
```
