### ISSUE TITLE
How to reconnect for listening websocket

### ISSUE THREAD

**Issue by denisenkoaj** [jaggedsoft/node-binance-api#25]
Hello! How i can create reconnection every time when connection falls?
 Specifically for websockets.trades
It's really a big problem

**Comment by denisenkoaj** [comment]
connection closes after 24h

**Comment by jaggedsoft** [comment]
I have added websocket reconnection to this function
This is available in release `v0.3.0` if you navigate to your project directory and issue an `npm update`
