### ISSUE TITLE
binance.balance not working

### ISSUE THREAD

**Issue by fragender** [jaggedsoft/node-binance-api#250]
Today I got this reaction on the console after running 
"getting list of current balances" with

binance.balance((error, balances) => {
  console.log("balances()", balances);
  console.log("ETH balance: ", balances.ETH.available);
});

reaction:
console.log("ETH balance: ", balances.ETH.available);
                       
TypeError: Cannot read property 'available' of undefined
    at binance.balance

It had always worked the months before.

**Comment by jaggedsoft** [comment]
I can confirm that I am also getting an error using this function:
`{"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}`

To see if you are getting errors you must add this at the top of your function `if ( error ) return console.error(error.body);`

Unfortunately, I am getting this error even with a very high recvWindow set, so I am unsure of the solution.

The functionality of this changed when they made it so you could trade your dust for BNB
You may need to do it like this in the future, if you don't own any ETH:
`if ( typeof balances.ETH !== "undefined" ) console.log("ETH balance: ", balances.ETH.available);`

**Comment by jaggedsoft** [comment]
Yes this works for me. We are wrapping our function with useServerTime so it syncs the clock with binance immediately when your program first starts

```js
binance.useServerTime(() =>
binance.balance((error, balances) => {
  if ( error ) return console.error(error.body);
  console.log("balances()", balances);
  if ( typeof balances.ETH !== "undefined" ) console.log("ETH balance: ", balances.ETH.available);
}));
```

**Comment by fragender** [comment]
cool!!

**Comment by fragender** [comment]
uuups!!!
[ 'balanceData error', {} ]
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

**Comment by jaggedsoft** [comment]
That's progress, should be easy to fix, just go into your binance API settings and issue a new key

**Comment by fragender** [comment]
Thank you!
As soon as my project works, I would like to thank you with a donation. How can I do this, please?

**Comment by jaggedsoft** [comment]
Donations are not required but appreciated:
```
BTC 1C5gqLRs96Xq4V2ZZAR1347yUCpHie7sa
ETH 0x1d2034348c851ea29c7d03731c7968a5bcc91564
```

Thank you!!

**Comment by bvdon** [comment]
I had same problem. I fixed with this line (a little different from above).

if (typeof balances['BTC'] !== "undefined") {
btcAvailableBalance = parseFloat(balances['BTC'].available);
btcOnOrderBalance = parseFloat(balances['BTC'].onOrder);
}
else {
btcAvailableBalance = 0;
btcOnOrderBalance = 0;
}
