### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by marccasco** [jaggedsoft/node-binance-api#251]
**Short Description:**
- Hi, I'm getting this error many times, although I still use the code, I do not understand why I get this error.
  
**Platform:**
- windows

**node version:**
- 10.5.0

**result**
```
connect ETIMEDOUT 104.20.12.48:443
[ 'WebSocket error: !ticker@arr (ENOTFOUND) getaddrinfo ENOTFOUND stream.binance.com stream.binance.com:9443' ]
[ 'WebSocket closed: !ticker@arr (1006)' ]
[ 'WebSocket reconnecting: !ticker@arr...' ]
```

Thank you!

**Comment by jaggedsoft** [comment]
Hi there, I believe the fix for most people has been switching name servers
Personally, I use https://1.1.1.1

**Comment by marccasco** [comment]
And if instead of putting localhost or 127.0.0.1, I put 1.1.1.1, will it work?
I do not understand the difference. Thank you!

**Comment by dmzoneill** [comment]
when your computer goes to make a request for "stream.binance.com", here are the steps it does.

calls getAddressByhostName( stream.binance.com )
if your are on linux, the /etc/nsswtich.conf will determine the lookup order (similar to windows).
   typical lookup order is 
 - hosts:  "files, dns" (which means look locally in files for a DNS registration such as /etc/hosts or send a DNS lookup to the DNS server.

In most cases your requests will go to an external DNS server, provided by your ISP.

your computer will open a tcp connection to the DNS server specified by IP address on port 53.
your computer will send "stream.binance.com" to the DNS server.
DNS server will respond with the IP address of stream.binance.com.
your computer then uses the IP address for "stream.binance.com" to make a direct connection.

We have found that in some places in the world, the DNS servers are out of sync, @jaggedsoft has asked you to use 1.1.1.1 (cloud flares DNS server), this basically bypasses your ISPS DNS server.

alternative DNS servers are google
8.8.4.4
8.8.8.8

You asked about 127.0.0.1. 127.0.0.1 is a local loopback connection. Its unlikely you are running a DNS sevrer on your local machine.

Exception to the case, is you are running something like NSCD (name server caching daemon) on your computer.  If you don't know what this is, then do not use 127.0.0.1.

moving the close

@marccasco

**Comment by vfelletti** [comment]
How can I change?

**Comment by PLQin** [comment]
I also encountered this problem:

```
var WebSocket = require('ws');
var ws = new WebSocket(`wss://fstream.binance.com/ws/btcusdt@markPrice`);

ws.on('ping', () => {
    console.log('==========receieved ping from server');
    ws.pong();
});

ws.on('open', function open() {
    console.log('--- connected');

    ws.send(JSON.stringify({
        method: 'SUBSCRIBE',
        params: ['btcusdt@depth'],
        id: "043a7cf2-bde3-4888-9604-c8ac41fcba4d"
    }));
});

ws.on('message', (buffer) => {
    console.log(`--- message`, JSON.stringify(JSON.parse(buffer.toString()), null, 4));
});

ws.on('error', (err) => {
    console.log(`--- error: `, err);
});

ws.on('close', (info) => {
    console.log('--- close: ', info);
});
```

get error:
```
Error: connect ETIMEDOUT 128.242.245.189:443

{
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '128.242.245.189',
  port: 443
}
```

Switched different proxies，replaced the window and mac，still unsuccessful，but replacing `fstream.binance.com` with `stream.binancefuture.com` can succeed!

Who will help me?
