### ISSUE TITLE
API Call for MarketCap?

### ISSUE THREAD

**Issue by bicced** [jaggedsoft/node-binance-api#254]
**Title**
- question

**Short Description:**
- Is there a way to get all coins by Marketcap from Binance?
  
**Platform:**
- macos

**node version:**
- 6.4

**Long descrption**
- Is there an API call to retrieve market cap of all coins on Binance?

thank you

**Comment by jaggedsoft** [comment]
As far as I can tell, there is no api call for https://info.binance.com yet
Personally, I use the coinmarketcap API for this
