### ISSUE TITLE
$api->orderStatus(BNBUSDT, $orderid); PRICE Returns 0.0000

### ISSUE THREAD

**Issue by quadricanna** [jaggedsoft/node-binance-api#255]
$orderid = "43032958";
$orderstatus = $api->orderStatus(BNBUSDT, $orderid);
$order_data = $orderstatus['price'];
print_r($orderstatus);

Please help, following is my result:

Array ( [symbol] => BNBUSDT [orderId] => 43032958 [clientOrderId] => TAZiFYwDVZjB9AnrOEFqAS **[price] => 0.00000000** [origQty] => 0.50000000 [executedQty] => 0.50000000 [status] => FILLED [timeInForce] => GTC [type] => MARKET [side] => BUY [stopPrice] => 0.00000000 [icebergQty] => 0.00000000 [time] => 1531724225146 [isWorking] => 1 )

**Comment by jaggedsoft** [comment]
It looks like you are using the PHP version of the library
Market buy orders always return 0 for the price, unless you specify newOrderRespType. 

php example (shows price of market buy)
```php
$response = $api->marketBuy("BNBUSDT", 1, ["newOrderRespType" => "FULL"]);
print_r($response);
```

node js example https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#neworderresptype-example-when-placing-orders

it returns an array of fills, you can take an average or just return the price of the first one

**Comment by quadricanna** [comment]
This is not a market order, this error is from orderstatus. 

$api->orderStatus(BNBUSDT, $orderid);

**Comment by jaggedsoft** [comment]
as I said, all market orders will return a price of 0.00000. This is a problem with binance
However, you can collect the price you paid during the order with newOrderRespType
