### ISSUE TITLE
'Trade Only' API Keys?

### ISSUE THREAD

**Issue by hugeprestigellc** [jaggedsoft/node-binance-api#256]
Apologies if this isn't exactly an issue but is there a way to determine if an API key offers withdrawal permissions? For security reasons, I'd like any app I build to reject API keys that offer withdrawal permissions.

Is there a way to check that?

**Comment by sanjaySbacancy** [comment]
Hello Support Team,

We have working on Withdraw API but some error facing when API call. We have enable Withdrawals option and add over current server IP Address in IP Access Restriction. Even then not working Withdraw API. 

This error facing when API call :

signedRequest error: {"msg":"You don't have permission.","success":false} 
Array
(
    [msg] => You don't have permission.
    [success] => 
)

Please find the attachment. Please solve issue as soon as possible. 
I hope you reply as soon possible.

Thank you.
