### ISSUE TITLE
feature: Add params for keep-alive REST requests

### ISSUE THREAD

**Issue by vvp83** [jaggedsoft/node-binance-api#257]
We need keep-alive options for requests.
I dnt found any params for module

Thank

**Comment by jaggedsoft** [comment]
The only keepalive that is required is for websocket account data, and this is handled automatically

**Comment by GitGauss** [comment]
I think the op is talking about the Connection: keep-alive header for HTTP persistent connection. So a single TCP connection is used to send multiple requests (e.g. lots of orders). 

Maybe it might be useful to allow override http request options, smth like this:
```javascript
const request = require('request');

let baseRequest = request;

options: function(opt, callback = false) {
	//...
	if (opt.requestDefaults != null) {
		baseRequest = request.defaults(requestDefaults);
	}
	//...

}

//... baseRequest is used then instead of request
```

**Comment by vvp83** [comment]
sorry for question but any news?
