### ISSUE TITLE
When I try an api, and I got this "balanceData error"

### ISSUE THREAD

**Issue by guofengld** [jaggedsoft/node-binance-api#258]
**Got a balanceData error**
- bug: balanceData error

**Short Description:**
Following the instructions and the examples, I created a 'hello world' like app, name app.js, I just want to see if this api works, unfortunately, it not worked for me.
  
**Platform:**
- macos

**node version:**
- v8.11.3  

**code**
```
let path = require('path');

let Binance = require(path.resolve(__dirname, 'node-binance-api.js'));
let binance = new Binance();

binance.options({
      APIKEY: '-',
      APISECRET: '-',
      useServerTime: true,
      reconnect: true,
      verbose: true
});

binance.balance(function(error, balances) {
	console.log('balances: ', balances);
});

```

**result**
```
node app.js
[ 'balanceData error', {} ]                                                                                               
balances:  {}    
```
I'm now in China and using a VPN to access the Binance website, have tried all the ways, need your help
thank you

**Comment by jaggedsoft** [comment]
need error checking

```js
binance.useServerTime(() =>
binance.balance((error, balances) => {
  if ( error ) return console.error(error.body);
  console.log("balances()", balances);
  if ( typeof balances.ETH !== "undefined" ) console.log("ETH balance: ", balances.ETH.available);
})
);
```

**Comment by guofengld** [comment]
nothing different, I think this is caused by the network I'm using
```
let https = require('https');

https.get('https://api.binance.com', function(res) {
  console.log(res);
});
```

event these lines of code will result to a failure, but I can access the address https://api.binance.com with my Chrome browser, confusing...

anyway, thanks for your help

**Comment by rdeelstra** [comment]
Are you sure the API keys are correct? Binance also did an API key reset recently so I would double check that. Also check if there are IP addresses whitelisted at the Binance account.

**Comment by guofengld** [comment]
@rdeelstra I'm sure that the api keys are correct, and IP address not restricted

**Comment by jaggedsoft** [comment]
The only other thing I can think of is the nameservers. Many people have reported success after switching to https://1.1.1.1

**Comment by guofengld** [comment]
@jaggedsoft sorry, I'm not very clear, to switch what? the hosts file?

**Comment by guofengld** [comment]
After setting up proxy as bellow, every thing goes fine
```
process.env.https_proxy='http://127.0.0.1:1087';
process.env.socks_proxy='socks://127.0.0.1:1086';
```

issue closed.
