### ISSUE TITLE
Document the entire websocket data objects

### ISSUE THREAD

**Issue by tonytamps** [jaggedsoft/node-binance-api#26]
Hey, I'm currently trying to handle the `outboundAccountInfo` and `executionReport` websocket responses and I'm finding it impossible to figure out some of the fields.

Any chance you could detail what each of the properties in these objects are?

Thanks.

**Comment by jaggedsoft** [comment]
Hi there, yes this information is available here:

https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#web-socket-payloads

**Comment by tonytamps** [comment]
Awesome and I also found some here - https://www.binance.com/restapipub.html#user-wss-endpoint

I realised that it's not actually coming from your library but from binance themselves.

Thanks.
