### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by marccasco** [jaggedsoft/node-binance-api#260]
**Title**
- bug: TypeError

**Short Description:**
- When checking balances, it usually works for me, but sometimes I miss an error like this, and it causes my node to fall.
How can I control these types of errors? Is there any way to make the node fail and let it continue?
  
**Platform:**
- windows

**node version:**
- 10.5.0

**result**
```
TypeError: Cannot read property 'available' of undefined
```

Thanks!

**Comment by jaggedsoft** [comment]
The most likely cause of this is sending too many requests and being blocked temporarily

Does it show what line number that is on? I can add some more sanity checks so it doesn't error out

**Comment by marccasco** [comment]
Thanks for the quick reply.
Maybe if it is for too many requests, but there must be some way to control this type of errors that sometimes jump, and that the node keeps running, right?

The error does not tell me any more details.

**Comment by marccasco** [comment]
I add:

I fixed this error by updating the computer time.
But surely it will happen again in the future.

I would like to know how to do so if the node does not crash, thank you.
