### ISSUE TITLE
Question of response times

### ISSUE THREAD

**Issue by pedrocarvajal** [jaggedsoft/node-binance-api#264]
I'm working with the "websockets" connection.
I have a question and I need to know what solutions they recommend me.

There are moments that I want to do an operation "Buy or Sale" at the time I send the operation the price for example is 100, which is not consistent is when the order "Buy or sell" is executed the price is not 100. I suppose it is by internet connection? a delay? Can this be improved? as? I need you to open at the correct price.

**Comment by jaggedsoft** [comment]
There are always two different prices. The bid and ask. You should factor buys using the 'ask' price and sells using the 'bid' price.

**Comment by pedrocarvajal** [comment]
I understand, but when I receive the information from the socket I have "high, low, close, open" and keep in mind that I use "market" operations, which I only use symbol and "lot / quantity".

or do you tell me that bit and ask is calculated differently? starting from "close"?

**Comment by jaggedsoft** [comment]
You are talking about chart information, but the orderbook (bid/asks) control the true price when placing orders.
E.g, the "close" price says 8162 for BTC/USDT and you want to buy some. The cheapest ask is $8165 so you end up paying slightly more.

```js
binance.websockets.depthCache(["BTCUSDT"], function(symbol, depth) {
	let asks = binance.sortAsks(depth.asks);
	let bids = binance.sortBids(depth.bids);
	const ask_sum = binance.sum(Object.values(asks));
	const bid_sum = binance.sum(Object.values(bids));
	const best_ask = binance.first(asks);
	const best_bid = binance.first(bids);
	console.log("bid: $"+best_bid+" ask: $"+best_ask+" bids: $"+bid_sum+". asks: $"+ask_sum);
});
```
> bid: $8158.88000000 ask: $8158.89000000 bids: 647.34 BTC. asks: 411.87 BTC.

**Comment by pedrocarvajal** [comment]
That is, suppose I want to make an opening when the "tick" or closing price is at: 100 ..
I do not have to be guided by that 100, if not by the "ask", which would be a close value in the example?

**Comment by jaggedsoft** [comment]
This might be better for you. It has the ask price built in, and updates once per second or more

```js
binance.websockets.prevDay("BTCUSDT", (error, price) => {
  //console.log(price); // view all data
  console.log("BTCUSDT close: "+price.close+" ask: "+price.bestAsk+" volume:"+price.volume+" change: "+price.percentChange+"%");
});

// This works for all symbols
/*binance.websockets.prevDay(false, (error, prevDay) => {
  //console.log(prevDay); // view all data
  for ( let obj of prevDay ) {
    let symbol = obj.symbol;
    console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
  }
});*/
```

**Comment by pedrocarvajal** [comment]
No, I think it does not work for me, because I'm working a strategy that works for the price on each "tick.

For example, I paste my code that I am using to request the request.

`
c.binance.websockets.depthCache([c.symbol], function(symbol, depth) {
	let asks = c.binance.sortAsks(depth.asks);
	let bids = c.binance.sortBids(depth.bids);
	const ask_sum = c.binance.sum(Object.values(asks)).toFixed(2);
	const bid_sum = c.binance.sum(Object.values(bids)).toFixed(2);
	var best_ask = c.binance.first(asks);
	var best_bid = c.binance.first(bids);
	ask = best_ask;
});

c.binance.websockets.chart(c.symbol, c.symbol_period, (symbol, interval, chart) => {
	let tick = c.binance.last(chart);
	const t = chart[tick];

	if (last_tick!=null) {
		log(t.close + '/' + ask);
	}

	last_tick = t;
});
`

For each "tick" I would be opting for the last ask.

**Comment by pedrocarvajal** [comment]
Taking as a reference the "bid / ask" solves the problem that when I enter an operation I enter with another price?

**Comment by pedrocarvajal** [comment]
I show you an image of what you intend to explain, the first date indicates the price at which an opening condition was fulfilled, but if you look below (second arrow) it is the price at which the order was executed! They have more than 2 USD difference.

Why do you think that problem is?
to. Delay in the execution of the order? (lag)?
b. I'm taking "t.close" (http://prntscr.com/kcviq9) as the reference price, and should I take "bid"?

**Comment by jaggedsoft** [comment]
It's because you need to use 'ask' not 'close' if you want the price to be the same
Chart data does not have this available, which is why it's easier to read it directly from the order book (depthCache)

**Comment by pedrocarvajal** [comment]
Ok, Thank you very much for your answers!
