### ISSUE TITLE
CORS issue on request

### ISSUE THREAD

**Issue by Mithgroth** [jaggedsoft/node-binance-api#27]
Helloes,
I'm getting CORS errors on all my calls:

`Failed to load https://api.binance.com/api/v1/ticker/allPrices: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Is there a spesific option I'm missing while initiating?

**Comment by jaggedsoft** [comment]
No exchange supports API calls from within the browser or plugins
