### ISSUE TITLE
Missing candlesticks where calling candlesticks for IOTABTC 4 hour

### ISSUE THREAD

**Issue by jamespfarrell** [jaggedsoft/node-binance-api#270]
**Title**
- bug: Missing candlesticks
- feature: please add
- enhancement: add this to existing features

**Short Description:**
Run:
         binance.candlesticks('IOTABTC', '4h', function (error, candles) {

                candles.forEach((candle) => {
                    console.log(candle[0]);
                 })
            });

You will see that there are missing candles after 1529971200000 and 1530662400000. There 14400000 milliseconds between each candle....
  
**Platform:**
- linux

**node version:**
- v8.9.4

**Comment by jaggedsoft** [comment]
Thank you for the report, but this problem is most likely on Binance's end. The API's job is just to make their own functions easier to use
