### ISSUE TITLE
Can't use variable out of the method "Get Kline/candlestick data for a symbol"

### ISSUE THREAD

**Issue by kobej1** [jaggedsoft/node-binance-api#273]
### Description
I want to use the variables to calculate the RSI of the last 14 hours but I can't use the variables in another function(CODE1). I also have tried to put the second function into the "binance.candlesticks" function. You can also find the code in the attachments below. Can someone please help me or is this an issue?
 
[project.zip](https://github.com/jaggedsoft/node-binance-api/files/2325371/project.zip)

### CODE1
```
//To convert time into ms
  var unixTime = new Date();
  unixTime.getUTCDate();
  var unixTime = Math.round(unixTime);

//To convert time into just the hour 
//For example 11:42 -> 11:00
  var hour = new Date();
  hour.getUTCDate();
  hour.setMinutes(0);
  hour.setSeconds(0);
  hour.setMilliseconds(0);
  var hour = Math.round(hour);
  
//Minus 1 hour
//For example 11:00 -> 10:00
  var h1 = 3600000;
  var hourMin1 = hour - h1;

//Intervals: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1
binance.candlesticks("BNBBTC", "1h", function (error, ticks, symbol){
  console.log("candlesticks()", ticks);
  let last_tick = ticks[ticks.length - 1];
  let [time, open, high,low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = last_tick;
  console.log(last_tick[4]);},  {limit: 30, endTime: unixTime}, 
);

console.log(last_tick[4]); 
//I want to use this variabele in another function
```

### CODE2
```
//To convert time into ms
  var unixTime = new Date();
  unixTime.getUTCDate();
  var unixTime = Math.round(unixTime);

//To convert time into just the hour 
//For example 11:42 -> 11:00
  var hour = new Date();
  hour.getUTCDate();
  hour.setMinutes(0);
  hour.setSeconds(0);
  hour.setMilliseconds(0);
  var hour = Math.round(hour);
  
//Minus 1 hour
//For example 11:00 -> 10:00
  var h1 = 3600000;
  var hourMin1 = hour - h1;
  

//Intervals: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1
binance.candlesticks("BNBBTC", "1h", function (error, ticks, symbol){
  console.log("candlesticks()", ticks);
  let last_tick = ticks[ticks.length - 1];
  let [time, open, high,low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = last_tick;
  console.log(last_tick[4]);},  {limit: 1, endTime: unixTime}, 
  function (error, ticks, symbol){
    console.log("candlesticks()", ticks);
    let prev_tick = ticks[ticks.length];
    let [time, open, high,low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = prev_tick;
    console.log(prev_tick[4]);},  {limit: 1, endTime: hourMin1}, 
);
```

### In the terminal I get this result (CODE1)
last_tick is not defined
(The first "last_tick[4]" inside the function works perfect)

### In the terminal I get this result (CODE2)
Only the results of the first function appear to the terminal

Can someone please help me?
Thank you!

**Comment by jaggedsoft** [comment]
https://github.com/anandanand84/technicalindicators

Just pass the `close` parameter from the candlestick function to any of those functions

**Comment by kobej1** [comment]
When I try to pass the parameter into the function RSI for example I get the error "close is not defined". I also have tried to put the paramater close in another variable. 

In the attachments you can find a screenshot.

![untitled](https://user-images.githubusercontent.com/42657049/44682823-bf5f6c00-aa44-11e8-82c7-6bd429bdabdc.png)

Can someone please help me?
Thank you!

**Comment by jaggedsoft** [comment]
yes copy all that code from line 43 to line 55 and put it directly after line 38

But the code that is on line 46 needs to change to this: `values: close`

**Comment by jaggedsoft** [comment]
Here this function is the best way to do it I think
But it is a websocket function so it will keep updating every time the chart changes

```js
const TA = require('technicalindicators');
binance.websockets.chart("BNBBTC", "1h", (symbol, interval, chart) => {
  let ohlc = binance.ohlc(chart);
  let rsi = TA.RSI.calculate({values:ohlc.close, period:14});
  let last_rsi = rsi[rsi.length - 1];
  console.log("RSI: "+last_rsi);
});
```

**Comment by kobej1** [comment]
@jaggedsoft Thanks a lot! I have just one more question. When I try to use the Stoch function on the same way I get the error message "Cannot read property 'length' of undefined". In the attachments you can find a screenshot of the code and the official example of the Stochastic function. Can you please help me? 

### Code
```
//Stoch
binance.websockets.chart("BNBBTC", "1h", (symbol, interval, chart) => {
  let ohlc = binance.ohlc(chart);
  let period = 14;
  let signalperiod = 3;
  let stoch = TA.Stochastic.calculate({high:ohlc.high, period:30}, {low:ohlc.low, period:30}, {close:ohlc.close, period:30}, {period:period}, {signalperiod:signalperiod});
  let last_stoch = stoch[stoch.length - 1];
  console.log("STOCH: "+last_stoch);
});

```
### Attachments
![image](https://user-images.githubusercontent.com/42657049/44715338-d4c1ae00-aab7-11e8-8b86-ef5fc676650a.png)

 https://runkit.com/anandaravindan/stochastic
