### ISSUE TITLE
depthCache all symbols

### ISSUE THREAD

**Issue by Dinfyru** [jaggedsoft/node-binance-api#274]
Is there ways to get info from websockets.depthCache for all symbols?
If i do it now, i will have error `'{"code":-1003,"msg":"Way too many requests; IP banned until 1535720616258. Please use the websocket for live updates to avoid bans."}'`

I need do this for get all info about all symbols in real time.

**Comment by jaggedsoft** [comment]
Yeah you can run a loop at your program startup to open a new depthCache request every 350ms

It might be easier to subscribe to one of the other endpoints though, do you need actual in depth order book information?

**Comment by jaggedsoft** [comment]
Feature request: Automatic rate limiting if subscribing to > 100 symbols

**Comment by bmino** [comment]
I've got a function that staggers the subscriptions in batches at a configurable delay. Want a PR?

**Comment by jaggedsoft** [comment]
@bmino, all of your pull requests are welcome, your previous ones have been very good. Thanks friend

**Comment by bmino** [comment]
Glad to help out! I submitted #294 to address this
