### ISSUE TITLE
 Buy and Sell full  using Market

### ISSUE THREAD

**Issue by mfidelli** [jaggedsoft/node-binance-api#275]
Hi
Is possible buy and sell full using marketBuy and marketSell?
Example:
binance.marketBuy ("BTCUSDT", "full");

thank you

**Comment by jaggedsoft** [comment]
No but that is a good idea

For now you have to take a few steps:
1. call exchangeInfo and record the values, like minQty and minNotional
2. get your balance in BTC
3. divide btc balance by minNotional

```
			let minNotional = minimums[symbol].minNotional;
			if ( ask * amount < minNotional ) {
				amount = minNotional / ask;
			}

			binance.marketBuy(symbol, amount, (error, response) => {
				if ( error ) return console.error("marketBuy",error,response);
				console.log("..Market Buy response", response);
				console.log("..order id: " + response.orderId);
			});
```
