### ISSUE TITLE
How I can get a server time? 

### ISSUE THREAD

**Issue by allawitte** [jaggedsoft/node-binance-api#277]
How it is possible to get server time? If I do binance.time()  or binance.time(data => console.log(data)) - I get null

**Comment by jaggedsoft** [comment]
First parameter is the `error` object so if that's null then it's a good thing

```js
binance.time((error, data)=> {
  console.log("Time: " + data.serverTime, new Date(data.serverTime).toLocaleString());
});
```

**Comment by allawitte** [comment]
Thanks a lot!
