### ISSUE TITLE
binance websockets trades response keys

### ISSUE THREAD

**Issue by allawitte** [jaggedsoft/node-binance-api#279]
If I send such request
binance.websockets.trades(['BNBBTC', 'ETHBTC'], (trades) =>  {
      console.log(trades);
    });
and get this kind of answer:
_E:1536277339895
M:true
T:1536277339889
a:201936172
b:201936183
e:"trade"
m:false
p:"0.03541800"
q:"0.12800000"
s:"ETHBTC"
t:80898401_

What is a and b keys? How to deshifrate it?

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#trade-streams

`b` is buyer order id and `s` is seller order id

You might try [aggTrades](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#aggregate-trade-streams) to see if it is easier

**Comment by allawitte** [comment]
Super! I suspect it, but was not sure.
