### ISSUE TITLE
websockets how to catch internet collapse error

### ISSUE THREAD

**Issue by allawitte** [jaggedsoft/node-binance-api#283]
when use:    binance.websockets.trades(symbols, (trades) => { ... })  and internet suddenly not working - how I can catch it?

**Comment by jaggedsoft** [comment]
Right now it will try to reconnect but not fire any kind of notification
I believe we still need logic to keep retrying connections if it failed the first time

**Comment by subos2008** [comment]
+1 for this feature request. Also suppression of the messages that get printed, it's spamming my logs.
