### ISSUE TITLE
Market Buy Error

### ISSUE THREAD

**Issue by allawitte** [jaggedsoft/node-binance-api#285]
When I send request like:
binance.buy("ADABTC", 1,  (error, response) => {
      console.log('error', error);
      if(error){
        console.log(error.body);
        serverSocket.write(JSON.stringify(error.body));
        return;
      }
      console.log("Limit Buy response", response);
      console.log("order id: " + response.orderId);
      if(response.orderId){
        serverSocket.write(JSON.stringify({orderId: response.orderId}));
      }
    });
I get error like:  ["BUY(ADABTC,1,NaN) ", {…}]  from line 46 node-binance-api.js

I even don't get any error message, just it doesn't go

What I'm doing wrong?

**Comment by jaggedsoft** [comment]
buy function requires symbol (ADABTC)
then quantity (1)
then price <-- limit orders require the price you want to pay

If you get a blank response, make sure test mode is not enabled
If you just want to market buy 1, use the market buy function. cheers!

**Comment by allawitte** [comment]
Oh, thank you!
I did stupid mistake :))
Now I change to:
binance.marketBuy(ADABTC, 1,  (error, response) => {
      if(error){
        console.log(error.body);
        serverSocket.write(JSON.stringify(error.body));
        return;
      }
      console.log("Limit Buy response", response);
      console.log("order id: " + response.orderId);
      if(response.orderId){
        serverSocket.write(JSON.stringify({orderId: response.orderId}));
      }
    });

and get an error:
{"code":-1013,"msg":"Invalid price."}  - how it is possible? I don't send any price!

**Comment by allawitte** [comment]
Thank you! All is perfect!
