### ISSUE TITLE
Getting 'balanceData error', {} with certain API keys only

### ISSUE THREAD

**Issue by hugeprestigellc** [jaggedsoft/node-binance-api#286]
Getting an issue where binance.withdrawal() is called and the response coming back is: 'balanceData error', {}

useServerTime is set to true and I also started calling binance.useServerTime() before the withdrawal call is made as per some advice I saw in other issue threads. Unfortunately, the user that is encountering this issue is still getting this balanceData error.

Have you heard of this issue before and is there any potential solution?

Thanks!

**Comment by jaggedsoft** [comment]
I saw this twice in my logs last night: `[ 'balanceData error', {} ]`
This seems to be a new thing. I haven't experienced it before

**Comment by algomeister** [comment]
I get the same error but only sometimes. Any possible reason/solution?

**Comment by chorsnell** [comment]
call `await binance.useServerTime();` before your balance request, as mentioned in the [troubleshooting](https://github.com/jaggedsoft/node-binance-api#troubleshooting), that should solve it :)
