### ISSUE TITLE
How to close websocket

### ISSUE THREAD

**Issue by allawitte** [jaggedsoft/node-binance-api#288]
if I do binance.websockets.terminate()  - I get an error:
["CombinedStream: Parse error: This socket has been ended by the other party"]0: "CombinedStream: Parse error: This socket has been ended by the other party"length: 1__proto__: Array(0)

How to do it correctly?
Is it possible to close only specific socket, not all?
And, by the way, how to logout from binance?

**Comment by jaggedsoft** [comment]
If you want the ability to terminate a connection:
1. You must set `reconnect: false` as part of your options
2. You must open the socket by itself and not with any other symbols.

Examples:
```js
// Test websocket reconnections
// Note: These websockets were opened with an array of more than one symbol.
//They can not be disconnected individually unless you connect individually.
//Send a string instead of an array. Like this: binance.websockets.trades('ETHBTC',
binance.websockets.trades(['BNBBTC', 'ETHBTC'], (trades) => {
	let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
	console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
setInterval(function() {
	// Terminate all websocket endpoints, every 6 sec
	let endpoints = binance.websockets.subscriptions();
	for ( let endpoint in endpoints ) {
		console.log("..terminating websocket: "+endpoint);
		let ws = endpoints[endpoint];
		ws.terminate();
	}
},6000);

// Optional test function to show all connected endpoints
setInterval(function() {
	// List all endpoints
	let endpoints = binance.websockets.subscriptions();
	for ( let endpoint in endpoints ) {
		console.log(endpoint);
		//let ws = endpoints[endpoint];
		//ws.terminate();
	}
}, 2500);

// Example of terminating a specific endpoint
setTimeout(function() {
	binance.websockets.terminate('ethbtc@kline_1m');
	//let endpoints = binance.websockets.subscriptions();
	let ws = endpoints['ethbtc@kline_1m'];
	ws.terminate();
	console.log('endpoint terminated');
}, 6000);
```

**Comment by allawitte** [comment]
Thank you.
But still something strange.
I do:
authBinance(request) {
        this.binance = new Binance().options({
            APIKEY: request[2],
            APISECRET: request[3],
            **reconnect: false,**
            useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
            //test: true // If you want to use sandbox mode where orders are simulated
        });

closeSockets(){
        let endpoints = this.binance.websockets.subscriptions();
        for ( let endpoint in endpoints ) {
            console.log("..terminating websocket: "+endpoint);
            let ws = endpoints[endpoint];
            ws.terminate();
        }    }

and still get the same error:
["CombinedStream: Parse error: This socket has been ended by the other party"]0: "CombinedStream: Parse error: This socket has been ended by the other party"length: 1__proto__: Array(0)

What I do wrong?

**Comment by jaggedsoft** [comment]
I'd have to see how you're connecting to your websocket. It's still being set up as a CombinedStream which is not what we want

```js
//Old way: binance.websockets.trades(['BNBBTC', 'ETHBTC'], (trades) => {
binance.websockets.trades('BTCUSDT', (trades) => {
	//let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
	//console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
```
What we're doing here is sending a string as the first parameter instead of an array
