### ISSUE TITLE
Q: How to get the status of a ticker (active/inactive) using prevDay()

### ISSUE THREAD

**Issue by kitt-th** [jaggedsoft/node-binance-api#289]
Hello,

I wish to detect whether a symbol returned from a ticker request using prevDay() is active or not.
For example, VENBTC has been inactive for a couple of months, but there is no indicator to show this in the data returned, which is :

 { symbol: 'VENBTC',
  priceChange: '-0.00000045',
  priceChangePercent: '-0.187',
  weightedAvgPrice: '0.00024205',
  prevClosePrice: '0.00024048',
  lastPrice: '0.00024002',
  lastQty: '378.00000000',
  bidPrice: '0.00000000',
  bidQty: '0.00000000',
  askPrice: '0.00000000',
  askQty: '0.00000000',
  openPrice: '0.00024047',
  highPrice: '0.00024743',
  lowPrice: '0.00023837',
  volume: '1569005.00000000',
  quoteVolume: '379.77231106',
  openTime: 1532287028321,
  closeTime: 1532373428321,
  firstId: 10404503,
  lastId: 10411872,
  count: 7370 }

Sure I could test the closeTime as that should be very close to the current time but I am sure that there is specific data available somewhere from the API that says whether a market is active or inactive.

Any pointers/help/info welcome.

Cheers.

**Comment by jaggedsoft** [comment]
Good question, I am surprised no one has talked about this yet.
Normally we can do it by daily volume, but it appears that volume hasn't been updated in a very long time.
https://api.binance.com/api/v1/exchangeInfo

exchangeInfo is the answer. It tells us the state of every market.

![image](https://user-images.githubusercontent.com/4283360/45598361-79624c00-b9e3-11e8-9888-8e136b2017cc.png)

```js
//minQty = minimum order quantity
//minNotional = minimum order value (price * quantity)
binance.exchangeInfo(function(error, data) {
	let minimums = {};
	for ( let obj of data.symbols ) {
		let filters = {status: obj.status};
		for ( let filter of obj.filters ) {
			if ( filter.filterType == "MIN_NOTIONAL" ) {
				filters.minNotional = filter.minNotional;
			} else if ( filter.filterType == "PRICE_FILTER" ) {
				filters.minPrice = filter.minPrice;
				filters.maxPrice = filter.maxPrice;
				filters.tickSize = filter.tickSize;
			} else if ( filter.filterType == "LOT_SIZE" ) {
				filters.stepSize = filter.stepSize;
				filters.minQty = filter.minQty;
				filters.maxQty = filter.maxQty;
			}
		}
		//filters.baseAssetPrecision = obj.baseAssetPrecision;
		//filters.quoteAssetPrecision = obj.quoteAssetPrecision;
		filters.orderTypes = obj.orderTypes;
		filters.icebergAllowed = obj.icebergAllowed;
		minimums[obj.symbol] = filters;
	}
	console.log(minimums);
	global.filters = minimums;
	//fs.writeFile("minimums.json", JSON.stringify(minimums, null, 4), function(err){});
});
```
This will show items that have the status of BREAK so you know to exclude them.

Another option would be using `bookTickers` .. this is what I do on startup to determine what markets I'm interested in. This filters out symbols with no bids, (inactive market) or you can select only BTC/ETH/BNB/USDT pairs, etc.
```js
binance.bookTickers((error, ticker) => {
	if ( error ) console.error(error);
	let markets = [], symbol; //'BTCUSDT'
	for ( symbol in ticker ) {
		let obj = ticker[symbol];
		if ( obj.bids == '0.00000000' ) continue;
		///////////////////////////////////////////////
		if ( symbol.substr(-3) !== 'BTC' ) continue;
		//if ( symbol.substr(-3) == 'ETH' ) continue;
		//if ( symbol.substr(-3) == 'USDT' ) continue;
		///////////////////////////////////////////////
		markets.push(symbol);
	}
	console.log(markets);
});
```

**Comment by kitt-th** [comment]
great thanks
