### ISSUE TITLE
Stop Loss Order Not Working

### ISSUE THREAD

**Issue by yongyi520** [jaggedsoft/node-binance-api#29]
When calling stop loss order, I use the following code to test stop loss order:

binance.sell(exchangePair, quantity, price, { stopPrice: price }, function (response) {...}

 I got the following error:
{ code: -1106,
msg: 'Parameter \'stopPrice\' sent when not required.' }

**Comment by Bestulo** [comment]
I don't know if this one is the case, but sometimes Binance API will return an error even when the order was successful. After doing that, make a get orders request in order to verify that it isn't already placed.

**Comment by jaggedsoft** [comment]
I will investigate and get back to you. I can verify that stop loss orders are not working as intended. Thanks for the feedback!

**Comment by jaggedsoft** [comment]
Unfortunately I have not been able to find the cause of this issue yet but I intend on fixing it as soon as I have the time

**Comment by yongyi520** [comment]
I think the cause of it is from binance server and not your code. Hope Binance updates their documentation with a stop loss order example

**Comment by jaggedsoft** [comment]
Yes I just remembered they added the STOP_LIMIT flag which needs to be passed
So perhaps I will check for the presence of stopPrice and if it exists I will automatically bump the order to a STOP_LIMIT

**Comment by yongyi520** [comment]
Oh that would be great! Thank you for being so active on github! :)

**Comment by jaggedsoft** [comment]
You must pass the 'type' of stop loss order it is
```
STOP_LOSS
STOP_LOSS_LIMIT
TAKE_PROFIT
TAKE_PROFIT_LIMIT
LIMIT_MAKER
```
#### Placing a STOP LOSS order
```javascript
// When the stop is reached, a stop order becomes a market order
// Note: You must also pass one of these type parameters:
// STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT
let type = "STOP_LOSS";
let quantity = 1;
let price = 0.069;
let stopPrice = 0.068;
binance.sell("ETHBTC", quantity, price, {stopPrice: stopPrice, type: type});
```

**Comment by jaggedsoft** [comment]
Added exception handling to throw an error if `type` is 'LIMIT' and `stopPrice` is set
https://github.com/jaggedsoft/node-binance-api/commit/000ddec6c4ad20e531086442271b485c2febc446

**Comment by preethichunduri** [comment]
I want to set the Limit Price while selling using Sell function. How can I do that? When i set stopprice, at times its making a partial fill. To avoid that, i also want to set the Limit field as in the binance website and pass it to this function.
