### ISSUE TITLE
ESOCKETTIMEDOUT on candlesticks() call

### ISSUE THREAD

**Issue by kitt-th** [jaggedsoft/node-binance-api#290]
Hello,

Currently experiencing several ESOCKETTIMEDOUT errors when calling websocket.candlesticks()
recvWindow is set very high in the options (120000) so unsure what the problem may be.

I'm querying a few different pairs and the ESOCKETTIMEDOUT error happens on a random pair each time .

e.g.

ZILBTC { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/brianmay/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.emitTimeout (_http_client.js:702:34)
    at Object.onceWrapper (events.js:255:19)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket.Socket._onTimeout (net.js:415:8)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5) code: 'ESOCKETTIMEDOUT', connect: false }

Any ideas what could cause this and how to handle it?

Cheers

**Comment by jaggedsoft** [comment]
How many is a few different pairs? If we're doing many pairs at once we probably want to call it on a timer so you don't get temporarily blocked for flooding too many requests at once.

**Comment by kitt-th** [comment]
Ah right, 60 pairs were being requested, so that is probably what's doing it. 
As I didn't receive a "too many requests" error I thought it could be something else.
I will stagger the requests..

**Comment by jaggedsoft** [comment]
Here's an example of how I implement rate limiting. It's a simple 175ms delay between candlestick requests
```js
binance.bookTickers((error, ticker) => {
	if ( error ) console.error(error);
	let markets = [], symbol; //'BTCUSDT'
	for ( symbol in ticker ) {
		let obj = ticker[symbol];
		if ( obj.bids == '0.00000000' ) continue;
		///////////////////////////////////////////////
		if ( symbol.substr(-3) !== 'BTC' ) continue;
		//if ( symbol.endsWith('ETH') ) continue;
		//if ( symbol.endsWith('USDT') ) continue;
		///////////////////////////////////////////////
		markets.push(symbol);
	}
	console.log(markets);
	for ( symbol of markets ) {
		setTimeout(candlesticks, count++ * 175, symbol);
	}
});
function candlesticks(symbol) {
	binance.websockets.chart(symbol, "4h", chartHandler);
}
//////////////////////////////////////////////
function chartHandler(symbol, interval, chart) {
	let tick = binance.last(chart);
	const last = chart[tick].close;
	console.log(symbol, interval, last);
}
```

**Comment by ptykamikaze** [comment]
Hello... I was having the same problem and reused that code to retrieve the candlestick history... it was working at the beginning but the error came back... I'm loading 20 coin pairs and after loading the 5, it give me the same error. I added a 500 ms delay and didn't work... Any idea or fix ?
