### ISSUE TITLE
Ticker null or undefined

### ISSUE THREAD

**Issue by djumanji** [jaggedsoft/node-binance-api#293]
**binance.prices((error, ticker) => {**

- bug: ticker is sometimes unavailable

**Short Description:**
Hi, first of all thank you for the complete solution you provided.

I'm using binance.prices in a simple loop with a timeout that reset the script. In this case, all I am doing is parsing cryptos in order to get their change rates from time A to time B.

ex : function refreshData(){

	getCryptos(); // is using binance.prices in order to get variations of cryptos prices.

	setTimeout(Refresh_Data,5000); // will re-execute getCryptos every 5 seconds

}

In getCryptos(), I'm using binance.prices(err,ticker)... And, sometimes, all of a sudden, the script crashes with the error : "Cannot convert undefined or null to object". It seems indeed that from a minute to another, ticker is null/empty, and I don't know why.

What I did to prevent the error is setting a simple "if" condition like this one "if(ticker != null && ticker !=="undefined"), at least my script doesn't crash and can purchase when ticker is not null again, it can take sometimes 5 to 10 minutes.

Any ideas from you will be welcome !

**Platform:**
- linux ubuntu

**node version:**
- 9.11

thank you !

**Comment by jaggedsoft** [comment]
without seeing your call to binance.prices I can't provide much input
the first thing I would suggest is make sure you're handling the error event if you're not already

```js
binance.prices((error, ticker) => {
    if ( error ) return console.error(error.body);
});
```

**Comment by djumanji** [comment]
It seems that you made my day.

I added the error statement, it returned me :

{"code":-1003,"msg":"Way too many requests; IP banned until 1538153468729. Please use the websocket for live updates to avoid bans."}

Thank you again, but please if you had some, could you give me informations about websockets usage for binance ?

**Comment by jaggedsoft** [comment]
Yes friend, Websockets is what you want. It does not cost anything and you get streamed the data right away. I feel like you will have better luck using the bid price or the ask price.
```js
binance.websockets.prevDay('BNBBTC', function(response) {
	//console.log(response);
	let symbol = response.symbol;
	console.log(symbol+" bid: ", response.bidPrice);
	console.log(symbol+" ask: ", response.askPrice);
});
```

Personally, my bot takes this approach:
1. Download prevDay information so we know what markets we're interested in (you can filter by volume here, or only trade on ETH pairs, whatever you want)
2. Subscribe to all the markets at once

Here is a complete example for you of how I do it:
```js
const Binance = require('node-binance-api');
const binance = new Binance().options("options.json");
global.ticker = {};

// Get all symbols
binance.prevDay(false, (error, prevDay) => {
    if ( error ) return console.log(error.body);
    let markets = [];
    for ( let obj of prevDay ) {
        let symbol = obj.symbol;

        // Filter BTC & USDT markets only (example)
        if ( !symbol.endsWith('BTC') && !symbol.endsWith('USDT') ) continue;

        console.log(`${symbol} price: ${obj.lastPrice} volume: ${obj.volume} change: ${obj.priceChangePercent}%`);
        global.ticker[symbol] = obj.lastPrice;
        markets.push(symbol);
    }

    // Subscribe to trades endpoint for all markets
    binance.websockets.trades(markets, (trades) => {
        let { e: eventType, E: eventTime, s: symbol, p: price, q: quantity, m: maker, a: tradeId } = trades;
        console.log(`${symbol} price: ${price}`);
        global.ticker[symbol] = price;
    });

    // You can use global.ticker anywhere in your program now
    setInterval(() => {
        console.log("*** Price of BTC: " + global.ticker.BTCUSDT);
    }, 3000);
});
```

**Comment by djumanji** [comment]
Very interesting.

I would have so much more questions to ask you but I don't want to bother you.. Anyway, thank you again for your support and this complete full example, I will definitely look in the same way as you did.

Ps: do you sometimes make conference or reports about crypto bots ? I would love to hear your advices concerning financial strategies to adopt on a bot ?
