### ISSUE TITLE
This dependency was not found - v - 0.8.4

### ISSUE THREAD

**Issue by zerotn3** [jaggedsoft/node-binance-api#295]
I have used `yarn add node-binance-api` and then import package. it's show error below. Please help me check. Thank you.

* dns in ./node_modules/socks-proxy-agent/index.js

To install it, you can run: npm install --save dns

**Comment by jaggedsoft** [comment]
Hmm try this first `npm install socks-proxy-agent -g`
strange that no one has reported this problem until now
