### ISSUE TITLE
Minimum value in BTC market exchanges to sell decimals

### ISSUE THREAD

**Issue by djumanji** [jaggedsoft/node-binance-api#297]
What is the minimum value of a crypto in BTC market exchanges to allow decimals sells ?

Hi Mr Eyrick,

I came to you a few weeks ago because I had a problem with websockets, your help was very helpful.

I am facing a little problem with my bot when I sell cryptos.

Using binance.balances(..), I get the amount of a crypto stored on my account, and most of the time this amount is with decimals.
Main problem is that sometimes decimals are acceped, (ex: SELL, ETHBTC, 89.100, 0.031715) and sometimes decimals are not (ex: SELL, TRXBTC, 112000.123, 0.00000382). 

So I was wondering what could be this minimum value for a crypto on BTC market exchanges to sell it with decimals.

I know that it is not mainly the aim of github issues, but I asked the same question on Binance support but unfortunately I had an automatic answer that was not what I really expected.

**Platform:**
- linux ubuntu

**code**

      if(current_value >= obj.stop_wins){ // stop_wins

                  var str_currency_symbol = obj.currency_symbol;

                  str_currency_symbol = str_currency_symbol.substring(0, str_currency_symbol.length - 3);

                  binance.balance((error, balances) => { // getting quantity available to sell

                    if ( error ) return console.error(error);

                    var quantity_available = balances[str_currency_symbol].available;

                    binance.sell(obj.currency_symbol, quantity_available, obj.stop_wins); // !! WILL CRASH HERE IF I SELL DECIMALS ON A LOW VALUE CRYPTO !!

Best regards,

Julien

**Comment by jaggedsoft** [comment]
Hi friend, the issue here is you are limited by minQty, minNotional and stepSize

You must conform to whatever exchangeInfo() shows in terms of minQty, minNotional and stepSize.
1. Get exchangeInfo data at startup, then you can use it anywhere in your program. Complete example at bottom of page

### Clamp order quantities to required amounts via minQty, minNotional, stepSize when placing orders
```js
let symbol = 'ETHBTC';
let price = 0.1234;
let qty = 1;
let minNotional = global.minimums[symbol].minNotional;

// Set minimum order amount with minQty
if ( qty< minQty ) qty = minQty;

// Set minimum order value with minNotional
if ( price * qty < minNotional ) {
	qty = minNotional / price;
}

// Round to stepSize
qty = binance.roundStep(qty, stepSize);
// Now buy or sell with "qty" and "price"

```

![image](https://user-images.githubusercontent.com/4283360/36249988-528054dc-11f1-11e8-90b8-c6002f2639f0.png)

Note here it tells us the state of each market too, this one is set to "BREAK" which means there is no trading on this symbol.
![image](https://user-images.githubusercontent.com/4283360/45598361-79624c00-b9e3-11e8-9888-8e136b2017cc.png)


### Complete example
```js
global.ticker = {};
global.balance = {};
global.minimums = {};
// Get exchangeInfo on startup
//minNotional = minimum order value (price * quantity)
binance.exchangeInfo((error, data) => {
	if ( error ) console.error(error);
	let minimums = {};
	for ( let obj of data.symbols ) {
		let filters = {status: obj.status};
		for ( let filter of obj.filters ) {
			if ( filter.filterType == "MIN_NOTIONAL" ) {
				filters.minNotional = filter.minNotional;
			} else if ( filter.filterType == "PRICE_FILTER" ) {
				filters.minPrice = filter.minPrice;
				filters.maxPrice = filter.maxPrice;
				filters.tickSize = filter.tickSize;
			} else if ( filter.filterType == "LOT_SIZE" ) {
				filters.stepSize = filter.stepSize;
				filters.minQty = filter.minQty;
				filters.maxQty = filter.maxQty;
			}
		}
		//filters.baseAssetPrecision = obj.baseAssetPrecision;
		//filters.quoteAssetPrecision = obj.quoteAssetPrecision;
		filters.orderTypes = obj.orderTypes;
		filters.icebergAllowed = obj.icebergAllowed;
		minimums[obj.symbol] = filters;
	}
	//console.log(minimums);
	global.minimums = minimums;
	//fs.writeFile("json/minimums.json", JSON.stringify(minimums, null, 4), (err)=>{});

	// Get ticker prices
	binance.prices((error, ticker) => {
		if ( error ) console.error(error);
		for ( let symbol in ticker ) {
			global.ticker[symbol] = parseFloat(ticker[symbol]);
		}
                // Get balance on a timer every 5 seconds
		setInterval(function(){ balance(); }, 5000);
		balance();
	});
});

// Get your balances
function balance() {
	binance.balance((error, balances) => {
		if ( error ) console.error(error);
		let btc = 0.00;
		for ( let asset in balances ) {
			let obj = balances[asset];
			obj.available = parseFloat(obj.available);
			//if ( !obj.available ) continue;
			obj.onOrder = parseFloat(obj.onOrder);
			obj.btcValue = 0;
			obj.btcTotal = 0;
			if ( asset == 'BTC' ) obj.btcValue = obj.available;
			else if ( asset == 'USDT' ) obj.btcValue = obj.available / global.ticker.BTCUSDT;
			else obj.btcValue = obj.available * global.ticker[asset+'BTC'];
			if ( asset == 'BTC' ) obj.btcTotal = obj.available + obj.onOrder;
			else if ( asset == 'USDT' ) obj.btcTotal = (obj.available + obj.onOrder) / global.ticker.BTCUSDT;
			else obj.btcTotal = (obj.available + obj.onOrder) * global.ticker[asset+'BTC'];
			if ( isNaN(obj.btcValue) ) obj.btcValue = 0;
			if ( isNaN(obj.btcTotal) ) obj.btcTotal = 0;
			btc+= obj.btcTotal;
			global.balance[asset] = obj;
		}
		//fs.writeFile("json/balance.json", JSON.stringify(global.balance, null, 4), (err)=>{});
	});
}
```

**Comment by djumanji** [comment]
Well, thank you so much for the complete solution !

What I appreciate when I ask you something, is that it does not start from a big thing (to me), but it leads to long changes in the organization of my code.

Definitely, I need to learn more and more, thank you again, problem will be solved soon.
