### ISSUE TITLE
Send Buy Market Order Simple and Easy

### ISSUE THREAD

**Issue by skhaleqi** [jaggedsoft/node-binance-api#298]
I would like to explain this issue:
Imagine that the account USDT balance is 10$. The BTC price in USDT is 1000$. Now you would like to send buy order with market type to binance.
node binance api dose this operation simple:
`let quantity=0.01;
binance.marketBuy("BNBBTC", quantity);`
Advance type of function and other option has been shown in internet.
at the moment of sending order to Bianace the BTC price raise up to 1001$ therefore the quantity of BTC for send by market should be 0.009 and the order has been return error from binance.
my question is:
Is there any way or solution to solve the quantity problem or binance has automate calculate the quantity or etc? I know that binance dose this operation in desktop application.

platform: linux
thank you

**Comment by skhaleqi** [comment]
thank for your reply

> The alternative is just using market orders

In my post i have mentioned that:

> Now you would like to send buy order with market type to binance.

but that seem there is no automatic way to calculate quantities.
because some time market price raise rapidly. Am I right?
my fast solution is  place market quantity with more couple cents.

**Comment by jaggedsoft** [comment]
Yeah you can calculate the quantity for that instant. For example, if you want to order .5 btc worth of BNB: `qty = 0.5 / price;`
Then just order, it works every time

```js
// Check minimum order size
let minNotional = 0.5;
if ( price * qty < minNotional ) {
    qty = minNotional / price;
}
```
