### ISSUE TITLE
Timestamp for this request is not valid for openOrders 

### ISSUE THREAD

**Issue by caohunan** [jaggedsoft/node-binance-api#3]
Hit the following error when trying to pull open Orders:

openOrders() { code: -1021, msg: 'Timestamp for this request is not valid.' }

I guess that the server side tried to compare the data.timestamp with server's time and rejected all the requests with all obsolete timestamps (time bypassed too long).

The problem here is that this API is trying to pass the client's local time. Need to consider the scenario where the client and the server are in different time zones.

**Comment by jaggedsoft** [comment]
I am in California while the servers are in Japan and it seems to be working fine. Perhaps your system time is off by a significant amount?
For windows:
![image](https://user-images.githubusercontent.com/4283360/32076214-0585643c-ba54-11e7-8d19-b53922050eda.png)

On linux: `ntpdate -s time.nist.gov`

**Comment by jaggedsoft** [comment]
Let me know if you are still having problems. This could be an issue with `recvWindow`
Unfortunately I can not join the Binance API telegram to ask as I don't have a mobile device
But I will help you test this until we can resolve it

**Comment by jaggedsoft** [comment]
The timestamp returned is a javascript `new Date().getTime()`
This value is in UTC time which is universal. So that leads me to believe your system clock might be off

**Comment by caohunan** [comment]
Hi Jon,

Thanks for your response. I am based on Sydney, Australia (GMT + 11). I believe my time is correctly set.

caof@ubuntu:~$ date
Fri Oct 27 08:44:45 AEDT 2017

Thanks,
Frank

**Comment by caohunan** [comment]
openOrders API works fine after upgrade to 0.2.1

**Comment by caohunan** [comment]
Hi Jon,

I still hit this issue when trying to cancel an open order:

cancel() response:  { code: -1021, msg: 'Timestamp for this request is not valid.' }

However, I believe my local time has been set correctly. Here is my full code:

`const binance = require('node-binance-api');
binance.options({
    'APIKEY': 'xxx',
    'APISECRET': 'xxx'
});

const MIN_ETH = 0.01;
const PRICE_UNIT = 0.00000001;
const ORDER_SYMBOL = "LINKETH";
let orderAmount = null;
let orderPrice = null;
let orderId = null;

setInterval(() => binance.bookTickers(function(ticker) {
    console.log(ticker.LINKETH);

    let currentPrice = parseFloat(ticker.LINKETH.bid);
    let currentBids = parseInt(ticker.LINKETH.bids);
    let bidPrice = currentPrice + PRICE_UNIT;
    let bidAmount = currentBids > 1000 ? 100 : 50;

    // Skip placing order if we still remain on the top
    if (orderPrice === currentPrice)
        return;

    if (orderId) {
        binance.openOrders(ORDER_SYMBOL, function(openOrders) {
            console.log("openOrders()", openOrders);
            openOrders.forEach(order => {
                binance.cancel(ORDER_SYMBOL, order.orderId, function(response) {
                    console.log("cancel() response: ", response);
                    console.log("cancel order id: ", order.orderId);
                });
            });
        });
        binance.buy(ORDER_SYMBOL, bidAmount, bidPrice, {}, function(response) {
            console.log("buy order id: " + response.orderId);
            orderPrice = bidPrice;
            orderAmount = bidAmount;
            orderId = response.orderId;
        });
    } else {
        binance.buy(ORDER_SYMBOL, bidAmount, bidPrice, {}, function(response) {
            console.log("buy order id: " + response.orderId);
            orderPrice = bidPrice;
            orderAmount = bidAmount;
            orderId = response.orderId;
        });
    }
}), 5000);`

**Comment by jaggedsoft** [comment]
Are your requests executing fast? The normal cutoff is 6.5 seconds before the timestamp becomes invalid. I will ask the binance team for more info. Thanks!

**Comment by jaggedsoft** [comment]
If you update again with `npm update` I adjusted the recvWindow. It should fix your problem
```
binance.options({
'APIKEY': 'xxx',
'APISECRET': 'xxx',
'recvWindow': 30000
});
```

**Comment by caohunan** [comment]
Still the same.
caof@ubuntu:~/workspace/binance$ npm ls node-binance-api
binance@1.0.0 /home/caof/workspace/binance
└── node-binance-api@0.2.2

Now it shows that the openOrders request is with invalid timestamp...

caof@ubuntu:~/workspace/binance$ node trade.js
{ bid: '0.00077330',
  bids: '1563.00000000',
  ask: '0.00078720',
  asks: '3155.00000000' }
buy order id: 1248489
{ bid: '0.00077331',
  bids: '100.00000000',
  ask: '0.00078720',
  asks: '3155.00000000' }
{ bid: '0.00077332',
  bids: '1638.00000000',
  ask: '0.00078718',
  asks: '3151.00000000' }
buy order id: 1248495
openOrders() { code: -1021, msg: 'Timestamp for this request is not valid.'
}

**Comment by jaggedsoft** [comment]
Could I get you to edit the `node-binance-api.js` file and modify the openOrders function?
If it works like this then it will answer several questions

```		openOrders: function(symbol, callback) {
			signedRequest(base+"v3/openOrders", {symbol:symbol, recvWindow:60000}, callback);
		},
```

and cancel

```
		cancel: function(symbol, orderid, callback) {
			signedRequest(base+"v3/order", {symbol:symbol, orderId:orderid, recvWindow:60000}, callback, "DELETE");
		},
```

**Comment by caohunan** [comment]
Hi Jon,

Yes, it is working now. Thanks a lot for your help.

Regards,
Frank
