### ISSUE TITLE
roundStep not rounding well

### ISSUE THREAD

**Issue by MauriPastorini** [jaggedsoft/node-binance-api#300]
**Title**
- bug: roundStep not rounding well
- feature: please add
- enhancement: add this to existing features

**Short Description:**
- RoundStep rounding wrong
  
**code**
```
var stepSize = 0.00001
var amount = 0.01
var newAmount = binance.roundStep(amount, step_size)

console.log(newAmount) //0.00999
```

Thank you

**Comment by jaggedsoft** [comment]
Thank you for the report
The number was not dividing properly so we added a `Math.round` call
![image](https://user-images.githubusercontent.com/4283360/47387229-63008c00-d717-11e8-8f42-8c1fea49953d.png)
`qty / stepSize` was returning an improperly rounded number

Available in v0.8.5 https://github.com/jaggedsoft/node-binance-api/commit/0a4b4922c756c12d0df5ce0c6ebc8b2c8a76bbc3
