### ISSUE TITLE
historicalTrades fromID not working.

### ISSUE THREAD

**Issue by thisisloze** [jaggedsoft/node-binance-api#303]
**Title**
- bug: historicalId not returning array of objects when using fromID

**Short Description:**
Unable to use historicalTrades to grab fromID
  
**Platform:**
- windows
- linux
- macos

**node version:**
- 9.11

**Long descrption**
binance.historicalTrades("BTCUSDT", lastId, (error, response)=>{ Is returning error.

**code**
```
binance.historicalTrades("BTCUSDT", lastId, (error, response)=>{
```

**result**
```
        return cb(null, JSON.parse(body));
               ^

TypeError: cb is not a function
    at Request._callback (C:\crypto\binance-async-bot\node_modules\node-binance-api\node-binance-api.js:110:16)
    at Request.self.callback (C:\crypto\binance-async-bot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\crypto\binance-async-bot\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\crypto\binance-async-bot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

thank you

**Comment by jaggedsoft** [comment]
`historicalTrades: function (symbol, callback, limit = 500, fromId = false)`
the parameters on this function are weird, so you must do it like this:
```js
binance.historicalTrades("BTCUSDT", (error, response)=>{
//...
}, 500, lastId);
```

**Comment by thisisloze** [comment]
`
setInterval(() => {
    if (lastId === 0) {
        console.log(tradeHistory.length)
        binance.historicalTrades("BTCUSDT", (error, response)=>{
            firstRun = false;
            console.log('FIRST GRAB')
            let h = Array.from(response);
            tradeHistory = tradeHistory.concat(h);
            //console.log(tradeHistory)
            let idlist = tradeHistory.map(x => ([x.id]));
            //console.log(idlist)
            lastId = parseInt(idlist[tradeHistory.length - 1])
            console.log(lastId)
            //console.log("historicalTrades", response);         
        });
    } else if (lastId !== 0) {
        console.log(tradeHistory.length)
        binance.historicalTrades("BTCUSDT", (error, response)=>{
            console.log('AFTER GRAB')
            let z = Array.from(response);   
            tradeHistory = tradeHistory.concat(z);
            //console.log(tradeHistory)
            let idlist = tradeHistory.map(x => ([x.id]));
            //console.log(idlist)
            lastId = parseInt(idlist[tradeHistory.length - 1])
            console.log(lastId)
            //console.log("historicalTrades", response);
        }, 500, lastId);
    }
    }, 2000);
`

**Comment by jaggedsoft** [comment]
Hmm, not sure off the top of my head
