### ISSUE TITLE
"Account has insufficient balance for requested action." - Price changing before calling marketBuy()

### ISSUE THREAD

**Issue by hugeprestigellc** [jaggedsoft/node-binance-api#304]
Hi there, I'm trying to exchange ALL my USDT for BTC using the following:

binance.marketBuy('BTCUSDT', binance.roundStep(amountToBuy, stepSize))

I'm determining the amountToBuy by getting my USDT balance and dividing it by the current BTCUSDT price from your API. So:

amountToBuy = balances['USDT'].available / price;

The marketBuy call works some times but other times I get the following message:
"Account has insufficient balance for requested action."

I think what is happening is the price of Tether is going up slightly relative to Bitcoin before I make the marketBuy() call.

So I guess my question is: what is the best way to handle this? Should I just implement some retry mechanism? Is there a way to just buy the maximum amount at market price without calculating the amount on my end? Should I just lower the amount I'm trying to buy slightly?

Any input would be much appreciated!

**Comment by jaggedsoft** [comment]
You need to calculate using the ask price not the last price (See https://github.com/jaggedsoft/node-binance-api/issues/264)

See my function balance() that I run on a timer here https://github.com/jaggedsoft/node-binance-api/blob/master/examples/balances-and-exchangeInfo.js

If you still need help let me know

**Comment by robertrookie21** [comment]
I had the same problem.  Reverting back to `return (((qty / stepSize) | 0) * stepSize).toFixed(precision);` in line 822 (node-binance-api.js) fixed the problem.

**Comment by jaggedsoft** [comment]
Interesting thank you @robertrookie21

**Comment by robertrookie21** [comment]
Hey Jon,
For example
let symbol = "MDABTC";
let quantity = 7.992;
console.log(binance.roundStep(quantity, global.filters[symbol].stepSize)); // Returns 8

**Comment by jaggedsoft** [comment]
Fixed v0.8.7 https://github.com/jaggedsoft/node-binance-api/commit/f69b783958903fc598e738f018274c6a059ac46c

**Comment by hugeprestigellc** [comment]
@jaggedsoft I'm still running into this issue unfortunately and I'm not sure I understand your solution that you mentioned in the comments above. Can you elaborate on how to get the "ask" price?

Thanks!

**Comment by jaggedsoft** [comment]
There are several functions that will return the 'ask' price. It's the lowest ask on the order book, and the actual price you can buy something for.
```js
binance.bookTickers((error, ticker) => {
  console.log("bookTickers()", ticker);
  console.log("Ask price of AMB: ", ticker.AMBBTC.ask);
});
```

@hugeprestigellc

**Comment by hugeprestigellc** [comment]
Hey @jaggedsoft apologies as I know you're busy. But after recently making the changes to use the ticker.askPrice as you suggested, I'm still occasionally encountering this issue (although it does seem to happen less now).

The issue seems to get particularly noticeable when prices are fluctuating quickly and wildly. 

Right now I'm getting it to work most of the time with a retry mechanism but it's still not 100%.

Is there something I'm missing to get this to always execute a 100% market buy order like we're able to do on Binance's website?

Thanks!

**Comment by jaggedsoft** [comment]
@hugeprestigellc I am more focused on developing for BitMax and Binance DEX at the moment

Maybe this will help: https://github.com/jaggedsoft/node-binance-api/issues/275

**Comment by freezepro** [comment]
> @hugeprestigellc I am more focused on developing for BitMax and Binance DEX at the moment
> 
> Maybe this will help: #275

Why not  Bitmex it has bigger volumes ? @jaggedsoft
