### ISSUE TITLE
Enhancement Request: get USD value of USDT

### ISSUE THREAD

**Issue by ExistentialPrime** [jaggedsoft/node-binance-api#306]
## Enhancement Request: get USD value of USDT

**Background**
- Binance only pairs their symbols up with USDT
- The recent volatility of USDT means that BTC worth 6,450 USDT may not necessary be worth $6,450
- Having the current actual value of USDT from Binance would be extremely helpful when producing valuations for users so as to allow developers to convert from coin -> USDT -> USD

**Description:**
A simple API call to get the USD value of USDT from Binance. Not sure if the official Binance api even has a call for this yet, however, as even their https://info.binance.com/en/currencies/tether info page audaciously assumes tether will always be worth $1.00 as its hardcoded in at the top. Nor does it show up anywhere in the exchange info response.

**Comment by jaggedsoft** [comment]
I believe this is outside of the scope of this library, we can get the USDT value in BTC but USD is another matter entirely. 
![image](https://user-images.githubusercontent.com/4283360/48439446-910d4500-e786-11e8-91e4-04a7852c4a26.png)
![image](https://user-images.githubusercontent.com/4283360/48439383-763ad080-e786-11e8-869d-537cad5f5e77.png)
The only way I can think to make this possible is to check the price of USDTUSD on Kraken or Poloniex

**Comment by jaggedsoft** [comment]
As soon as Binance adds Margin / Fiat then this will likely become possible and included in the library. Thank you for the suggestion

**Comment by ExistentialPrime** [comment]
Thanks for the quick response! I look forward to the feature addition if/when it makes it in. I appreciate all the great work you do keeping this package up to date!
