### ISSUE TITLE
Round step not working 

### ISSUE THREAD

**Issue by MauriPastorini** [jaggedsoft/node-binance-api#309]
Hello, I found a bug on the roundStep func:

pair of test = "BQXETH"
`newAmount = parseFloat(binanceStaticInstance.roundStep(99.21619208254788, 1)`

Error: "Cannot read property 'length' of undefined"

Thanks

**Comment by jaggedsoft** [comment]
You might have to pass a string instead.
I suppose we could add some logic to auto convert it to a string

**Comment by MauriPastorini** [comment]
Hi thank you for your answer. I tried binanceStaticInstance.roundStep("99.21619208254788", 1) and dont seem to work :/

**Comment by jaggedsoft** [comment]
Are you sure you're on the new version? I remember fixing an issue like this before

Try this instead: `.toFixed(8)`
```js
amount = 99.21619208254788
newAmount = parseFloat(binanceStaticInstance.roundStep(amount.toFixed(8), 1)
```

**Comment by MauriPastorini** [comment]
Yes I am on 0.8.7.
I am receiving the same error with that try: "Cannot read property 'length' of undefined"

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/49916364-cd71b500-fe9a-11e8-90b6-fa125328c81f.png)
for BQXETH, stepSize is `"1.00000000"`
You must pass this value (as a string) as provided by exchangeInfo
![image](https://user-images.githubusercontent.com/4283360/49916411-fb56f980-fe9a-11e8-9f73-63a3b9a24cca.png)

**Comment by MauriPastorini** [comment]
It seems that step size must be the same string that binance returns, I was parsing to float the `1.0000`, so sending `1` instead of `1.000` . 
Thanks for your help!
