### ISSUE TITLE
Limit Buy response {} order id: undefined

### ISSUE THREAD

**Issue by cassianogr** [jaggedsoft/node-binance-api#311]
Hello! 

I've got the error below, when I try use the endpoint :
 binance.buy("MITHBTC", xxxx, xxxx, {type:'LIMIT'}, (error, response) => {
                        if ( error ) return console.error(error);
                        console.log("Limit Buy response", response);
                        console.log("order id: " + response.orderId);
                      });

There's not error on content of the variable 'error' in the callback.

I try buy with other symbols, but.....:(

It Return:
Limit Buy response {}
order id: undefined

Anybody help me?

Thanks

**Comment by yosietserga** [comment]
Hi, did you tr y putting your code into useServerTime?

`binance.useServerTime(function() {
	binance.buy("MITHBTC", xxxx, xxxx, {type:'LIMIT'}, (error, response) => {
            if ( error ) return console.error(error);
                console.log("Limit Buy response", response);
                console.log("order id: " + response.orderId);
       });
});`

**Comment by jaggedsoft** [comment]
Sorry friend, if you want support from Binance you must go through https://t.me/binance_api_english

I have made several proposals for improving the API and providing better support but they have shot them down.
