### ISSUE TITLE
Randomly null ticker values and errors on calculus in async function

### ISSUE THREAD

**Issue by djumanji** [jaggedsoft/node-binance-api#314]
binance.prices((error, ticker) => {

    bug: ticker is sometimes null

Short Description:

Hello dear,

I had ever asked you a similar question and your help was very useful.

This time I'm not sure that this problem is related to your complete API or is related to a bad usage of nodejs async functions.

Unfortunately, the problem is too deep to provide you tons of code. But if you had any ideas it will be welcomed, if not don't worry about deleting this issue.

Let me explain : with an async function reseting each 15s, I'm analyzing values of 10 cryptos with the function binance.prices((error, ticker) => {}.

I have as you suggested me months ago a "throw error" to get any errors from the function,
anyway it's never returning any errors, but sometimes the "current value" is set to null in a random way. 

This problem is rare but can be very blocking. To avoid it, I just check if the "current value" is null, or not. Considering this, I also noticed calculus errors on getting stop wins and stop loss, which are sometimes randomly set to the same price of the current value...

Indeed, sometimes the main async function seems to be overloaded with parsing 10 differents cryptos and opening many of your binance functions. I can not find any logical solutions neither documentation, and I was wondering if you had ever faced a similar problem on nodejs.

I hope you understood my problem, any help will be appreciated

Platform:

    linux ubuntu

node version:

    9.11

thank you !

**Comment by djumanji** [comment]
I just go a perfect toString() example to provide you : 

2019-01-08 13:11:58
{"currency_symbol":"BNBBTC","quantity":"7.68","bought_price":"0.00162970","stop_loss":"0.00162970","stop_wins":"0.00162970","strategy":"falling_wedge"}

And obviously, the next 15s it is selling it and making me lose my trade.

**Comment by jaggedsoft** [comment]
I cannot provide any insight to this, sorry.
My only concern would be if you are making more than 5-10 requests per second then it would possibly return an empty response as you get temporarily blocked by their load balancer.
