### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by vach** [jaggedsoft/node-binance-api#32]
Tried stream over webscoket, keys are provided using this

binance.websockets.trades(['BNBBTC', 'ETHBTC'], function(trades) {
    let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
    console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});

no output

tried getting an http call done

binance.trades("SNMBTC", function(trades, symbol) {
    console.log(symbol+" trade history", trades);
});

output was 

SNMBTC trade history { code: -1021,
  msg: 'Timestamp for this request was 1000ms ahead of the server\'s time.' }

great lib

**Comment by jaggedsoft** [comment]
#1 - binance was down for over an hour
#2 - fix your system time
#3 - quit bitching
