### ISSUE TITLE
DepthMarket connection issue

### ISSUE THREAD

**Issue by LuckStock** [jaggedsoft/node-binance-api#321]
Oh, bugs aren't supported by Binance?
Well, may be someone has a fix for this bug.
Connecting to Binance API method called DepthMarket via websockets providing a list of symbols to watch.
It's working for some time, then later it starts to throw errors that can't be caught:
`"CombinedStream: Parse error: Cannot read property \'messageQueue\' of undefined"`

This error remains through all previous and latest versions of node-binance-api and I have no idea how to resolve it.
Any help will be appreciated!

**Comment by jaggedsoft** [comment]
Maybe someone from the community can help (my time is focused on other things)
I would suggest attempting to connect to your websocket individually, instead of passing an array. See if it works then. It also might be possible that CombinedStream can only accept a maximum number of values.

**Comment by jaggedsoft** [comment]
The other thing to mention is that if you are connecting to too many symbols at once, you might be temporary banned for a short amount of time. To prevent this wait 300ms between calls, especially for market depth or chart history.

**Comment by LuckStock** [comment]
I doubt it's a ban, it's some problem in module code.
The average number of symbols being watched is 20.
What is the best way to watch for price changes of 20-100 symbols in real time including the volumes if there is no fix to the method above?

**Comment by jaggedsoft** [comment]
I use the trade streams https://github.com/jaggedsoft/node-binance-api/blob/master/examples/experiments.js

bookTickers https://github.com/jaggedsoft/node-binance-api/blob/master/examples/standalone.js

connect to all endpoints example https://github.com/jaggedsoft/node-binance-api/blob/master/examples/subscribe-to-all.js

**Comment by LuckStock** [comment]
Thank you, I will check those methods shortly!

**Comment by jaggedsoft** [comment]
Good luck
And like I said before try connecting individually without array syntax:
i.e, change `['BNBBTC']` to `'BNBBTC'`
```js
binance.websockets.depth(['BNBBTC'], (depth) => {
  let {e:eventType, E:eventTime, s:symbol, u:updateId, b:bidDepth, a:askDepth} = depth;
  console.log(symbol+" market depth update");
  console.log(bidDepth, askDepth);
});
```
This will cause a direct socket connection instead of using combinedStream

**Comment by LuckStock** [comment]
And in this case, watching for 20-100 symbols won't be a subject to a temporary ban from Binance?

**Comment by jaggedsoft** [comment]
Nope you can connect to all of them at once, I think there's over 400 market pairs now

**Comment by kitt-th** [comment]
the error is in your own code somewhere - I'm presuming you're running Javascript and Node here. I get the same error from time to time when trying to reference a variable that is undefined at the time.

unfortunately node cannot tell you which line number of your code is at fault. you have to check all code that references messageQueue and go from there. Hope that helps ;)
