### ISSUE TITLE
Cancel function isn't the same?

### ISSUE THREAD

**Issue by kirkins** [jaggedsoft/node-binance-api#322]
Hi I'm confused about the instructions.

According to the docs there should be a `cancel` function and `cancelOrders` but when I console log my binance object I only have one called `cancelOrder`:

![screenshot from 2019-02-03 19-09-59](https://user-images.githubusercontent.com/9503662/52184901-5b0cb980-27e7-11e9-9f7d-9e7c6c8acc46.png)

My package.json has `"binance-api-node": "^0.8.1",` am I using the same library?

**Comment by jaggedsoft** [comment]
nope, binance-api-node is a different project
https://github.com/HyperCubeProject/binance-api-node
