### ISSUE TITLE
Question about the test option

### ISSUE THREAD

**Issue by Darksoulsong** [jaggedsoft/node-binance-api#323]
Sorry, I know you're working in other projects right now, but I have a question that perhaps you can answer with little effort:

Does the test option covers the selling of assets? I mean, If I put a sell order with test = true, will it try to sell my assets for real or is it going to fake a selling? Moreover, where can I get some examples of the selling api response?

**Comment by jaggedsoft** [comment]
The test functionality, implemented by binance, does nothing but return an empty response. 

View the "response full" here:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-endpoints
