### ISSUE TITLE
opening new websocket on each subscription?

### ISSUE THREAD

**Issue by waterdrop01** [jaggedsoft/node-binance-api#326]
Hello there,

It seems a new websocket connection is opened on each subscription.

I was just wondering if my understanding of the code is correct, and if you could provide a short rational behind this decision? Why not reusing the same websocket connection?

Many thanks!!

**Comment by jaggedsoft** [comment]
The preferred method of making socket connections is using a combinedStream, which happens automatically if you pass an array, like this:

```js
binance.websockets.trades(['BNBBTC', 'ETHBTC'], (trades) => {
  let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
  console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
```

Lately I am too busy to improve the documentation, it could be much better. But I have some examples on how you can do this even without using my library here:

Plain javascript: https://github.com/jaggedsoft/node-binance-api/blob/master/examples/experiments.js

Using this library: https://github.com/jaggedsoft/node-binance-api/blob/master/examples/subscribe-to-all.js
