### ISSUE TITLE
binance.marketBuy does not complete

### ISSUE THREAD

**Issue by pfeiflelukas** [jaggedsoft/node-binance-api#328]
Hi Everyone,

I am having issues getting my marketBuy working. It is just returning

```
Market Buy Response = {} 
Order ID = undefined
```

I have enabled the below under the initial setup

```
  useServerTime: true,
  recvWindow: 60000, 
  verbose: true,
  test: false
```

I am calling the function like so

```
        binance.marketBuy("BTCETH", BTC_Balance, (error, response) => {
          if(response.status == 'FILLED' || response.status == 'Filled' || response.status == 'filled') {
            tradeCompleted = true;
            ETH_Balance = response.executedQty;
          }
          if(error) {
            log('failed market trade buy on BTCETH for Trader 1: ' + error + '\n', 'failedtradelog.log')
          }
        });
```

I also tried copying and pasting the default marketTrade in examples but the error continues.

I recently saw that another setup function might be required but when i added it the result was the same.

```
  function binanceInfo() {
    binance.exchangeInfo((error, data) => {
    })
  }
```

All other API calls seem to work (haven't tried other buy methods).

I checked under the Binance and the API key/secret i created allows trading.

Does anyone have a solution to this?

Thanks

**Comment by pfeiflelukas** [comment]
I forgot to add the output from the log taken:

`
failed market trade buy on BTCETH for Trader 1: [object Object]
`

**Comment by pfeiflelukas** [comment]
even the most basic buy option fails.

`
binance.marketBuy("BNBUSDT", 0.2);
`

returns

`[ 'BUY(BNBUSDT,0.2,0) ', {} ]`

but fails to do the trade in Binance

**Comment by jaggedsoft** [comment]
Looks like you left `test` mode set to true

Can't tell you much more unless you fix your logging
`failed market trade buy on BTCETH for Trader 1: [object Object]`

Should print the object details, not just that it's an object. Maybe switch to `util.inspect`

**Comment by bmino** [comment]
I agree, it appears you have the test mode set to true. This will result in empty objects being returned.

Paste something like this right before your code that performs the market buy
```
const isTestModeEnabled = binance.getOption('test');
console.log(isTestModeEnabled);
```

**Comment by Turbine1991** [comment]
> I agree, it appears you have the test mode set to true. This will result in empty objects being returned.
> 
> Paste something like this right before your code that performs the market buy
> 
> ```
> const isTestModeEnabled = binance.getOption('test');
> console.log(isTestModeEnabled);
> ```

I'm having the same issue, but with selling. It returns output and then an empty object.

Test mode is "False". It used to work a few months ago.

**Comment by jestersimpps** [comment]
+1

**Comment by e4drcf** [comment]
I've got same issue with sell and buy methods of binance object.
response is {}
testMode is disabled.
please help
