### ISSUE TITLE
Trying to get Minute Candle Close For all symbols

### ISSUE THREAD

**Issue by amigoni** [jaggedsoft/node-binance-api#329]
I'm trying to pull all the Kline Candle Close for all symbols. I tried using the Websocket Chart endpoint, but I am getting sporadic results. 

- First there seems to be a limit of 200 symbols on it. 
- Second the data coming through seems to be sometimes empty for a symbol.

Has anyone found a way to get All Symbols Kline at a close of a timeperiod? Or is there a rest call that will allow me to do that instead of calling them one by one? I can't seem to find it. I see there are references to v1 API but unfortunately can't find official docs on it. 

Thanks in advance.

**Comment by bmino** [comment]
Candlesticks are generally useful to see trends across a time period for a single ticker. If you are only interested in the current prices, `/api/v3/ticker/price` will serve you ideally.

I might recommend against using websockets if you only want the closing price for a given time period as they are best suited for obtaining live data.

Based on your description you seem to want the closing price of some candlestick size at a given point during the day. This is only accomplished by looping through all the tickers you want and calling the `/api/v1/klines` endpoint on each ticker as shown in pseudo-code below. Replace the 00000's with the timestamp in ms of your desired time frame.

```javascript
function handlerFn(error, data, symbol) {
    if (error) return;
    // TODO: handle the kline data
}

tickers.forEach((ticker) => {
    binance.candlesticks(ticker, "5m", handlerFn, { limit: 1, startTime: 00000000, endTime: 0000000 });
});
```
