### ISSUE TITLE
data.balances is not iterable

### ISSUE THREAD

**Issue by matty8444** [jaggedsoft/node-binance-api#34]
I am trying to return my account balances using the provided code:

binance.balance(function(balances) {
	console.log("balances()", balances);
});

I am getting the below error:

TypeError: data.balances is not iterable

**Comment by jaggedsoft** [comment]
Thanks for the report! I am looking in to this

**Comment by matty8444** [comment]
Hi it was my mistake. My api secret was incorrect. Sorry!
