### ISSUE TITLE
Allow deletion of depth cache book data

### ISSUE THREAD

**Issue by evan-coygo** [jaggedsoft/node-binance-api#345]
If a user decides they no longer want to keep a depth cache for a market (`websocket.depthCache()`) they can terminate that connection, but there's no way to delete the cached data from memory. 

Exposing a method `binance.websocket.clearDepthCache(market)` would be helpful for this which would run `delete Binance.depthCache[market]`

**Comment by jaggedsoft** [comment]
Thank you for your contribution!
https://github.com/jaggedsoft/node-binance-api/pull/346
was merged and a new release will be issued soon

**Comment by evan-coygo** [comment]
@jaggedsoft when do you think you'll be getting this released?

**Comment by evan-coygo** [comment]
@jaggedsoft just checking up again, we're blocked by this before our next release. please let me know if there's anything we can do to help get this out!

**Comment by jaggedsoft** [comment]
@ `v0.9.5`
