### ISSUE TITLE
Margin Trading

### ISSUE THREAD

**Issue by jaggedsoft** [jaggedsoft/node-binance-api#349]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md

**Comment by kitt-th** [comment]
interested

**Comment by guygberg** [comment]
Very interested to have this

**Comment by vitaly-t** [comment]
It would be something very similar to #367

**Comment by jsappme** [comment]
any update on the oco margin order development?

**Comment by jaggedsoft** [comment]
@jsappme I'm not sure anyone is working on anything at the moment. My only plans (later when I have time) are to work on a clean async javascript api for Binance Futures

**Comment by jaggedsoft** [comment]
I think we currently have support for margin, everything except OCO
