### ISSUE TITLE
Is there an easy way to get the average price of last month?

### ISSUE THREAD

**Issue by mike34562** [jaggedsoft/node-binance-api#350]
Is there an easy way to get the average price for any coin of the last week, month or year?

**Comment by jaggedsoft** [comment]
Yeah you can request daily candles for your period and take the average (for week, month, year, etc)

```js
    const sum = arr => arr.reduce( ( a, b ) => a + b, 0 );
    const mean = arr => sum( arr ) / arr.length;
```
