### ISSUE TITLE
differences with Binance's fork

### ISSUE THREAD

**Issue by FiretronP75** [jaggedsoft/node-binance-api#354]
Most projects forked by Binance are a little behind the originals. But with this one, Binance's fork is 25 commits ahead and 29 commits behind the original, which implies they actually took another development path. Did they really diverge this much? Or is it more an illusion?

**Comment by jaggedsoft** [comment]
They're the same, just messed up a large commit in the past I think

**Comment by jaggedsoft** [comment]
Basically I use jaggedsoft as the development version and whenever changes are made I push them to release and fork them to binance
Stable tested code goes to the binance repo

**Comment by FiretronP75** [comment]
Thanks!
