### ISSUE TITLE
Placing OCO and watching for websocket updates

### ISSUE THREAD

**Issue by gunar** [jaggedsoft/node-binance-api#357]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade

https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#order-update

**Comment by Dylan-Phoon** [comment]
Is this a new feature that's going to be implemented? Would be really useful. Polling the api is not a very good solution atm...

**Comment by gunar** [comment]
I've got it working with a patch. The code is ugly but works. If we're willing I could send a PR, we could merge it, and refactor it later.

**Comment by jaggedsoft** [comment]
Thanks friend! This week is really busy for me but I will try my best
