### ISSUE TITLE
calling balance generates this error

### ISSUE THREAD

**Issue by fjafferi** [jaggedsoft/node-binance-api#36]
```
binance.balance(function(balances) {
});

```

> 
> node-binance-api/node-binance-api.js:220
>                 for ( let obj of data.balances ) {
>                                       ^
> 
> TypeError: data.balances is not iterable
>     at balanceData (node-binance-api/node-binance-api.js:220:25)
>

**Comment by jaggedsoft** [comment]
I will fix this. In the mean time please make sure your API key is correct

**Comment by allawitte** [comment]
On 
binance.balance((error, balances) => {
  console.log("balances()", balances);
});
I get an object balanceData error with empty content
I checked my API key. secret key - all correct, I use   useServerTime: true, 

What could be the problem?

**Comment by jaggedsoft** [comment]
problem is because useServerTime takes a second to kick in sometimes
For you this method of serverTime should work, this will allow it to fire on startup

```js
binance.useServerTime(() =>
	binance.balance((error, balances) => {
	  if ( error ) return console.error(error.body);
	  console.log("balances()", balances);
	  if ( typeof balances.BTC !== "undefined" ) console.log("BTC balance: ", balances.BTC.available);
	  if ( typeof balances.ETH !== "undefined" ) console.log("ETH balance: ", balances.ETH.available);
	})
);
```

**Comment by allawitte** [comment]
Thank you very much!
It works now!

Best, Alla


Web-site: http//allawitte.nl

 

----- Reply to message -----
Subject: Re: [jaggedsoft/node-binance-api] calling balance generates this error (#36)
Date: 5 сентября 2018 г., 22:04:04
