### ISSUE TITLE
Btc pairs for alt_coins

### ISSUE THREAD

**Issue by breakimpossible** [jaggedsoft/node-binance-api#362]
I need to get btc pairs for alt_coins only btc pairs not bnb & eth pairs 
This code for btc & bnb & eth & usdt pairs for alt_coins I need to make it for btc pairs for alt_coins only

https://github.com/jaggedsoft/node-binance-api/blob/master/examples/experiments.js

**Comment by jaggedsoft** [comment]
Put this after line 8
```js
if ( obj.symbol.endsWith('BTC') ) continue;
```

**Comment by breakimpossible** [comment]
@jaggedsoft last question please. 
How can I get 24h volume with this code ☝️🌷.

**Comment by jaggedsoft** [comment]
@breakimpossible 

```js
const binance = require('node-binance-api')();
binance.prevDay(false, (error, prevDay) => {
	for (let obj of prevDay) {
		let symbol = obj.symbol;
		if (!symbol.endsWith('BTC')) continue;
		console.log(`${symbol} volume:${obj.volume} change: ${obj.priceChangePercent}%`);
	}
});
```

**Comment by mrbreaks** [comment]
thank you so much my bro.

**Comment by breakimpossible** [comment]
Thank you for your help ❤️.

**Comment by Stevennabile** [comment]
@jaggedsoft 
One question please
I need real 24h volume for alt_coins but in btc

**Comment by jaggedsoft** [comment]
@Stevennabile change "volume" to "quoteVolume"

**Comment by Stevennabile** [comment]
It's work's thanks
But I can't get 24h volume for alt_coins in btc with price using this code in one massage. 
https://github.com/jaggedsoft/node-binance-api/blob/master/examples/experiments.js
Can I get price change % and 24h in btc and price in the same massage. 🤨

**Comment by jaggedsoft** [comment]
Yes this endpoint returns tons of extra data now that it didn't before https://api.binance.com/api/v1/ticker/24hr

![image](https://user-images.githubusercontent.com/4283360/67810509-03ac2900-fa9b-11e9-9d36-e3a72f5bbf25.png)

```js
const binance = require('node-binance-api')();
binance.prevDay(false, (error, prevDay) => {
	for (let obj of prevDay) {
		let symbol = obj.symbol;
		if (!symbol.endsWith('BTC')) continue;
		console.log(`${symbol} ${obj.quoteVolume} BTC ${obj.priceChangePercent}% @ ${obj.lastPrice}`);
	}
});
```

**Comment by Stevennabile** [comment]
@jaggedsoft I forgot to ask you can I buying and selling activities from market trade with the last code you sent it ❤️

**Comment by Stevennabile** [comment]
@jaggedsoft I forgot to ask you can I get buying and selling activities from market trade with the last code you sent it ❤️.
I need to build a tracking bot that give me buying and selling alerts with the price and volume and price changes %. 
I'm a beginner programmer 😅.

**Comment by Ourderv** [comment]
@jaggedsoft I have the same question of @Stevennabile ☝️
I need to build a a code that track a buy and sell activities for only btc pairs for alt_coins for example give me this 👇
LTC/BTC
45 btc selling now 
At price 0.22
Volume: 400 btc
Price change: 20%
Last activity: 2 days ago
Can you help me please ❤️

**Comment by mrbreaks** [comment]
@jaggedsoft can i get price change % but in WebSocket 
like the code below but add price change % between the part console.log(data.s+' price: '+data.p+' quantity '+xx);
this code 
const ws = new WebSocket('wss://stream.binance.com:9443/stream?streams='+streams.join('/'));
  ws.on('message', function(payload) {
    let json = JSON.parse(payload), stream = json.stream, data = json.data;
    var xx = data.p*data.q;
    if ( data.e == 'aggTrade' ) {
      console.log(data.s+' price: '+data.p+' quantity '+xx);
    } else console.log(stream, data);
