### ISSUE TITLE
depthCache with >205 currencies results in rate limit

### ISSUE THREAD

**Issue by bgold0** [jaggedsoft/node-binance-api#365]
Anything less then or equal to 205 currencies works but anything more you get the following error:

>   body: '{"code":-1003,"msg":"Too many requests; current limit is 1200 requests per 1 MINUTE. Please use the websocket for live updates to avoid polling the API."}' }

```
binance.websockets.depthCache([], function(symbol, depth) {

})
```

To be honest I'm not sure how it's reaching 1200 requests but I think this happens when you get the snapshot of an order book to start the websocket when doing a request like this: `path: '/api/v1/depth?symbol=SOMETHING&limit=500',`

**Comment by tymmesyde** [comment]
Why is this issue closed ?

**Comment by encloinc** [comment]
Yeah why is this closed??

**Comment by jaggedsoft** [comment]
The user must have read previous closed issues like this one https://github.com/jaggedsoft/node-binance-api/issues/351#issuecomment-630570530

If you're connecting to lots of depthCache or chart endpoints at once, you probably need to stagger them with a delay between connections, or use a smaller limit for each depthCache.
