### ISSUE TITLE
Code that track buy & sell activities with price & volume

### ISSUE THREAD

**Issue by Ourderv** [jaggedsoft/node-binance-api#366]
I need to build a a code that track a buy and sell activities for only btc pairs for alt_coins for example give me this point_down
LTC/BTC
45 btc selling now
At price 0.22
Volume: 400 btc
Price change: 20%
Last activity: 2 days ago
Can you help me please ❤️

**Comment by Ourderv** [comment]
@jaggedsoft please answer me I will give you anything you need but help me please. ❤️

**Comment by jaggedsoft** [comment]
What have you tried so far?
