### ISSUE TITLE
Depth cache out of sync

### ISSUE THREAD

**Issue by mstijak** [jaggedsoft/node-binance-api#37]
Depth cache occasionally goes out of sync. This started happening today (1/5/2018). Binance did some upgrades last night and it seems that websocket is no longer reliable.

Any clues what is happening?

I just wanted to report the problem. Feel free to close the issue if you feel it's not related to the library.

**Comment by jaggedsoft** [comment]
#33 Others are reporting this same issue. Unfortunately my time is very limited this week but I will get to the bottom of it as soon as I can
Thank you for the report

**Comment by mstijak** [comment]
I think I figured it out. If multiple symbols are used, `reconnect` function resubscribes all symbols.
If four symbols are used, on reconnect 16 symbols will be resubscribed. 
I believe this causes #33 too.
The fix is easy. Would you accept a PR?

```
let reconnect = function() {
     if ( options.reconnect ) depthCacheFunction(symbols, callback);
};
```

**Comment by jaggedsoft** [comment]
Yes. Very clever. Thank you for this!!

**Comment by jaggedsoft** [comment]
Pushing an update now. Thank you!!

**Comment by mstijak** [comment]
Glad to help! 🎉
