### ISSUE TITLE
How to use bollinger indicator by API?

### ISSUE THREAD

**Issue by mfidelli** [jaggedsoft/node-binance-api#373]
Hello,

I have two doubts

1° - Is there any information available on the indicators that are in the APP?
Example: Bollinger

2° - Is there a way to buy or sell iqual of the application, using the percentage?
example: sell 100%

thanks

**Comment by jaggedsoft** [comment]
If you have the PECL trader library installed then bollinger calculations are relatively easy https://www.php.net/manual/en/function.trader-bbands.php

**Comment by mfidelli** [comment]
> Se você possui a biblioteca de traders PECL instalada, os cálculos de bollinger são relativamente fáceis https://www.php.net/manual/en/function.trader-bbands.php


I will check this option thanks

but through the Binance API they don't provide this information?

**Comment by jaggedsoft** [comment]
This is the library I use https://github.com/anandanand84/technicalindicators
