### ISSUE TITLE
I can not get websockets endpoint

### ISSUE THREAD

**Issue by Kuzmich100kM** [jaggedsoft/node-binance-api#382]
Use this code:
```js
// List all endpoints
let endpoints = binance.websockets.subscriptions();
for ( let endpoint in endpoints ) {
	console.log(endpoint);
	//binance.websockets.terminate(endpoint);
}
```

And don’t get anything, absolutely nothing.
If I try to get the whole object through an async function, always get { }

**Comment by jaggedsoft** [comment]
where is your callback function? all the examples are given like this:
```js
binance.websockets.miniTicker(markets => {
  console.log(markets);
});
```

if you don't like this library then try a different one https://github.com/Ashlar/binance-api-node

**Comment by jaggedsoft** [comment]
i'm not sure if you can terminate a websocket that's been connected through a CombinedStream. So that means if you plan on terminating the socket you have to connect to it individually instead of connecting to multiple websockets at once

**Comment by Kuzmich100kM** [comment]
> where is your callback function? all the examples are given like this:

I use code from this
[https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#terminate-websocket-connections](url)

I tried to create a callback function, as in your example above - it does not work.
```js
binance.websockets.subscriptions(endpoints => {
	for (let endpoint in endpoints) {
		console.log(endpoint)
	}
})
```

> f you don't like this library then try a different one

Oh no, I really like your library :-)

**Comment by jaggedsoft** [comment]
thank you :) so the only thing that comes to mind is that you might be calling the code to check the currently connected subscriptions too fast, maybe we need to add a slight delay. if it still doesnt work then we will need to go back to the drawing board

maybe try something like this:
```js
// Connect to any websocket immediately
binance.websockets.miniTicker(markets => {
  console.log(markets);
});

function check_sockets() {
    binance.websockets.subscriptions(endpoints => {
        //console.info(endpoints);
        for (let endpoint in endpoints) {
            console.log(endpoint)
        }
    });
}
setInterval(check_sockets, 999);
```

there is also an advanced example for connecting to the websocket endpoints manually, but we'd have to switch it from a CombinedStream to a single connection. this is provided for reference only https://github.com/jaggedsoft/node-binance-api/blob/master/examples/experiments.js

**Comment by Kuzmich100kM** [comment]
> ```js
> // Connect to any websocket immediately
> ```

Sorry, this code return miniTicker, but does not show in console endpoints too.

**Comment by Kuzmich100kM** [comment]
Help me please. 
How i can destroy binance.websockets.prevDay for All symbols? 
I tried to see the endpoints, but I didn’t succeed, your responce above does not work.
Where is the error in this code?
```js
const Binance = require("node-binance-api")
const binance = new Binance().options({})

binance.websockets.prevDay(false, (error, prevDay) => {
	//console.log(prevDay)
})

function check_sockets() {
	binance.websockets.subscriptions(endpoints => {
		console.info(endpoints)
		for (let endpoint in endpoints) {
			console.log(endpoint)
			//binance.websockets.terminate(endpoint);
		}
	})
}
setInterval(check_sockets, 999)

```

**Comment by jaggedsoft** [comment]
i haven't tested this and i'm not sure why it wouldn't be showing up in `endpoints`
but the same effect should be able to be achieved by terminating it manually (as long as it was connected by itself and not using a CombinedStream)
you might also turn `verbose: true` on in your options when instantiating because it'll tell you if it's just reconnecting the websocket right away. you have to turn auto reconnect off before terminating something

```js
binance.websockets.terminate("!ticker@arr");
```

**Comment by jaggedsoft** [comment]
we need to add these options to the documentation:
```js
const Binance = require('node-binance-api');
const binance = new Binance().options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  log: console.log,
  verbose: true
});
```

**Comment by Kuzmich100kM** [comment]
Jaggedsoft, thanks for responce.
verbose: true in options is work, but this does not return anything, only writes to the consoleI. And after a while: Terminating inactive / broken WebSocket: undefined. I can’t understand how this can be used in the code. I can only look with my eyes and hands :)

![Screenshot_4](https://user-images.githubusercontent.com/46998842/76074581-3f548380-5fa4-11ea-8a78-4535a08a52ab.jpg)

And the code with   
```js
binance.websockets.subscriptions(endpoints => {
		console.info(endpoints)}
``` 
 did not start

**Comment by Kuzmich100kM** [comment]
binance.websockets.terminate  - It also works very strange. It writes in console that terminated but continues to work.

This full code:
```js
const Binance = require("node-binance-api")
const binance = new Binance().options({
	APIKEY: "<key>",
	APISECRET: "<secret>",
	log: console.log,
	verbose: true,
	reconnect: false,
})

binance.websockets.prevDay("DATABTC", (error, prevDay) => console.log(prevDay))

setTimeout(() => binance.websockets.terminate("databtc@ticker"), 5000)
```

This is what I get in the console:
![Screenshot_3](https://user-images.githubusercontent.com/46998842/76075371-9575f680-5fa5-11ea-8c4d-feaec7427372.jpg)

**Comment by bmino** [comment]
Looks like you've done some good research here! I tried to replicate your issue and could not. Is this still happening for you?

I ran your snippet of code against version `0.11.4` of the API and it executed as expected
