### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by CryptoTimp** [jaggedsoft/node-binance-api#384]
Trying to call a futures account call via futures api. Keys are in place but receive this error when using 
console.info( await binance.futuresAccount() );

**Comment by jaggedsoft** [comment]
I cannot reproduce this error

1. Make sure you're wrapping your software within an async function:
```js
( async () => {
    // Example code here

} )();
```

2. Make sure you have the right version of the library installed `npm ls node-binance-api`
