### ISSUE TITLE
Missing lastUpdateId in depth

### ISSUE THREAD

**Issue by mnj93** [jaggedsoft/node-binance-api#387]
I'm trying to maintain order book locally using Binance differential order book updates.
For that, I will need `lastUpdateId`  returned by depth snapshot so that I can ignore updates older than that specific id but current depth function only returns an object containing `ask` and `bids`.  

Following is code snippet for reference: 

```
binance.depth('BTCUSDT', function(depth, symbol){
      console.log(depth) // {ask, bids}
      console.log(symbol) // BTSUSDT
});
```

If needed I can raise the PR to return `lastUpdateId`.

**Comment by jaggedsoft** [comment]
the WebSocket specification handles lastEventUpdateId and related fields for you automatically and also returns lastUpdateId. The function for this is depthCache. if you would like to send a pull request to update the /depth endpoint I think that might be a good idea. Thank you!

**Comment by mnj93** [comment]
![image](https://user-images.githubusercontent.com/20276545/75765561-b6500900-5d65-11ea-8cf9-f988bc52d659.png)

I've just noticed after forking your repo that it's already there as you can see in the above image. 
I was using an older version earlier so that's why it was missing. Sorry about this.
