### ISSUE TITLE
Cannot see/log the errors

### ISSUE THREAD

**Issue by VisionTrader** [jaggedsoft/node-binance-api#388]
Hi,

The websocket is working fine, but i tried to create errors to log them for long term troubleshooting.
In this process, i was unable to log any error in any way. 
I am just trying to subscribe to one symbol using the websocket connection. I disconnected the network, i entered a wrong symbol etc but i receive no error in the console.
I configured in options:
  log: log => {
    console.log(log); 
  }
I checked your code and you are logging errors:
Binance.options.log('WebSocket error: ' + this.endpoint +
            (error.code ? ' (' + error.code + ')' : '') +
            (error.message ? ' ' + error.message : ''));
What am i doing wrong?
Shouldn't i see reconnection messages or an error if the subscription failed?

Thank you!

**Comment by jaggedsoft** [comment]
I think it works like this. we should probably add this to the documentation. cheers

```js
const Binance = require('node-binance-api');
const binance = new Binance().options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  log: console.log,
  verbose: true
});
```

**Comment by VisionTrader** [comment]
Thank you very much for your reply. It is fine now. 
I will close the case.
Have a nice day!
