### ISSUE TITLE
FuturesPrice reduce problem.

### ISSUE THREAD

**Issue by mehmetuken** [jaggedsoft/node-binance-api#394]
https://github.com/jaggedsoft/node-binance-api/blob/451573827b17e4a4280652a4400cffaec9dd8f5a/node-binance-api.js#L2265
this line wrong result because reduce not pass empty object
data.reduce( ( out, i ) => ( ( out[i.symbol] = i ), out ), {} ) like this

`{
  symbol: 'BTCUSDT',
  price: '5489.13',
  ETHUSDT: '128.60',
  BCHUSDT: '174.17',
  XRPUSDT: '0.1554',
  EOSUSDT: '2.021',
  LTCUSDT: '36.41',
  TRXUSDT: '0.01014',
  ETCUSDT: '4.764',
  LINKUSDT: '2.420',
  XLMUSDT: '0.03912',
  ADAUSDT: '0.02787',
  XMRUSDT: '36.17',
  DASHUSDT: '49.93',
  ZECUSDT: '27.02',
  XTZUSDT: '1.761',
  BNBUSDT: '10.467',
  ATOMUSDT: '1.765',
  ONTUSDT: '0.3430',
  IOTAUSDT: '0.1288',
  BATUSDT: '0.1288',
  VETUSDT: '0.002640',
  NEOUSDT: '6.058',
  QTUMUSDT: '1.218',
  IOSTUSDT: '0.002424'
}
`

result out like this.

**Comment by jaggedsoft** [comment]
Thank you very much
