### ISSUE TITLE
Can't place post-only futures orders

### ISSUE THREAD

**Issue by Xodetaetl** [jaggedsoft/node-binance-api#396]
It seems the timeInForce parameter is hard-coded to 'GTC'. Post-only would be 'GTX' but we can't pass it. Or other values, for that matter.

in futuresOrder:
https://github.com/jaggedsoft/node-binance-api/blob/f8aca0f4cb4cc332f307dbc98193ccce5147fdad/node-binance-api.js#L362

**Comment by jaggedsoft** [comment]
Thank you very much for your contribution!
https://github.com/jaggedsoft/node-binance-api/commit/4cdba133021429c01bcddbc5fd1e1f0e2d577a9a

A release will be issued soon. If you need it sooner just let me know and I'll publish it ASAP

**Comment by jaggedsoft** [comment]
fixed my mistake https://github.com/jaggedsoft/node-binance-api/commit/86f4ab41cd5062fd5a21dd6efbe3ad0a7a2cc156

**Comment by Xodetaetl** [comment]
> Thank you very much for your contribution!
> [4cdba13](https://github.com/jaggedsoft/node-binance-api/commit/4cdba133021429c01bcddbc5fd1e1f0e2d577a9a)
> 
> A release will be issued soon. If you need it sooner just let me know and I'll publish it ASAP

Np, I can wait for the release. Thanks!
