### ISSUE TITLE
 binance.futuresPrices() always returns "Invalid API Key" error

### ISSUE THREAD

**Issue by AlberErre** [jaggedsoft/node-binance-api#399]
Just noticed that  `binance.futuresPrices()` method is always returning `Invalid API Key`. Even when the API Key is valid and works correctly for other methods.

**Comment by AlberErre** [comment]
I figure it out thanks to https://github.com/jaggedsoft/node-binance-api/issues/367

@jaggedsoft looks like the documentation (`.README`) is not updated. The correct initialization, using `options`, was deleted on this commit https://github.com/jaggedsoft/node-binance-api/commit/451573827b17e4a4280652a4400cffaec9dd8f5a

**Comment by jaggedsoft** [comment]
hmm it should work the same either way but I'll test it, thanks for bringing it to my attention. let me know if there's anything you want me to work on next

**Comment by jaggedsoft** [comment]
It's because I didn't publish my changes to npm. whoops. cheers friend!

**Comment by AlberErre** [comment]
Perfect! cheers 🚀
