### ISSUE TITLE
info on candles

### ISSUE THREAD

**Issue by thaison316** [jaggedsoft/node-binance-api#40]
I tried everywhere but can't seem to find what this means on the candle.  can someone help me?

what do these represent in a candle:

assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored

thanks

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams
assetVolume is the amount of volume of the base asset, if its the BNB_BTC pair, i believe this is BTC
theres also `volume` which is the actual asset, such as BNB
buyAssetVolume this is the amount of BNB purchased in buy volume only
buyBaseVolume this is the amount of BTC purchased in buy volume only

hopefully you can figure it out from here, sorry if i got something backwards
