### ISSUE TITLE
sell and buy volume

### ISSUE THREAD

**Issue by alperasan** [jaggedsoft/node-binance-api#400]
hi there i wanna ask you there how can we seperete an 1 hour volume for sell volume and buy volume ? if you help me i ll be soo glad have a nice day.

**Comment by jaggedsoft** [comment]
```js
    const Binance = require( 'node-binance-api' );
    const binance = new Binance();

    binance.candlesticks( "BTCUSDT", "1h", ( error, ticks, symbol ) => {
        let last_tick = ticks[ticks.length - 1];
        let [time, open, high, low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume] = last_tick;
        let perc = Number( buyBaseVolume ) / Number( volume ) * 100;
        console.info( `${symbol}: ${close} buyVolume: ${buyBaseVolume} of ${volume}. demand: ${perc.toFixed( 2 )}%` );
    }, {limit: 500, endTime: 1514764800000} );
```

**Comment by alperasan** [comment]
jaggedsoft how can we do it at python ? can you help me about it  ?

**Comment by jaggedsoft** [comment]
No this is the javascript library. Ask in https://github.com/sammchardy/python-binance or https://t.me/binance_api_english

You can also do your own web request to get the json data directly from binance by reading their api docs

**Comment by alperasan** [comment]
thanks alot have a nice day.
