### ISSUE TITLE
Random EPROTO error

### ISSUE THREAD

**Issue by Rexbas** [jaggedsoft/node-binance-api#412]
Hi,

I have this piece of code:

```
let seconds = 0;
setInterval(async () => {
	const balances = await binance.futuresBalance().catch(e => {console.log("in balances " + e);});
	const info = await binance.futuresExchangeInfo().catch(e => {console.log("in info " + e);});
	
	console.log("magic for s = " + seconds);
	
	
	seconds += 1;
}, 1000);
```
The output for this code is:
```
magic for s = 0
magic for s = 1
in balances Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

magic for s = 2
magic for s = 3
magic for s = 4
in info Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

magic for s = 5
in balances Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

magic for s = 6
in balances Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

in info Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

magic for s = 7
magic for s = 8
in balances Error: write EPROTO 1995635152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 80

```

As you can see I am getting EPROTO errors. Until yesterday everything was working fine. This is really annoying because sometimes it looks like the program is working fine but then after a while these EPROTO errors appear and when they do appear they will usually keep coming for some time. Which makes my program unreliable. Also it does not look like there is a pattern.

I tested on Node v12.16.2 and v13.12.0 for both Raspbian and Windows 10.

I have no idea what is causing this error so I hope someone can help me.

**Comment by Rexbas** [comment]
It appears that this issue resolved itself. I have not received any errors for some time now. Nonetheless, I created a try-retry function so if it ever happens again it will simply try again and filter the errors out.

**Comment by jaggedsoft** [comment]
Not sure, might have something to do with the version of node or the memory limit on the raspbian.
If worse comes to worse, you can `NODE_TLS_REJECT_UNAUTHORIZED=0` which is not recommended for most applications, it disables the https verification, but it will likely solve the issue
