### ISSUE TITLE
Invalid API-key, IP, or permissions for action, request ip: xx.xx.xx.x

### ISSUE THREAD

**Issue by byjameson** [jaggedsoft/node-binance-api#414]
Hello i made all configrations right, but it gives error code -2015 , Invalid API-key, IP, or permissions for action, request ip: xxx.xx.x.xx 

When i use console.log( await binance.futuresAccount() );

Thank you for your response

**Comment by jaggedsoft** [comment]
did you create a new api key since futures came out? you can only get futures permissions on brand new api keys

**Comment by byjameson** [comment]
I have handle it 8 hours ago! but there is a new problem, first of all when i open position long or short, i cant close it because you dont have any function. To make opposite position its not working. it make other way position, second of history of positions is not work wery well, it doesnt reflect truth. You have to fix them dude. I have a algorithm if you would like, i can share it with you and it can make 300% per month. write me gokhancava@gmail.com. but first fix them
