### ISSUE TITLE
first of all when i open position long or short, i cant close it because you dont have any function. To make opposite position its not working.

### ISSUE THREAD

**Issue by byjameson** [jaggedsoft/node-binance-api#415]
I have handle it 8 hours ago! but there is a new problem, first of all when i open position long or short, i cant close it because you dont have any function. To make opposite position its not working. it make other way position, second of history of positions is not work wery well, it doesnt reflect truth.

**Comment by jaggedsoft** [comment]
> I cant close it because you dont have any function

try a reduceOnly order

**Comment by jaggedsoft** [comment]
You might have better success with this library
https://github.com/Ashlar/binance-api-node/

I am not paid for my work, you can submit a pull request for any changes you desire.

**Comment by byjameson** [comment]
how can i make reduce only order?

**Comment by jaggedsoft** [comment]
use futuresPositionRisk to see your open positions and profit

```js
if ( side == 'LONG' ) order = await binance.futuresMarketSell( obj.symbol, amount, {reduceOnly: true} )
else order = await binance.futuresMarketBuy( obj.symbol, amount, {reduceOnly: true} )
```

**Comment by byjameson** [comment]
it worked thanks.

**Comment by byjameson** [comment]
if you would like, i can take you in my bot system
