### ISSUE TITLE
Individual Symbol Book Ticker Streams / All Book Tickers Stream missing in websocket implementation

### ISSUE THREAD

**Issue by cwolters** [jaggedsoft/node-binance-api#419]
The "Individual Symbol Book Ticker Streams" and "All Book Tickers Stream" is missing in websocket implementation.

For reference see https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#individual-symbol-book-ticker-streams

Would be great to add it!
Thank you!

**Comment by jaggedsoft** [comment]
Thank you very much. I will also work on the futures websockets as soon as I have some time

**Comment by jaggedsoft** [comment]
This will be in the next release being issued in an hour or less. Wow this function is fast, the data is sent in realtime.

```js
    // Spot Trading: bookTickers stream includes the bid/ask price & amount, for all symbols
    binance.websockets.bookTickers( response => {
        console.log( response );
    } );

    // Spot Trading: bookTickers stream includes the bid/ask price & amount, for a symbol
    binance.websockets.bookTickers( 'BTCUSDT', console.log );
```
