### ISSUE TITLE
Additional options for fetching trades

### ISSUE THREAD

**Issue by mstijak** [jaggedsoft/node-binance-api#42]
Sorry to bug again.

The `trades` method doesn't allow any parameters. Would something like this make sense:

```
trades: function(symbol, callback, options) {
	signedRequest(base+"v3/myTrades", {symbol:symbol, ...options}, function(data) {
		if ( callback ) return callback.call(this, data, symbol);
	});
},
```

**Comment by jaggedsoft** [comment]
No bugging going on here, just want to make this better over time, thanks for the suggestion

Yes something like that looks like it makes a lot of sense

**Comment by jaggedsoft** [comment]
Thank you again for your contributions!

Can't seem to get the 'limit' parameter to work. Any ideas?
```js
binance.trades("BNBBTC", function(trades, symbol) {
	console.log(symbol+" trade history", trades);
}, {limit: 2});
```

**Comment by mstijak** [comment]
That's strange. Using `fromId` works for me..

**Comment by jaggedsoft** [comment]
Maybe I'm doing something wrong
this doesn't seem to work for me either

```binance.trades("BNBBTC", function(trades, symbol) {
	console.log(symbol+" trade history", trades);
}, {fromId: 11240989});```

**Comment by mstijak** [comment]
I did a quick look at my code and it seems that both parameters are passed
`{ limit: 500, fromId: lastTradeId }`.
I have no other ideas. It seems to be working for me.

**Comment by jaggedsoft** [comment]
My mistake, I added this to my aggTrades instead of myTrades. I really like this and will expand this to other functions in the future
Thank you again
