### ISSUE TITLE
Support for 100ms depth stream

### ISSUE THREAD

**Issue by joelrich** [jaggedsoft/node-binance-api#425]
Currently, the library only supports 1s depth streams. By changing the the stream to `<symbol>@depth@100ms` the update frequency is increased. Would you accept a pull request which makes the depth stream configurable? Like the following:

```js
new Binance({
    depth: 'depth@100ms'
})
```

**Comment by jaggedsoft** [comment]
i'm open to it, but it might be cleaner to accept a parameter like this:

```js
/**
* Futures WebSocket mark price
* @param {symbol} symbol name or false. can also be a callback
* @param {function} callback - callback function
* @param {string} speed - 1 second updates. leave blank for default 3 seconds
* @return {string} the websocket endpoint
*/
futuresMarkPriceStream: function fMarkPriceStream( symbol = false, callback = console.log, speed = '@1s' ) {
    if ( typeof symbol == 'function' ) {
        callback = symbol;
        symbol = false;
    }
    let reconnect = () => {
        if ( Binance.options.reconnect ) fMarkPriceStream( symbol, callback );
    };
    const endpoint = symbol ? `${ symbol.toLowerCase() }@markPrice` : '!markPrice@arr'
    let subscription = futuresSubscribeSingle( endpoint+speed, data => callback( fMarkPriceConvertData( data ) ), { reconnect } );
    return subscription.endpoint;
},
```

**Comment by joelrich** [comment]
So, something like this then?
```js
depth: function depth ( symbols, callback, speed='' )
depthCache: function depthCacheFunction( symbols, callback, limit = 500, speed='' )
```
As a consequence, if you have multiple `depthCache` invocations with different speeds, they will all update the same cache.

**Comment by jaggedsoft** [comment]
yeah fair point, perhaps it deserves more thought. to me the easiest sounds like setting it to as fast as possible by default (because why not)

Maybe we could have a global speed option that defaults to as fast as possible or go with your original idea. I like it

**Comment by joelrich** [comment]
Ok, I will create a pull request for the global option then. And based on your other response, I think I will call it depthSpeed which can be set to '' or '@100ms' with a default of '@100ms'. The use the old behavior, you would then have to set it to ''. Does that sound fine? Or would you like to do this on your own?

**Comment by jaggedsoft** [comment]
that sounds great. I would love to do more myself, but I've been working 90+ hours a week for the past several months and have no more free time. so every bit of help is very much appreciated! ciao friend, and thank you.

**Comment by joelrich** [comment]
Pull request: https://github.com/jaggedsoft/node-binance-api/pull/426

Two notes:
- Not sure where to document the depthSpeed option. It can be set to '' (for 1s) or '@100ms'.
- The "Websockets symbol/array depthcache" tests do not test what they are supposed to do in my opinion. Even if I set depthSpeed to an invalid value, the tests will still pass. I think this is because the first event is not a websocket event, but comes from the snapshot itself.

The following snippet can be used to test the behaviour:
```js
let Binance = require('./node-binance-api.js');
let binance = new Binance({depthSpeed: ""}); // "", "@100ms" or anything else to break it

let last = Date.now();
binance.websockets.depthCache("BNBUSDT", function () {
    console.log("duration", Date.now() - last);
    last = Date.now();
});
```

**Comment by jaggedsoft** [comment]
we might have to do the test case with a simple subscription instead of depthcache in order to keep it simple. thanks!

**Comment by joelrich** [comment]
I think this is covered by the `websockets.depth` test, isn't it? This one at least fails for invalid depth streams.

**Comment by bmino** [comment]
I've been fixing this locally for a few weeks and figured I'd submit a PR and looky here, I'm not the only one!

I'd send my vote for just changing the update speed behind the scenes to 100ms without another optional parameter.

Depth cache websocket are the only endpoints that support a configurable update speed, and why would anybody reasonably want to ignore cache updates that would otherwise be available?

Keep in mind that if done via a parameter, code changes will be needed for:
1. `depthCacheStaggered` method parameter
    * Subsequent call to `this.depthCache`
2. `depthCache` method parameter
    * Singular symbol stream builder
    * Array of symbols stream builder
    * Subsequent call during reconnect

**Comment by joelrich** [comment]
@bmino I just don't think it's a good practice to change behavior like this in a minor release. Consider the following use case as an example: If somebody writes the oderbooks into a database, then this minor release will increase the volume by 10x. Since this is rather unexpected, it may result in out of disk space errors (e.g. because only the latest day is kept).

If this were my own library, I would have introduced the option and set it to the old value. In the next major release, I would have changed the default value of the option.
