### ISSUE TITLE
(WebSocket) chart & futuresChart — never setting isFinal:true

### ISSUE THREAD

**Issue by jaggedsoft** [jaggedsoft/node-binance-api#438]
```js
( async () => {
    const Binance = require( 'node-binance-api' );
    process.on( 'unhandledRejection', up => { throw up } )
    const binance = new Binance( {verbose:true} );
    binance.setOption( 'verbose', true );

    binance.futuresChart( 'BTCUSDT', '1m', ( symbol, interval, chart ) => {
        let lastKey = Object.keys( chart ).pop();
        if ( chart[lastKey].isFinal ) {
            process.stdout.clearLine();
            process.stdout.cursorTo( 0 );
            console.info( chart,`BINGO! ${ symbol } ${ interval }` );
        } else {
            process.stdout.write( '.' );
        }
    }, 2 )
} )();
```

I suppose the best workaround is checking if the time exceeds the previous closeTime.

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/83662853-5ff2a080-a5c8-11ea-81c2-99856f3f7e29.png)

**Comment by numerized** [comment]
Hello there, amazing module, thanks!
Very helpful examples as well.

I've found that isFinal:true never shows in the socket result for this chunk of code:

```
binance.websockets.chart("ETHUSDC", "1m", (symbol, interval, chart) => {
    let tick = binance.last(chart);
    console.log(chart[tick])
}

```

To detect that I have the final candle I have to do this:

```
if (chart[tick].isFinal !== false) {
    console.log(chart[tick])
}
```

Then I know that I have the final candle:

<img width="414" alt="Screenshot 2021-02-21 at 02 06 10" src="https://user-images.githubusercontent.com/166829/108612475-68566a00-73e9-11eb-83e2-fe1ccb4c11ec.png">
