### ISSUE TITLE
What's the minimun LOT_SIZE? I can buy with binance mobile app but can't do this with node-binance-api

### ISSUE THREAD

**Issue by ProgrammingLife** [jaggedsoft/node-binance-api#439]
My code is:
```
async function testBuy() {
	const price = 0.08883;
	const quantity = 168.9;
	try {
		const response = await binance.buy("ADAUSDT", quantity, price, { type: "LIMIT" }, false);
	} catch(e) {
		console.log(e); 
// I get: "statusCode": 400, "body": "{\"code\":-1013,\"msg\":\"Filter failure: LOT_SIZE\"}",
	}
}
testBuy();
```
Calculation: 0.08883 * 168.9 = 15.003387 USDT 
According to Binance limits: https://www.binance.com/en/trade-rule - the minimum trading amount for ADA is: 0.1ADA. But in my case it's: 168ADA. And my price satisfies to min step size there: 0.00001.

What's wrong?

**Comment by ProgrammingLife** [comment]
Sorry it's my fault. For those who will have such problem look carefully here: https://api.binance.com/api/v3/exchangeInfo it's all about precision.

**Comment by jaggedsoft** [comment]
Not just precision but the min_notional needs to be met in addition to the minimum quantity. if you need help join the [binance api telegram](https://t.me/binance_api_english)
