### ISSUE TITLE
What is binance-exchange/node-binance-api ?

### ISSUE THREAD

**Issue by flolege** [jaggedsoft/node-binance-api#441]
What is this api?

It looks official, but it was forked from this repo ?

**Comment by jaggedsoft** [comment]
this project is the main repository, the other one is a fork that i also maintain, but this one is newer.
I won the first binance api programming competition and this is the most popular binance api wrapper, though lately i'm having a hard time keeping up with the new features which might be part of the reason why binance is focusing on making their own official releases.
an official api would be something made by binance themselves, which is something they're only now starting to do. i guess this would be considered a community api, it's 100% maintained by the users with no intervention of binance. Some of the things I implement are way different than the "standard" binance way in the interest of making it easier for newbies or power users.
I asked binance for only a small discount on trading fees to incentivize my development time but they declined. and I'm working 90 hours a week lately so i have very little time to make changes. but i will improve things as soon as i can

**Comment by jaggedsoft** [comment]
https://binance.zendesk.com/hc/en-us/articles/115002103732

**Comment by flolege** [comment]
Wow many thanks for the detailed response! Interesting and good to know. Keep up the good work, I appreciate you commitment.
