### ISSUE TITLE
is there any way to put the stoploss order in the futuresmarket

### ISSUE THREAD

**Issue by vicentxxye** [jaggedsoft/node-binance-api#469]
i try it with   order = await binance.futuresSell('BTCUSDT', quantity, price1, { stopPrice: stopprice1, type: type })

get the feed back

with

 { code: -1116, msg: 'Invalid orderType.' }

**Comment by vicentxxye** [comment]
var k = Math.abs(price - entry);
    var a = +(k - 15);
    let type = "STOP_LOSS";
    var price1 = +(entry + a);
    var price2 = +(entry - a);
    var stopprice1 = +(entry + a + 1);
    var stopprice2 = +(entry - a - 1);
    let quantity = Math.abs(position);

**Comment by jaggedsoft** [comment]
I think you're just missing the 'type' being STOP_LOSS
here's some of my messy code testing trailing stops, stop losses and take profits. After you buy, the stop loss needs to be a sell order and vice versa.

this might work: I was using it as a `TAKE_PROFIT_MARKET`
```js
await binance.futuresOrder( 'SELL', 'BTCUSDT', 0.001, false, { type: 'STOP_LOSS_MARKET', stopPrice, closePosition: true } );
```
---
```js
let firstOrder = type == 'BUY' ? await binance.futuresMarketBuy( market, positionSize, { newOrderRespType: 'RESULT' } ) : await binance.futuresMarketSell( 'BTCUSDT', 0.001, { newOrderRespType: 'RESULT' } );
    console.info( firstOrder );

let stopPrice = type == 'BUY' ? Number( firstOrder.avgPrice ) + 1.5 : Number( firstOrder.avgPrice ) - 1.5;
let trailProfit = await binance.futuresOrder( counterSide, market, positionSize, false, { type: 'TRAILING_STOP_MARKET', callbackRate: 0.1, reduceOnly: true } );
console.info( trailProfit );
// let stopOrder = await binance.futuresOrder( counterSide, 'BTCUSDT', 0.001, false, { type: 'TAKE_PROFIT_MARKET', stopPrice, closePosition: true } );
// console.info( stopOrder );
```

**Comment by vicentxxye** [comment]
thank for your answer .

i do the let   before 
as
let type = "STOP_LOSS";
_____________________________
i tried your way with  
await binance.futuresOrder( 'SELL', 'BTCUSDT', 0.001, false, { type: 'STOP_LOSS_MARKET', stopPrice, closePosition: true } );
like this 

var slmove = async() => {
    var k = Math.abs(price - entry);
    var a = +(k - 15);
    let type = "STOP_LOSS";
    var price1 = +(entry + a);
    var price2 = +(entry - a);
   var stopprice1 = +(entry + a + 1);
    var stopprice2 = +(entry - a - 1);
    let quantity = Math.abs(position);
    console.log(position, price1, price2, entry, a, k, stopprice1, stopprice2)

    if (k > 75 && k < 3000) {
      (position > 0) ? order = await binance.futuresOrder('SELL', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice: stopprice1, cloesePosition: true }): order = await binance.futuresOreder('BUY', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice: stopprice2, closePosition: true })
    } else if (k > 55 && k <= 75) {
       (position > 0) ? order = await binance.futuresOrder('SELL', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice: stopprice1, cloesePosition: true }): order = await binance.futuresOreder('BUY', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice: stopprice2, closePosition: true })
    } else if (k > 10 && k <= 55) {
        (position > 0) ? binance.futuresOrder('SELL', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice, cloesePosition: true }).then((result) => {
            console.log(result)
        }): await binance.futuresOrder('BUY', 'BTCUSDT', quantity, false, { type: 'STOP_LOSS_MARKET', stopPrice: stopprice2, closePosition: true })
    } else console.log("nok")
    console.log('k=' + k)


but it  didnt work still get the  feed of  { code: -1116, msg: 'Invalid orderType.' }
i dont know why it cant work .

**Comment by jaggedsoft** [comment]
Valid Order Types for futures:

LIMIT
MARKET
STOP
STOP_MARKET
TAKE_PROFIT
TAKE_PROFIT_MARKET
TRAILING_STOP_MARKET

https://binance-docs.github.io/apidocs/futures/en/

**Comment by vicentxxye** [comment]
thank you  get you

**Comment by bcfsunali** [comment]
> I think you're just missing the 'type' being STOP_LOSS
> here's some of my messy code testing trailing stops, stop losses and take profits. After you buy, the stop loss needs to be a sell order and vice versa.
> 
> this might work: I was using it as a `TAKE_PROFIT_MARKET`
> 
> ```js
> await binance.futuresOrder( 'SELL', 'BTCUSDT', 0.001, false, { type: 'STOP_LOSS_MARKET', stopPrice, closePosition: true } );
> ```
> 
> ```js
> let firstOrder = type == 'BUY' ? await binance.futuresMarketBuy( market, positionSize, { newOrderRespType: 'RESULT' } ) : await binance.futuresMarketSell( 'BTCUSDT', 0.001, { newOrderRespType: 'RESULT' } );
>     console.info( firstOrder );
> 
> let stopPrice = type == 'BUY' ? Number( firstOrder.avgPrice ) + 1.5 : Number( firstOrder.avgPrice ) - 1.5;
> let trailProfit = await binance.futuresOrder( counterSide, market, positionSize, false, { type: 'TRAILING_STOP_MARKET', callbackRate: 0.1, reduceOnly: true } );
> console.info( trailProfit );
> // let stopOrder = await binance.futuresOrder( counterSide, 'BTCUSDT', 0.001, false, { type: 'TAKE_PROFIT_MARKET', stopPrice, closePosition: true } );
> // console.info( stopOrder );
> ```

Is this Working...?  I tried but got an error, " code: -1116, msg: 'Invalid orderType.'"

**Comment by bcfsunali** [comment]
> LIMIT
> MARKET
> STOP
> STOP_MARKET
> TAKE_PROFIT
> TAKE_PROFIT_MARKET
> TRAILING_STOP_MARKET

It's working... Thanks 👍

**Comment by Film-Worachai** [comment]
`binance.futuresOrder('SELL', symbol, quantity, false, { type: 'STOP_MARKET', workingType: 'MARK_PRICE', stopPrice: price, closePosition: true })`

`binance.futuresOrder('BUY', symbol, quantity, false, { type: 'STOP_MARKET', workingType: 'MARK_PRICE', stopPrice: price, closePosition: true })`
