### ISSUE TITLE
How to transfer from Futures to Main account?

### ISSUE THREAD

**Issue by byjameson** [jaggedsoft/node-binance-api#470]
Hello, i couldnt see you solution to -> How to transfer from Futures to Main account?

**Comment by jaggedsoft** [comment]
binance added support for that this week
https://binance-docs.github.io/apidocs/spot/en/#account-list-user_data

i won't have time to add it for a bit but hopefully someone will put in a pull request

**Comment by byjameson** [comment]
please do that. i need that too much.

**Comment by guygberg** [comment]
Created a pull request for this issue

**Comment by jaggedsoft** [comment]
available in `v0.11.12` https://github.com/jaggedsoft/node-binance-api/commit/7c885b416a807a1f6f19462f70041fb66a5f88f7
