### ISSUE TITLE
I need transfer money from futures to spot!

### ISSUE THREAD

**Issue by byjameson** [jaggedsoft/node-binance-api#489]
Hello sir, I need transfer money from futures to spot. Please make it is urgent.

**Comment by guygberg** [comment]
Hi 

If you are referring to the below, it already been implemented and is available for you.
The function is   futuresTransferBtwSpotFutres( asset, amount, type ).
Let me know if you have any questions.
 
![image](https://user-images.githubusercontent.com/40508367/92684195-99f8de80-f33d-11ea-9588-b145969fe7f3.png)

Regards
Guy
