### ISSUE TITLE
quick syntax error

### ISSUE THREAD

**Issue by jsappme** [jaggedsoft/node-binance-api#49]
node-binance-api.js:431
                marketSell: function(symbol, quantity, flags = {type: 'MARKET'} callback = false) {
                                                                                ^^^^^^^^

**the comma is missing**

SyntaxError: Unexpected identifier

marketSell: function(symbol, quantity, flags = {type: 'MARKET'}, callback = false) {
			order('SELL', symbol, quantity, 0, flags, callback);
		},

**Comment by jaggedsoft** [comment]
Thank you. Fixed
