### ISSUE TITLE
Binance API Deprecation [effective on Septembre 9th!]

### ISSUE THREAD

**Issue by waterdrop01** [jaggedsoft/node-binance-api#491]
As per [Binance API announcement](https://www.binance.com/en/support/articles/c386a9ce44e74e15a796f56289a763d6), `outboundAccountInfo` data stream is now deprecated.
![Screenshot from 2020-09-07 15-23-48](https://user-images.githubusercontent.com/47316824/92392706-f6ca7e00-f11e-11ea-94e4-a70f35eaabb7.png)

But looking at `node-binance-api` [source code](https://github.com/jaggedsoft/node-binance-api/blob/8c7ac82270aa97e0dc90ad25fe85753d1dcace79/node-binance-api.js#L1888), the deprecated type is still in use, and the new type `outboundAccountPosition` is not used.
![Screenshot from 2020-09-07 15-29-14](https://user-images.githubusercontent.com/47316824/92392688-ee724300-f11e-11ea-81ac-e41f1be9d08b.png)

What is the recommended way to handle this API change? (effective in 2 days)

Thanks!

**Comment by gunar** [comment]
Reminder that we've deprecated `outboundAccountInfo` on 6075392. I've just received a new notification from Binance (on Telegram) that they'll deprecate it soon so it seems they're delaying the breaking change. Whenever it happens, our work is done already.
