### ISSUE TITLE
Wrong endpoint in userFutureData when renew listenKey

### ISSUE THREAD

**Issue by blacksabbather** [jaggedsoft/node-binance-api#500]
"userDataStream?listenKey" should be "listenKey?listenKey"

**Comment by arenddeboer** [comment]
I submitted a PR for this https://github.com/jaggedsoft/node-binance-api/pull/501

**Comment by blacksabbather** [comment]
how to use git to get your fix?

**Comment by arenddeboer** [comment]
As a hot patch, you could  overwrite node_modules/node-binance-api/node-binance-api.js with https://raw.githubusercontent.com/arenddeboer/node-binance-api/master/node-binance-api.js or wait for PR to merge and a new release on npm.

**Comment by jaggedsoft** [comment]
thank you guys, should be available on npm `v0.12.1`
