### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by FoxBearBear** [jaggedsoft/node-binance-api#503]
When I try to run  **console.info( await binance.futuresTime())**, which is shown right [https://openbase.io/js/node-binance-api](url) here as an example, it gives me the following error.

 console.info( await binance.futuresTime())
               ^^^^^

SyntaxError: missing ) after argument list

**Comment by jaggedsoft** [comment]
I cannot reproduce this issue
