### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by FoxBearBear** [jaggedsoft/node-binance-api#504]
Once again, following the recommendations from  [https://openbase.io/js/node-binance-api](url) with the following script

> let ticker = await binance.prices();
> console.info(`Price of BNB: ${ticker.BNBUSDT}`);
>

It gives me the following error

let ticker = await binance.prices();
             ^^^^^

SyntaxError: await is only valid in async function

**Comment by jaggedsoft** [comment]
wrap your program in async tags like this, its way easier
```js
(async () => {
    const Binance = require('node-binance-api');
    const binance = new Binance().options({
    APIKEY: '<key>',
    APISECRET: '<secret>'
    });
    let ticker = await binance.prices();
    console.info(ticker);
})();
```

**Comment by FoxBearBear** [comment]
> wrap your program in async tags like this, its way easier

The whole program? 

Thank you for the quick reply!

**Comment by FoxBearBear** [comment]
> wrap your program in async tags like this, its way easier

The whole program ? 

Thank you for the quick reply!

**Comment by jaggedsoft** [comment]
yeah that's what I do most of the time. I wish you didn't need to do that
every time (it should be automatic) but coding that way is much cleaner
than using callbacks


https://github.com/jaggedsoft

**Comment by FoxBearBear** [comment]
It's still returning **_undefined_** :/

**Comment by jaggedsoft** [comment]
cannot reproduce issue
