### ISSUE TITLE
"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"

### ISSUE THREAD

**Issue by FoxBearBear** [jaggedsoft/node-binance-api#507]
I am trying to make an order of size 24.67 with a MIN_NOTIONAL: 10.00000000 and it is giving me this error.

      {
        "filterType": "MIN_NOTIONAL",
        "minNotional": "10.00000000",
        "applyToMarket": true,
        "avgPriceMins": 5
      }

**Comment by jaggedsoft** [comment]
means not ordering enough, please see telegram for support
