### ISSUE TITLE
futuresPrices failing unexpectedly from time to time

### ISSUE THREAD

**Issue by meetmangukiya** [jaggedsoft/node-binance-api#508]
```
1|dum      | 2020-09-25T07:59:55: TypeError: data.reduce is not a function
1|dum      | 2020-09-25T07:59:55:     at Object.futuresPrices (/home/phoenix/bots/dum/node_modules/node-binance-api/node-binance-api.js:3412:25)
1|dum      | 2020-09-25T07:59:55:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|dum      | 2020-09-25T07:59:55:     at async Promise.all (index 2)
```

running into this error unexpectedly, works at times, doesn't at some. I checked the source, nothing seems wrong. Been wrecking my brain against this. Seems like a very simple error, yet haven't found any solution. :sweat:

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L3679

need to add some sort of validation function. please test if you're able, line 3679

likely getting connection reset or timed out due to too many requests
```js
if ( !data || !Array.isArray(data) ) return data;
return data.reduce( ( out, i ) => ( ( out[i.symbol] =  i.price ), out ), {} );
```

**Comment by meetmangukiya** [comment]
100% sure we are not hitting rate limits. Also, wouldn't your suggestion return two different type of items?

**Comment by jaggedsoft** [comment]
no it'll return the error if there's an error otherwise the data as expected

**Comment by meetmangukiya** [comment]
I have ported the code to use ccxt. Won't be verifying anytime soon. So keep this open or close it as you see fit.
