### ISSUE TITLE
Kline streams (chart) strange behavior

### ISSUE THREAD

**Issue by Amantel** [jaggedsoft/node-binance-api#509]
Hello! 
Using `binance.websockets.chart(['ADABNB'], '1h', async (symbol, interval, chart) => { doSomething(); }`
Expected behavior: new 'signal' each hour. 
Issue: new 'signal' each minute for 3 minutes, then silence for 10 minutes or so, then another tick and so on. Definitely not in 1 tick in hour. 

I am pretty confused :(

**Comment by 2pd** [comment]
`Update Speed: 2000ms`
https://binance-docs.github.io/apidocs/spot/en/#trade-streams

Based on the API, this Klines stream updates every 2s, which means the server pushes the latest data for the last bar every 2 seconds.

**Comment by Amantel** [comment]
Thanks! 
It pushes data every 2s if there is anything new (which is not the case for a lot of pairs), thus my `doSomething` function will be get a signal as soon as anything changes (but not faster than once in 2000ms)
