### ISSUE TITLE
All-zeros lending API response

### ISSUE THREAD

**Issue by ProgrammingLife** [jaggedsoft/node-binance-api#514]
I am trying to do:

```
await binance.useServerTime();

const lendingData = await binance.lending();
console.log("response:", lendingData);

const response = await binance.balance(); 
console.log("response:", response);
```

I get all zeros in lending API:
```
response: {
  totalAmountInBTC: '0',
  totalAmountInUSDT: '0',
  totalFixedAmountInBTC: '0',
  totalFixedAmountInUSDT: '0',
  totalFlexibleInBTC: '0',
  totalFlexibleInUSDT: '0',
  positionAmountVos: [
```
but I have absolutely correct (not zero) amount in balance response.

What do I do wrong? What permissions should I give to the API-key for doing lending request? Isn't the same permissions as in the case with getting balances with which I don't have any problems?

**Comment by jaggedsoft** [comment]
How are you instantiating your program? creating the new Binance() code .. I haven't used lending yet so I'm not sure how it works but I remember when futures API came out you needed to create a new api key or you couldn't access the futures data.
