### ISSUE TITLE
Some of my futures orders become EXPIRED before they can get executed

### ISSUE THREAD

**Issue by jsappme** [jaggedsoft/node-binance-api#518]
Did anyone experience this issue? For me it happens randomly (1 on 5 times).

Here is the code I am using:

```
const res = await binance.futuresBuy( pair, amount, exit_price.toFixed(2));
current_order_id = res.orderId
const rest = await binance.futuresOrderStatus( "BTCUSDT", {orderId: current_order_id} )
```

**Comment by jaggedsoft** [comment]
This is because the default order type is GTX. (this matches the web interface)
If you want your orders to be regular limit orders, change the order type to GTC
```js
const buyOrder = await binance.futuresBuy( pair, amount, exit_price.toFixed(2), { timeInForce: 'GTC' } );
```

**Comment by jsappme** [comment]
Thank you very much @jaggedsoft 

Great pkg, keep up this great job.

**Comment by YoleYu** [comment]
@jaggedsoft I met the same problem will update the lib version(the old version is some years ago). I want to know why the default value is set to GTX not GTC? Thanks.
