### ISSUE TITLE
Futures MARKET order got an API error

### ISSUE THREAD

**Issue by anwebdevelopers** [jaggedsoft/node-binance-api#528]
Hi. I am trying to place a MARKET order and I get an error with the code "-1022" and the text "Signature for this request is not valid." What is the problem? It seems, for my part, I'm doing everything right.
![image](https://user-images.githubusercontent.com/26022868/100335177-1d95a380-2fee-11eb-99b3-b88a124a6536.png)
![image](https://user-images.githubusercontent.com/26022868/100335570-94cb3780-2fee-11eb-9e47-b2d79910bb48.png)

**Comment by jaggedsoft** [comment]
it does not look like you're using this library, we have no mention of binanceMain in our source

**Comment by anwebdevelopers** [comment]
![image](https://user-images.githubusercontent.com/26022868/100567331-a7d95280-32e1-11eb-902a-a25381bdb4b1.png)
I use this lib for several years...

**Comment by anwebdevelopers** [comment]
> it does not look like you're using this library, we have no mention of binanceMain in our source

I use this lib for several years...

![image](https://user-images.githubusercontent.com/26022868/100567470-fbe43700-32e1-11eb-8aba-26c43e1fd2d0.png)
