### ISSUE TITLE
Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed.

### ISSUE THREAD

**Issue by dawadam** [jaggedsoft/node-binance-api#532]
Hi, i have this error sometimes :
`Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed.`
When this happens, all requests raise the same error.
I precise it was after a ETIMEDOUT
And i'm using client with "useServerTime" option set at true.

**Comment by jaggedsoft** [comment]
not sure which function is causing that error, with more info I can try to reproduce it

**Comment by preethamdpg** [comment]
I got the same error when I used binance testnet api keys
