### ISSUE TITLE
Limit take profit order

### ISSUE THREAD

**Issue by Ermak1243** [jaggedsoft/node-binance-api#535]
Hello. Please show me how can i send limit take profit order to close my opened position, like pressing a button "Limit" in line with open position.

**Comment by Kuzmich100kM** [comment]
If we are talking about futures, then I have not found a short way. I would be glad for a hint. I implemented the button like this:
1. In Backend get all pairs and filter with (entryPrice !== 0)

```js
;(async () => {
	let res = await binance.futuresPositionRisk() // return array with all 72 pairs
	let openPosition = res.filter(el => +el.entryPrice !== 0) // filter only open positions
	return res
})()
```
2. Send this to the front-end, make a button there that sends a sell / buy request to the back-end.
3. Create a new order on the backend

```js
;(async (symbol, amount, price) => {
	await binance.futuresSell(symbol, amount, price)
        console.log(`Futures Limit SELL  |  ${symbol}  |  ${amount}  |  ${price}`)
})()
```

**Comment by Ermak1243** [comment]
> If we are talking about futures, then I have not found a short way. I would be glad for a hint. I implemented the button like this:
> 
> 1. In Backend get all pairs and filter with (entryPrice !== 0)
> 
> ```js
> ;(async () => {
> 	let res = await binance.futuresPositionRisk() // return array with all 72 pairs
> 	let openPosition = res.filter(el => +el.entryPrice !== 0) // filter only open positions
> 	return res
> })()
> ```
> 
> 1. Send this to the front-end, make a button there that sends a sell / buy request to the back-end.
> 2. Create a new order on the backend
> 
> ```js
> ;(async (symbol, amount, price) => {
> 	await binance.futuresSell(symbol, amount, price)
>         console.log(`Futures Limit SELL  |  ${symbol}  |  ${amount}  |  ${price}`)
> })()
> ```

Strange, when i did this, the order was not placed. But now exhibited. Thank you!
