### ISSUE TITLE
userFutureData throw an error if APIKEY is not valid

### ISSUE THREAD

**Issue by Kuzmich100kM** [jaggedsoft/node-binance-api#537]
If Apikey is not valid the server crashes with an error

This code:
```js
const margin_call_callback = res => log(res)
const order_update_callback = res => log(res)
const account_update_callback = res => log(res)

;(() =>
	binance.websockets.userFutureData(
		margin_call_callback,
		account_update_callback,
		order_update_callback
	))()
```

And this error:

![изображение](https://user-images.githubusercontent.com/46998842/101994988-45b02280-3ccf-11eb-821f-89b62bfcb258.png)

**Comment by waterdrop01** [comment]
I agree, could be more user friendly. Also, It crashes the node.js application :)

**Comment by jaggedsoft** [comment]
Thank you!!
