### ISSUE TITLE
Issue with marketBuy method

### ISSUE THREAD

**Issue by matty8444** [jaggedsoft/node-binance-api#54]
I'm attempting to use the marketBuy method but get a response of "{ code: -1013, msg: 'Invalid price.' }". I am not passing in a price as it is a marketBuy. Code looks like:

binance.marketBuy("ADAETH", 50, function(response) {
console.log(response)
})

**Comment by nickvorie** [comment]
Having the same issue. Looking at the source for marketBuy, you should be passing an object as the third argument, and the callback as the fourth. 

I'm getting the same response, though.

**Comment by Cpetegit** [comment]
workaround without changing the api code:

flags = {
    type: "MARKET"
}

binance.marketBuy("BNBBTC", 2 , flags,  function (response) { 
    console.log(response);
})

**Comment by jaggedsoft** [comment]
Thank you @Cpetegit I will publish a release fixing this soon

**Comment by jaggedsoft** [comment]
Resolved with https://github.com/jaggedsoft/node-binance-api/commit/8bf3cde02379e20ba085d9460d9158487515d8d7

Thank you very much!

**Comment by nickvorie** [comment]
Thanks @Cpetegit !
