### ISSUE TITLE
How to transfer from spot account to delivery futures account?

### ISSUE THREAD

**Issue by waterdrop01** [jaggedsoft/node-binance-api#540]
Hello,

I can't find which function should be used to transfer from spot account to delivery futures account?

Also, Is there a way to directly call an API method/endpoint (manually)?

Thanks!

**Comment by Kuzmich100kM** [comment]
To see all the functions that are in this library use this:

```js
const Binance = require("node-binance-api")
const binance = new Binance().options({
	APIKEY: "",
	APISECRET: "",
})

console.log(binance)
```

**Comment by waterdrop01** [comment]
Thanks @Kuzmich100kM! 

I imagine there is not such function then :)

**Comment by waterdrop01** [comment]
fixed by https://github.com/jaggedsoft/node-binance-api/pull/542
