### ISSUE TITLE
Signature for this request is not valid.

### ISSUE THREAD

**Issue by Daniel-Rafique** [jaggedsoft/node-binance-api#558]
When making a call to: binance.futuresTransferAsset() the response is: 

```
[Object: null prototype] {
  code: -1022,
  msg: 'Signature for this request is not valid.'
}
```

**Comment by Jabbaxx** [comment]
Did you check your keys etc ?
https://dev.binance.vision/t/faq-signature-for-this-request-is-not-valid/176

**Comment by Daniel-Rafique** [comment]
Solved!
