### ISSUE TITLE
question on stop orders

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [jaggedsoft/node-binance-api#560]
Hi, 

how would one identify if a TAKE_PROFIT or STOP_LOSS order has been filled?
Is it possible to give it an individual ID ? Not talking about OCO. It seems the "stopClientOrderId" field is only available for OCO. Why is that?

**Comment by jaggedsoft** [comment]
try telegram or binance developers
https://t.me/binance_api_english
https://dev.binance.vision/
https://developers.binance.com/
