### ISSUE TITLE
Futures with additional parameters "newClientOrderId"

### ISSUE THREAD

**Issue by Kuzmich100kM** [jaggedsoft/node-binance-api#565]
Hello. How can send a new order on **Futures** with a parameter **newClientOrderId** ?
In Spot and Margin i was find: 

```js
 const marginOrder = ( side, symbol, quantity, price, flags = {}, callback = false ) => {
       ...
        if ( typeof flags.newClientOrderId !== 'undefined' ) opt.newClientOrderId = flags.newClientOrderId;
}
        
```
But on the Futures there is no such.

**Comment by jsappme** [comment]
Any update on this?

**Comment by Kuzmich100kM** [comment]
I think no. Otherwise, the topic would be closed ((

**Comment by jsappme** [comment]
So there is no way to use this pkg if we want to pass the newClientOrderId in new orders?

**Comment by Kuzmich100kM** [comment]
If the creator of the package said that he definitely does not plan to do this, then it would be possible to make a hook. But he is still silent ((.

**Comment by Kuzmich100kM** [comment]
It turns out that there you just had to add this value to the params object.

`binance.futuresBuy(symbol, qty, prc, { newClientOrderId: "1234567879"})`

It's sad that no one has suggested before :(
