### ISSUE TITLE
Version on NPM is outdated

### ISSUE THREAD

**Issue by adrianmcli** [jaggedsoft/node-binance-api#59]
I spent 2 hours scratching my head trying to figure out why my options for the candlesticks endpoint wasn't working. And then I dug deeper into the code and realized that the README reflected a version of the package that hasn't been published yet.

**Comment by jaggedsoft** [comment]
what has changed?

**Comment by adrianmcli** [comment]
Candlestick options. The `limit`, `startDate`, `endDate` options don't do anything in the current version on NPM.

**Comment by jaggedsoft** [comment]
i'm very confused because npm should just download the changes from github here / or the latest published release file with all the changes included

**Comment by adrianmcli** [comment]
NPM will download from the latest version that was pushed using the `npm publish` command, not from the master branch of this repo (unless I specify it). My suspicion is that `npm publish` has not been run since [that change](https://github.com/jaggedsoft/node-binance-api/pull/55) was merged.

**Comment by adrianmcli** [comment]
You can try it yourself by just doing `npm install node-binance-api` and then going to your `node_modules` folder and inspect line 608 of the `node-binance-api.js` file.

**Comment by jaggedsoft** [comment]
Thanks for your help! `v0.3.9` is now live on the stable branch https://github.com/binance-exchange/node-binance-api/commit/3a0c754bbc4bdb68638afac3d619c7b328676901

**Comment by adrianmcli** [comment]
Happy to. Thanks for creating this project.
