### ISSUE TITLE
How to use http_proxy ?

### ISSUE THREAD

**Issue by aquilatrindade** [jaggedsoft/node-binance-api#598]
Please I need help, and sorry for opening this issue, but I am really without a solution for my application.

I have a copy trade robot with 400 customers at binance, and I easily pass the limit of requests per minute.

I have 3 IPS on a VPS and I need to go through the Binance request weight limit.

I divided my application into 3 parts, websocket, app1 and app2 and I would need each 1 to have a different ip, I've tried to put hostname in http, express and nothing, I know we have http_proxy as a possible solution for what I need, but I don't know how use in my 3 different apps and thus share the load of the request limit.

the applications are on the same machine, but I can't come up with the logic in the code or structure that I need to have it work.

ps: if you have a charitable soul willing to help me i will be happy as a reward i can exempt the fees for using my robot (lol). But seriously, whoever interests me can even pay if I have to.

thank you for your support and time.

EDIT:

It's solved with code below?

binance.options({
    proxy: {
        auth: {
            username:'',
            password:''
        },
        host:'my_ip',
        port:'my_port'
    }
});

**Comment by ubarbaxor** [comment]
If you have several proxies available, put their config in there.
If you use your own VPS as ip and put the same host for all 3 applications, then it won't make a difference.
I'm confused as to why the amount of customers would make a difference. Are you getting rate limited by IP or by API KEY ?

My best guess would be :
- Have a server listen to the markets, decide what should be done
- for each of your customer, have them run a client. This client subscribes via WS(S) to the server, and gets their copy orders there, then uses its own API key to pass the orders.

If that solves your issue, please mark the ticket as resolved.
If you need advice for writing code / understanding the workings of it, please contact in private.

**Comment by aquilatrindade** [comment]
@ubarbaxor 

I have an application running on the server with 1 ip only, my clients have their apis all connected to my robot, the robot executes 1 purchase order for example, and all other clients execute the same order from the same server / ip . I'm overcoming the weight limit at Binance, that's why I use a proxy.

I'm testing with free proxies for now, if you want to help me I can pass a part of the code to check, the problem is just finding the best way to do this.

I need my application to run for api 400 all at once from the same server but without breaking the Binance weight limit of 1200 / minute

**Comment by aquilatrindade** [comment]
No responses i'll try alone, tks.
