### ISSUE TITLE
Does the fututeMarket function (Buy/Sell) send quantity in percentage or in absolute value?

### ISSUE THREAD

**Issue by gustavo-dev** [jaggedsoft/node-binance-api#609]
I'm new to this API and I'm developing a bot for a customer, so I can't mess around. 

![image](https://user-images.githubusercontent.com/42685889/110517217-5531e280-80e9-11eb-897d-5647b5b74ee9.png)

He said to me to place orders with 5% of the balance. So should I calculate the 5% or does the Future API accept percentages?
If I do need to calculate, how could I do it?

Thanks in advance

**Comment by tonyth00** [comment]
Hi,
Pretty sure futuresMarketBuy/futuresMarketSell functionality requires you to calculate the absolute value. The official binance futures API does not accept percentage as input. [https://binance-docs.github.io/apidocs/futures/en/#new-order-trade](url)

**Comment by gustavo-dev** [comment]
Hey @tonyth00, thank you for your response, but I have a question. I did some digging and came to this calculation:

```
balance * 0.05 * leverage / BTC Price (Best Bid or Best Ask)
```

What's the difference between the calculation you described and this one? I'm sorry if this is a stupid question, I have minimal knowledge about cryptos and trading. And one last thing, how would I do this in code? Is there any socket stream for this "leverage bracket" or do I need to make a request every time I place a trade, and should I multiply notionalCap or notionalFloor?

**Comment by tonyth00** [comment]
Hi,

If you adjust the leverage to 125x, notice that the maximum position is 50,000 USDT. This is the `notionalCap`. So no matter how much money you have in your account, the maximum size will be this amount. You can increase position size by reducing your leverage to the next bracket (250,000 USDT at 100x). 

![image](https://user-images.githubusercontent.com/10070184/110872696-26507380-8285-11eb-890b-6aa2d85adccf.png)

`futuresLeverageBracket` is a single request, you only need to call it once at initialization. It returns leverage brackets for all coins. Leverage brackets don't change very often. Once you have selected a leverage, you can access this object to get `notionalCap`.

The formula you provided returns the number of BTC to buy. If this value exceeds `notionalCap / BTC price`, the order will be rejected. In this case you might consider the minimum of the two values to make sure the order executes.

**Comment by gustavo-dev** [comment]
Ohh I get it :) Tysm @tonyth00, I'll close this issue now
