### ISSUE TITLE
binance.futuresHistDataId 

### ISSUE THREAD

**Issue by ChenYCL** [jaggedsoft/node-binance-api#617]
back `{
    "code": -1002,
    "msg": "You are not authorized to execute this request."
}`

**Comment by updatesvc** [comment]
You need to apply for historical data, after that they will grant your API keys access if you are approved.
You can apply here.
https://www.binance.com/en/support/faq/e707685b4e0f408fa7c1b9ccd8ea7aa9

**Comment by ChenYCL** [comment]
😄 thank for your reply

**Comment by updatesvc** [comment]
welcome
