### ISSUE TITLE
Can newClientOrderId be sent when placing an order

### ISSUE THREAD

**Issue by finrojo** [jaggedsoft/node-binance-api#640]
I'm not able to see where I can generate my own newClientOrderId and send with my order. I am listening to the userData websocket and can see the one coming back that Binance generate but I need to be able to send my own so I can reference the incoming data to my log of orders I've sent.

Is this possible?

**Comment by Kuzmich100kM** [comment]
Already asked this question
[https://github.com/jaggedsoft/node-binance-api/issues/565#issue-793520907](url)

**Comment by finrojo** [comment]
Sorry, I'm a bit confused as I've only just started using the method in this way in nestJS using typescript, am I able to add a callback so I can attach the newClientOrder? How would I go about that?

`      if (data.type === 'MARKET') {
        buyResult = await binance.marketBuy(data.symbol, data.quantity);
      } else {
        buyResult = await binance.buy(data.symbol, data.quantity, data.price);
      }`

**Comment by denernun** [comment]
await binance.marketBuy(data.symbol, data.quantity, *newClientOrderId:
'xyz'*);

**Comment by finrojo** [comment]
Fantastic, thanks for the answer, that has worked for me and made a huge difference!
