### ISSUE TITLE
Buy with Stable coin or Postfix coin 

### ISSUE THREAD

**Issue by heysyam99** [jaggedsoft/node-binance-api#679]
Hi, how can i marketBuy using stable coin instead of how many coins I want to buy like the system in binance? For example, for the symbol BTCUSDT, I will just need to put how much USDT I want to spend, for example, 10 USDT and it will calculate how much will get the BTC automatically and will buy it with the current market price. Thank you.

![Screenshot 2021-05-27 at 3 33 53 PM](https://user-images.githubusercontent.com/35216709/119784600-f5392400-bf00-11eb-9c6b-583de915db50.png)

**Comment by heyimbrucelee** [comment]
@heysyam99 hey syam ! how did you solved it ? i'm facing same issue :/

**Comment by heysyam99** [comment]
hey @heyimbrucelee , I just pull the project and update the code manually for now since there is already pull request for this but take a long time to merge. here is the PR and you can update the code yourself. https://github.com/jaggedsoft/node-binance-api/pull/626

**Comment by heyimbrucelee** [comment]
@heysyam99 tyvm :)

**Comment by Lippa73** [comment]
could someone please show an example how I would structure the query after the code has been added?

**Comment by heysyam99** [comment]
@Lippa73 I have replied to your comment in the PR.

Putting the comment [link](https://github.com/jaggedsoft/node-binance-api/pull/626#issuecomment-993506403) for others reference
