### ISSUE TITLE
Performance Issues in WebSocket Cache Depth

### ISSUE THREAD

**Issue by ramonconrado94** [jaggedsoft/node-binance-api#698]
I had some performance issues, don't know if is something wrong in my code.

Just caching with redis and get the depth in some points of the system

Here is a snippet... Could someone help me?

```
 async getDepthWS(symbol): Promise<any> {
    const Binance = require('node-binance-api');
    const binance = new Binance().options({
      keepAlive: true,
      log: console.log,
      verbose: true,
    });

    binance.websockets.depthCache([symbol], async (symbol, depth) => {
      const bidsArray = new Array<any>();
      const asksArray = new Array<any>();
      let bids = binance.sortBids(depth.bids);
      let asks = binance.sortAsks(depth.asks);
      for (const price in bids) {
        bidsArray.push(price);
      }
      for (const price in asks) {
        asksArray.push(price);
      }
      await this.cacheManager.set(
        symbol,
        { bids: bidsArray.slice(0, 20), asks: asksArray.slice(0, 20) },
        { ttl: 10 },
      );
    });
  }
```

**Comment by kanish-111** [comment]
or just use direct code, i use 
`const WS  =require('ws')
const ws = new WS('wss://stream.binance.com:9443/ws/btcusdt@bookTicker')
ws.on('message', function incoming(data) {
console.log(date);
}`
this will be faster i guess, just chceck it, ps: install ws first.

**Comment by ramonconrado94** [comment]
> or just use direct code, i use
> `const WS =require('ws') const ws = new WS('wss://stream.binance.com:9443/ws/btcusdt@bookTicker') ws.on('message', function incoming(data) { console.log(date); }`
> this will be faster i guess, just chceck it, ps: install ws first.

Yeah... you're right! Thanks, I'll try.
