### ISSUE TITLE
"Filter failure: LOT_SIZE"

### ISSUE THREAD

**Issue by azharuniverse** [jaggedsoft/node-binance-api#71]
There should be a way to handle this from within the library to make it easier for a novice developer.

Suggestioin : 
`order_volume.toFixed(3).slice(0,-1)`

**Comment by georgeMuraveiAlkh** [comment]
@azharuniverse Each currency pair has own LOT_SIZE so there is no universal solution - only to get current lot_size for each pair from Binance. Also I dont know for what you are using `slice(0,-1)` here. `order_volume.toFixed(2)` will return the same.

**Comment by azharuniverse** [comment]
Doing `order_volume.toFixed(2)` will round the value to mentioned precision causing the volume to exceed available balance. 

I agree with you. such things should be handled be Binance itself.

**Comment by georgeMuraveiAlkh** [comment]
Also you will trapped with small amounts of shitcoins -> as example You buying 10 some of coin which cant be smaller than 1 -> after Binance get their comission in your wallet you see 9.985 BUT you can sell only 9 or will get LOT_SIZE error in case of selling 9.985 @jaggedsoft where we can complain on this issue? Will Binance fix this stupidity?

**Comment by jaggedsoft** [comment]
Buy some BNB then you only get charged commission in BNB (and it lowers your fees to .05% instead of .25% like most exchanges)

I do the same thing with my binance bot that I do with all my other bots

```if ( order_qty > available_balance ) order_qty = available_balance;```

**Comment by azharuniverse** [comment]
@jaggedsoft, `if ( order_qty > available_balance ) order_qty = available_balance;` wont prevent this error. Example is given in @georgeMuraveiAlkh  comment
Its the issue of presion in order_qty which must satisfy. `(quantity-minQty) % stepSize == 0`
