### ISSUE TITLE
Universal websocket client?

### ISSUE THREAD

**Issue by rafaelklaessen** [jaggedsoft/node-binance-api#75]
Would it be an option to switch to [universal-websocket-client](https://www.npmjs.com/package/universal-websocket-client)?
You'd have to use the browser WebSocket API, but it would work for both browsers and Node applications.

**Comment by jaggedsoft** [comment]
API's won't work from browsers or plugins because CORS only allows connections from binance.com

**Comment by rafaelklaessen** [comment]
> CORS only allows connections from binance.com

@jaggedsoft Why so?
Also, websockets *do* work. The API could work via JSONP too but I'm not sure about that.

**Comment by jaggedsoft** [comment]
Could you give me an example via JSONP that works?
```js
get_json("https://api.binance.com/api/v1/ticker/24hr", function(response){ console.log(response); });
    function get_json(url, callback) {
        var http = new XMLHttpRequest();
        http.onreadystatechange = function() {
            if ( http.readyState == 4 && http.status == 200 ) {
                callback(http.responseText);
            }
        }
        http.open("GET", url, true);
        http.send();
    }
```
![image](https://user-images.githubusercontent.com/4283360/35197933-2c637bde-fe9c-11e7-84d3-66e8c05d91c9.png)

**Comment by jaggedsoft** [comment]
I haven't tested the websockets since they moved to stream.binance.com, but I know before they definitely didn't work.
Just tested them, still not working:
![image](https://user-images.githubusercontent.com/4283360/35197976-c9841298-fe9c-11e7-9113-72147d19c45d.png)

**Comment by rafaelklaessen** [comment]
I forgot that JSONP requires the server to take a callback parameter, so I can't get it working :(

**Comment by rafaelklaessen** [comment]
Also, websockets did work in a previous version see [this fork](https://github.com/gmverdon/node-binance-api).

**Comment by rafaelklaessen** [comment]
But you're right.
Thanks for the info & making this amazing API :)

**Comment by chintanmahant** [comment]
How to use socket api
