### ISSUE TITLE
WebSocket connection closed!

### ISSUE THREAD

**Issue by vaielab** [jaggedsoft/node-binance-api#76]
Even if I leave the option to reconnect as default (true), after a while I get an message telling me WebSocket connection closed! 
Is there a way to always force reconnect, I would like the websocket to stay online for a very long period of time.

Here my binance options:
binance.options({
    'APIKEY': 'XXX',
    'APISECRET': 'XXX',
    'recvWindow': 60000,
    'test': true
});

Thanks

**Comment by jaggedsoft** [comment]
If you are getting the message that your websocket is closed, but `reconnect` is on (it's on by default) then don't worry, it's reconnecting seamlessly and your program should keep running as if nothing ever happened.
Why this happens, I don't know. For me it only happens on the "Account balance" websocket

**Comment by vaielab** [comment]
Currently using it on both trades and candlesticks websocket (on 2 different programs running at the same time), and most of the time I get the error message pretty much at the same time.

**Comment by vaielab** [comment]
Hi there, since I made this issue, I managed to add a lots of logs to my software.
I am now certain that if we get the "WebSocket connection closed!" message, we will not get anything from that websocket anymore, and I think I know why

When you subscribe to a websocket you make a reconnect function like so

```
let reconnect = function() {
  if ( options.reconnect ) subscribe(symbol.toLowerCase()+'@aggTrade', callback);
};
subscribe(symbol.toLowerCase()+'@aggTrade', callback, reconnect);
```

So you actually only 1 reconnection available, if the websocket reconnect for any reason, the reconnect function kickin, but if this one close again, subscribe() was called with no reconnect parameter so it default to false.

I don't know if all websocket is affected by this, but at trade and candlesticks are.

**Comment by jaggedsoft** [comment]
Thanks! I'll make sure trade and candlestick get updated

**Comment by jaggedsoft** [comment]
Perhaps this would work:
```js
					let reconnect = function retry() {
						if ( options.reconnect ) subscribe(symbol.toLowerCase()+'@aggTrade', callback, retry);
					};
```

**Comment by jaggedsoft** [comment]
Thanks again for the report, this fixed it
I'll push a new release tomorrow

Test code:
```js
binance.websockets.trades(['BNBBTC', 'ETHBTC'], (trades) => {
	let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
	console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
setInterval(function() {
	// Terminate all websocket endpoints, every 6 sec
	let endpoints = binance.websockets.subscriptions();
	for ( let endpoint in endpoints ) {
		console.log("..terminating websocket: "+endpoint);
		let ws = endpoints[endpoint];
		ws.terminate();
	}
},6000);
```

**Comment by vaielab** [comment]
Thank you so much!
