### ISSUE TITLE
Error: unexpected server response (504)

### ISSUE THREAD

**Issue by vaielab** [jaggedsoft/node-binance-api#77]
From time to time, I get this error message:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (504)
    at ClientRequest._req.on (/home/user1/Desktop/Projets/binance/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)

Sometime I get the error secondes after I launch the app, and other time it will occur hours/days after the app is running.
I only use one the trade websocket, but I pass it a large (50+) array of symbol to watch

**Comment by jaggedsoft** [comment]
504 response means Gateway timeout, yes this has happened to me a few times as well
If you are opening a large number of connections it is best to do it in a timer so there is a 150ms delay between each new connection
Otherwise it tries to open all the connections at once and can get you blacklisted temporarily

**Comment by jaggedsoft** [comment]
We should do this automatically in a future release
But here is the approach I take: (175ms delay between new connections)
```js
let count = 0;
for ( symbol of markets ) {
	setTimeout(binance.websockets.chart, count++ * 175, symbol, "5m", callback);
}
```

**Comment by vaielab** [comment]
But what about when the script is running for hours, and suddently this happend?

**Comment by jaggedsoft** [comment]
It might happen if many websockets are disconnected at once and try to reconnect without delay.
I suppose the fix would be automatically applying a user-configurable delay to reconnections

**Comment by jaggedsoft** [comment]
Idea: Every time a websocket is disconnected, we keep an internal timer
The first websocket reconnects immediately
The second one would wait 150ms
The third one would wait 300ms, etc

If more than a second passes since the last disconnection, timer reset so the next one will be instant again
This way, if many happen in a short time, they will all be reconnected properly. If not, we can keep retrying the connection until it's successfully restored

**Comment by vaielab** [comment]
I think this could work.
Can we do this globally for all websocket (if I'm using candlesticks, trades & depth at the same time)

**Comment by jaggedsoft** [comment]
Yep, sounds good. I don't have a lot of time this week but this should be a nice addition

**Comment by vaielab** [comment]
So I took a loot at the ws library that you are using, and I think I found out something.

When we receive an 504 or 502 or 50X error, ws throw an error at line 653

```
  this._req.on('response', (res) => {
    if (!this.emit('unexpected-response', this._req, res)) {
      this._req.abort();
      this.finalize(new Error(`unexpected server response (${res.statusCode})`));
    }
  });
```

How I understand this correctly, ws send a message on the event listener "unexpected-response" and since we don't listen to it, it abord the connection and throw an error.
But in node-binance-api, around line 208, if we add something like this

```
ws.on('unexpected-response', function(req, res) {
  //Check if the socket is still up, log the error
  //Maybe abord like in ws, but reconnect just after
  return true;
});
```
Ws will never throw that new Error, and the script will not crash.
We will have to be careful since if we receive an 504, we should reconnect with a delay not to flood the server while they already think we are flooding them.

In any case, even if the socket dies, at least the script won't crash (I think)

**Comment by jaggedsoft** [comment]
Thank you very much, going to start testing this.

**Comment by jaggedsoft** [comment]
Available in `v0.4.8` but still without the automatic reconnect. At least now we will see what's happening

**Comment by vaielab** [comment]
Good news, it seem to be working, this morning I received "WebSocket Unexpected response: trigeth@aggTrade" and the app is still working.
As expected, the websocket still closed, but at least, the rest of the app is still running

**Comment by nickreese** [comment]
Thank you for this. This problem has been plaguing our paper trade only app for a while now. This was one of the last items on my to handle. Stoked to test it out. 

Also, one thing we should keep in mind is that caches depth/candle would need to be cleared and rebuilt when the websocket timeout/error occurs.

**Comment by nickreese** [comment]
Digging into this, it looks like if we can see it was a depth websocket that erred, then just need to detect if we were maintaining an active depthCache for that symbol and if so call the getDepthCache(symbol) function. From my snooping, this looks as though it would handle the clearing of that invalid cache and resubscribing/building it afresh.

**Comment by jaggedsoft** [comment]
Great, so when this happens the websocket definitely needs to be reconnected? I'll go ahead and take care of that today if so

**Comment by jaggedsoft** [comment]
This might work. I'll test it out in a short while

```js
ws.on('unexpected-response', function(req, res) {
	//Check if the socket is still up, log the error
	//Terminate and reconnect?
	//Thanks vaielab https://github.com/jaggedsoft/node-binance-api/issues/77
	options.log('WebSocket Unexpected response: '+this.endpoint);
	if ( reconnect && options.reconnect ) {
		options.log('..WebSocket reconnecting: '+this.endpoint);
		reconnect();
	}
	return true;
});
```

**Comment by nickreese** [comment]
Not sure if it definitely needs to be connected, but if there is any delay in the update of a depth websocket our depth cache is invalid. 

Testing this now:

```
ws.on('unexpected-response', function(req, res) {
			ws.terminate();
			if(this.endpoint.indexOf('@depth') > -1){
				let symbol = this.endpoint.slice(0, this.endpoint.indexOf('@depth'));
				getDepthCache(symbol);
				return;
			}
			if ( reconnect && options.reconnect ) {
				try {
					reconnect();
				} catch ( error ) {
					options.log('WebSocket reconnect error: '+error.message);
				}
			}
			//Check if the socket is still up, log the error
			//Terminate and reconnect?
			//Thanks vaielab https://github.com/jaggedsoft/node-binance-api/issues/77
			options.log("WebSocket Unexpected response: "+this.endpoint, res);
			return true;
		});
```

**Comment by vaielab** [comment]
Based on the documentation from https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md
We should check the header of the response from binance if the header code is 429 or 418, we should not reconnect immediatly, at least putting it in a timeout

**Comment by jaggedsoft** [comment]
Websockets don't have header codes though

**Comment by nickreese** [comment]
Here is the cache update id issue: https://github.com/binance-exchange/node-binance-api/issues/21

I hope to be able to test this.

**Comment by Dannybert** [comment]
Hello guys,

I have been building an application for myself to scan certain pumps etc. where I need the 1h and the 5m candle data to track such events. The code was working fine, untill it gave a 431 error: Unexpected server response. I am using c9 to code but I read that it was probably the websocket having to get to many request at once. So I tried putting a setInterval() in there, but still the same error.

Any suggestions on the code and how that problem is solved?

```
var market1h = 'not yet defined';
var market5m = 'not yet defined';

binance.prevDay(false, (error, prevDay) => {
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		markets.push(symbol);
	}
	setInterval(get1hData, 1500);
	setInterval(get5mData, 1200);
	
	function get1hData(){
	    binance.websockets.candlesticks(markets, '1h', (candlestickData) => {
		let tick = binance.last(candlestickData);
		market1h = candlestickData[tick];
		io.emit('market1h', market1h);
	    });
	}
	function get5mData(){
	    binance.websockets.candlesticks(markets, '5m', (candlestickData) => {
		let tick = binance.last(candlestickData);
		market5m = candlestickData[tick];
		io.emit("market5m", market5m);
	    });
	}
});
```

**Comment by jaggedsoft** [comment]
Your functions get1hData and get5mData only need to be called once. You can make it work by simplifying it like this:
```js
var market1h = 'not yet defined';
var market5m = 'not yet defined';

binance.prevDay(false, (error, prevDay) => {
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		markets.push(symbol);
	}
    binance.websockets.candlesticks(markets, '1h', (candlestickData) => {
		let tick = binance.last(candlestickData);
		market1h = candlestickData[tick];
		io.emit('market1h', market1h);
    });
    binance.websockets.candlesticks(markets, '5m', (candlestickData) => {
		let tick = binance.last(candlestickData);
		market5m = candlestickData[tick];
		io.emit("market5m", market5m);
    });
});
```

**Comment by Dannybert** [comment]
Thanks for the improvement, but I had this before and now it gives a 431:
Unexpected server response error. This was the reason I tried to add the
setInterval() in there, but didn't help at all. I have the API requests
outside of the 'GET' requests for the page. I believe I make to many
requests to the API and should add something that prevents this error from
happening. Any suggestions?

Thanks anyway so far.


Kind regards,

Danny Hoekstra


Op za 16 mrt. 2019 om 19:45 schreef Jon Eyrick <notifications@github.com>:

**Comment by Dannybert** [comment]
Thanks for the reply, but I had it without the setInterval at first, but in the node.js code I have the functions outside of the get requests. Is it better to move it inside the get requests?? Or do you need to see the whole code to be able to check if it is okay?

Thanks anyway!

Greetings,

Danny
