### ISSUE TITLE
Trades call failing with code -1104

### ISSUE THREAD

**Issue by misterdeveloper** [jaggedsoft/node-binance-api#80]
Hello,

I'm not sure if anyone else had this issue, but when I try to pull all of the trades for ETHBTC, I get a code 1104 returned.

Code:

            binance.trades("ETHBTC", function(trades, symbol) {
                console.log(symbol+" trade history", trades);
            });

Error:

{ code: -1104,
  msg: 'Not all sent parameters were read; read \'4\' parameter(s) but was sent \'5\'.' }

Anyone else run into this? Ideas?

TIA!

**Comment by jaggedsoft** [comment]
I'm not getting this issue on the latest version
You're providing the API key correctly and everything?

**Comment by jaggedsoft** [comment]
Important to note that now in the latest version, the format is this:
binance.trades("SNMBTC", (error, trades, symbol) => {
	console.log(symbol+" trade history", trades);
});

**Comment by misterdeveloper** [comment]
Using same API key - works for everything else except for trades. 

I tried the format from your example and still get the following error:

{ code: -1104,
  msg: 'Not all sent parameters were read; read \'4\' parameter(s) but was sent \'5\'.' }

I am not sure if I am using the latest version.  Will try that next.  Thank you for the follow up!

**Comment by jaggedsoft** [comment]
I'd say whatever problem existed was probably fixed, current version is `v0.4.5` but any version after 0.4.0 needs you to add `error` in front of every callback response
example: `binance.trades("ETHBTC", function(trades, symbol) {`
changed to
`binance.trades("ETHBTC", function(error, trades, symbol) {`

**Comment by misterdeveloper** [comment]
I pulled the latest and it seems to be working as you said.  I'm not sure what the original issue was.  Thank you so much for your help!
