### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by DaliborTrampota** [jaggedsoft/node-binance-api#804]
It seems like the owner of this repository is no longer maintaining this repository so I've decided to fork it and fix it up, add [futures user stream](https://binance-docs.github.io/apidocs/futures/en/#start-user-data-stream-user_stream) and many more starting today. Feel free to contribute and make this package complete again! https://github.com/DaliborTrampota/node-binance-api

**Comment by myfender** [comment]
I see yours is also unmaintained... is there anyone updating it?
