### ISSUE TITLE
Websockets timing out

### ISSUE THREAD

**Issue by ryanvanbelkum** [jaggedsoft/node-binance-api#82]
I'm trying to establish a websocket connection and consistently seeing a timeout error.

Ex: 
```
binance.websockets.prevDay('BNBBTC', (error, response) => {
  console.log(response);
});
```
Outcome
```
Uncaught Error: connect ETIMEDOUT 13.112.109.76:9443
```

However, some of the streams are working as expected.
Ex:
```
binance.websockets.depthCache(["BNBBTC"], function(symbol, depth) {
```

Is anyone else seeing this issue?

Here is my function
``` 
function setupWebsocks(){
  binance.options({
    APIKEY: "......",
    APISECRET: "......"
  });

  binance.websockets.prevDay('BNBBTC', (error, response) => {
  	console.log(response);
  });
}
```

**Comment by jaggedsoft** [comment]
Are you passing multiple symbols to the function? If you pass too many at once, binance will block you for a short time. I'm working on an automatic solution for this

For now, I wait 150ms before opening another connection

**Comment by ryanvanbelkum** [comment]
@jaggedsoft Thank you for the quick reply. The issue is actually on my end (firewall). Closing.
