### ISSUE TITLE
recentTrades: Too many parameters; expected '2' and received '5'.

### ISSUE THREAD

**Issue by keyle** [jaggedsoft/node-binance-api#83]
Status 400 Bad Request
{"code":-1101,"msg":"Too many parameters; expected '2' and received '5'."}

Any ideas?

also, on a related note, there is no method for Binance's GET /api/v1/aggTrades ?

**Comment by jaggedsoft** [comment]
Thank you for your report!
added aggTrades function for next release
Fixed historicalTrades, recentTrades, aggTrades functions
```js
		aggTrades: function(symbol, options = {}, callback = false) { //fromId startTime endTime limit
			let parameters = Object.assign({symbol}, options);
			marketRequest(base+'v1/aggTrades', parameters, callback);
		},
```

```js
binance.aggTrades("BNBBTC", {limit:500}, (error, response)=>{
	console.log("aggTrades",response);
});
```

```js
binance.recentTrades("BNBBTC", (error, response)=>{
	console.log("recentTrades",response);
});
```

```js
binance.historicalTrades("BNBBTC", (error, response)=>{
	console.log("historicalTrades",response);
});
```

**Comment by keyle** [comment]
Thanks for the quick fix! Can you ping this ticket with the next release number?

**Comment by jaggedsoft** [comment]
`v0.4.6` is now live https://github.com/jaggedsoft/node-binance-api/commit/8a474093b6095da50d5310b48234bd4ef9d8b334

**Comment by alpcnet** [comment]
send_signed_request ( error )
send_public_request ( work )
