### ISSUE TITLE
Multiple Instances?

### ISSUE THREAD

**Issue by springjben** [jaggedsoft/node-binance-api#84]
How do I get multiple instances of this?

If you create 1 "options" it will over ride it if you have a system where it passes their information when they login.

**Comment by jaggedsoft** [comment]
This will be implemented soon. It's a breaking change so it will be worked into `v0.5.0`
It might take up a week or two. Very limited time at the moment
See https://github.com/jaggedsoft/node-binance-api/issues/81 for a community solution
