### ISSUE TITLE
How to close a position in hedge mode?

### ISSUE THREAD

**Issue by clientmagallanes22** [jaggedsoft/node-binance-api#842]
Can some1 help me how to close a position in hedge mode please

**Comment by clientmagallanes22** [comment]
@jaggedsoft please master

**Comment by SANGMINNNN** [comment]
Do you solve it?

**Comment by SANGMINNNN** [comment]
YES! please bro

**Comment by clientmagallanes22** [comment]
> YES! please bro

to open long
await binance.futuresMarketBuy("BTCUSDT", 0.100, {workingType: "MARK_PRICE"});
to close long
await binance.futuresMarketSell("BTCUSDT", 0.100, {positionSide: "LONG", workingType: "MARK_PRICE"});

to open short
await binance.futuresMarketSell("BTCUSDT", 0.100, {workingType: "MARK_PRICE"});
to close short
await binance.futuresMarketBuy("BTCUSDT", -0.100, {positionSide: "SHORT", workingType: "MARK_PRICE"});

**Comment by SANGMINNNN** [comment]
THX!
