### ISSUE TITLE
what to do if .withdraw() is "outdated"?

### ISSUE THREAD

**Issue by v03d** [jaggedsoft/node-binance-api#843]
https://stackoverflow.com/questions/72860726/node-binance-api-what-to-do-if-withdraw-is-outdated

'This endpoint has been deprecated, please integrate with “POST@/sapi/v1/capital/withdraw/apply”. See details in the announcement: here https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269'

**Comment by encloinc** [comment]
how did you fix this?
