### ISSUE TITLE
Recent trades returns Too many parameters

### ISSUE THREAD

**Issue by davidstoneham** [jaggedsoft/node-binance-api#85]
code (from example)

`binance.recentTrades("BNBBTC", (error, response) => {
            console.log("recentTrades", response);
        });`

error body: "{"code":-1101,"msg":"Too many parameters; expected '2' and received '5'."}"

**Comment by davidstoneham** [comment]
Turns out this should be a publicRequest not a signedRequest

**Comment by jaggedsoft** [comment]
Thank you for the report!
Have you tried the latest version? In `v0.4.6` these are actually `marketRequests`

**Comment by davidstoneham** [comment]
Yep everything works correctly in 0.4.6!

**Comment by jaggedsoft** [comment]
thank you!
