### ISSUE TITLE
Cancel all orders on a specific market without orders causes a timeout

### ISSUE THREAD

**Issue by marcovega** [jaggedsoft/node-binance-api#88]
Hello guys,

I'm posting it here since I don't know if I'm the only one with the issue. Currently, if I have NO open orders inside a market, say ETHBTC, whenever I try to cancel all orders the server won't send a response.

Is anyone having this issue? I solved it by averaging the response and adding a timeout after .5 seconds.

**Comment by jaggedsoft** [comment]
i'll test this when i can and report back

**Comment by jaggedsoft** [comment]
I can not reproduce this problem. Sorry
Cancelling all orders for a symbol like this:
```js
binance.cancelOrders("XMRBTC", (error, response, symbol) => {
	console.log(symbol+" cancel response:", response);
});
```
Returns nothing, but no error, no timeout, etc
Typically the reason for gateway timeouts are if you have too many connections opening at once
Are you opening many websocket connections in a short time?
