### ISSUE TITLE
Stop loss orders are not supported

### ISSUE THREAD

**Issue by qjflores** [jaggedsoft/node-binance-api#89]
running `binance.sell(symbol, quantity, price, {type: 'STOP_LOSS', stopPrice: price}, this.placeStopLimitOrderCallBack)` I get 

`{ code: -1013,
  msg: 'Stop loss orders are not supported for this symbol.' }`

**Comment by jaggedsoft** [comment]
Unfortunately binance only applies stop losses on certain symbols

you can see by calling exchangeInfo() or viewing here

https://api.binance.com/api/v1/exchangeInfo

**Comment by jaggedsoft** [comment]
It appears your problem is that STOP_LOSS is not supported
However STOP_LOSS_LIMIT is

**Comment by Birleyici** [comment]
> Görünüşe göre sorununuz STOP_LOSS desteklenmiyor
> Ancak STOP_LOSS_LIMIT


How can I send stop_loss_limit. Is there an api?
