### ISSUE TITLE
Websocket Reconnection/Heartbeat

### ISSUE THREAD

**Issue by tsujp** [jaggedsoft/node-binance-api#9]
I can't see anything in the implementation for heartbeat checks (although this could be done by someone using the library).

Also, is there any chance we could get automatic re-connections to the socket if the network connection drops?

**Comment by jaggedsoft** [comment]
Thanks for your suggestion!
The heartbeat keepalive is performed automatically but this only applies to the User Data websocket endpoint.
I am working on a solution to reconnect other websocket connections automatically. I will keep you updated

**Comment by jaggedsoft** [comment]
I am testing a build with this feature. Once I am sure it is stable I will publish a release

**Comment by jaggedsoft** [comment]
I believe it works as intended, will continue testing it. For now I am pushing a new build
No changes are necessary, just `npm update` and it will automatically reconnect these types of websocket connections: `chart, depthCache, candlesticks, userData`

**Comment by jaggedsoft** [comment]
Currently the websocket only attempts to reconnect once. If that attempt fails it stops trying to reconnect

I am planning on making it keep retrying automatically if it fails the first attempt
