### ISSUE TITLE
Redirect logs from node-binance-api

### ISSUE THREAD

**Issue by vaielab** [jaggedsoft/node-binance-api#90]
Hello again,

I was wondering if it was possible to send the logs back insted of using console.log
I would have seen something like a fonction passed to binance.options like 

```
binance.options.({
  APIKEY: XXX,
  APISECRET: XXX,
  logs: (log) => {
    //Do something with log
    console.log(log);
  }
});
```

By default it would be simple a console.log, so if someone don't care about changing it, it will call console.log as it is presently, but if someone want it to don't log, or record the logs, it would be an options

**Comment by jaggedsoft** [comment]
Yes I like this idea thank you for the suggestion
