### ISSUE TITLE
markeyBuy returning empty response

### ISSUE THREAD

**Issue by samilkorkmaz** [jaggedsoft/node-binance-api#91]
I can successfully call [binance.prices()](https://github.com/jaggedsoft/node-binance-api#getting-latest-price-of-a-symbol) but when I call [binance.marketBuy()](https://github.com/jaggedsoft/node-binance-api#chaining-orders-together), I get an empty response. Am I doing something wrong?

**Comment by jaggedsoft** [comment]
maybe missing the new `error` parameter which is required in the callback

```js
binance.marketBuy(symbol, amount, (error, response) => {
    if ( error ) return console.error("marketBuy",error,response);
    console.log("..Market Buy response", response);
    console.log("..order id: " + response.orderId);
});

```

Also binance always returns the price as 0 for market buys, nothing we can do about this

**Comment by iboxgithub** [comment]
Hi, I have the exact same issue, I have empty responses when I use marketBuy.
`Response = {} and error = undefined`
Do you have an idea?
I am using your lib with Promises, is it ok or should I use https://github.com/binance-exchange/binance-api-node?

Thanks for your help

**Comment by jaggedsoft** [comment]
@iboxgithub maybe you have `test` set to true

**Comment by iboxgithub** [comment]
Yes! Thanks a lot!
