### ISSUE TITLE
Error: connect ETIMEDOUT 54.238.203.159:443

### ISSUE THREAD

**Issue by droidmanspace** [jaggedsoft/node-binance-api#92]
I am trying to get candlestick using 
```
 binance.candlesticks(market, timePeriod, function(error, data, symbol) {
if error throw error
// my logic
}
```
I am passing each coinpair to the market variable and after **30 to 35** coin pairs it throws the error 
 ```
if(error) throw error
                ^

Error: connect ETIMEDOUT 54.238.203.159:443
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

```
I am having 240 coin pairs to best called but failed on 30 or more. I am using a for loop to iterate array and  I also tried setTimeOut function to delay the API call, but no use. 
Can please explain how to call **candlestick()** for 240 coin pairs ?

**Comment by jaggedsoft** [comment]
You must give a 150ms delay after every new connection otherwise you are sending them too many requests too quickly

If you are making many requests and require up-to-date data, the websocket version is much better
