### ISSUE TITLE
Unable to specify fromID

### ISSUE THREAD

**Issue by programmrz** [jaggedsoft/node-binance-api#95]
historicalTrades only allows the passing of limit and symbol, but doesnt allow the passing of fromId

(as found in the official binance api..)
string : fromId
type: LONG
required: NO
Desc: TradeId to fetch from. Default gets most recent trades.

**Comment by jaggedsoft** [comment]
Thank you for the report!

**Comment by jaggedsoft** [comment]
Resolved in https://github.com/jaggedsoft/node-binance-api/commit/bbb79fad9fae28f66ed40ca49b71a9132068fff9 and scheduled for release soon in `v0.4.8`
