### ISSUE TITLE
404 trying to load balances

### ISSUE THREAD

**Issue by LorinWeb** [jaggedsoft/node-binance-api#97]
Hi guys,

I'm having a hard time trying to load balances.
I've already double-checked the API key/secret pair.

My set-up is quite trivial:

```js
import binance from 'node-binance-api';

binance.options({
  APIKEY: '<myKey>',
  APISECRET: '<mySecret>',
  useServerTime: true, // <= this doesn't change the outcome
});

binance.prices((error, ticker) => {
  console.log('prices()', ticker); // => returns correct object
});

binance.balance(function(balances) {
  console.log('balances()', balances); // => balances() TypeError: Failed to fetch
});
```
It's throwing the following error:
`Failed to load https://api.binance.com/api/v3/account?timestamp=1517613376176&recvWindow=60000&signature=528d823f4ff4868b83096cf8cc912a9db4d262ffbed271ef642eb4bacacac1a2: Response for preflight has invalid HTTP status code 404`

Any idea why this could be happening?

**Comment by jaggedsoft** [comment]
Hi friend, starting in `v0.4.0` the balance() function was changed to this format:

```js
binance.balance((error, balances) => {
//...
}
```

**Comment by LorinWeb** [comment]
@jaggedsoft thanks for your kind reply, unfortunately, that didn't change the outcome. It still throws a 404.

**Comment by jaggedsoft** [comment]
Sounds like you might be trying to run it from the browser, due to CORS this can only be run from node.js

**Comment by LorinWeb** [comment]
Ok, this really helps. I should set this up as a server-side script then. Thank you very much!
